package com.bdcor.pip.web.data.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.bdcor.pip.core.persistence.MyBatisRepository;
import com.bdcor.pip.web.data.domain.UqsAnswer;
import com.bdcor.pip.web.data.domain.UqsAnswerExample;
import com.bdcor.pip.web.data.domain.UqsAnswerKey;

@MyBatisRepository
public interface UqsAnswerMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PIP_UQS_ANSWER
	 * @mbggenerated
	 */
	int countByExample(UqsAnswerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PIP_UQS_ANSWER
	 * @mbggenerated
	 */
	int deleteByExample(UqsAnswerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PIP_UQS_ANSWER
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(UqsAnswerKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PIP_UQS_ANSWER
	 * @mbggenerated
	 */
	int insert(UqsAnswer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PIP_UQS_ANSWER
	 * @mbggenerated
	 */
	int insertSelective(UqsAnswer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PIP_UQS_ANSWER
	 * @mbggenerated
	 */
	List<UqsAnswer> selectByExample(UqsAnswerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PIP_UQS_ANSWER
	 * @mbggenerated
	 */
	UqsAnswer selectByPrimaryKey(UqsAnswerKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PIP_UQS_ANSWER
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") UqsAnswer record,
			@Param("example") UqsAnswerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PIP_UQS_ANSWER
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") UqsAnswer record,
			@Param("example") UqsAnswerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PIP_UQS_ANSWER
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(UqsAnswer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PIP_UQS_ANSWER
	 * @mbggenerated
	 */
	int updateByPrimaryKey(UqsAnswer record);
	
	List<Map> getUqsCompleteTab(Map paramMap);
}