package com.bdcor.pip.web.fee.domain;

import java.text.SimpleDateFormat;
import java.util.Date;

import javax.persistence.Transient;

import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.transaction.annotation.Transactional;

public class PipActualReg {
   
    private String id;
    
    private String project_name;
    
    private String lcc_name;
    
    private String  fee_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIP_FEE_ACTUAL_REG.PROJECTID
     *
     * @mbggenerated
     */
    private String projectid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIP_FEE_ACTUAL_REG.LCCID
     *
     * @mbggenerated
     */
    private String lccid;

    
    private int actualCost;

    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date costDate; 
    @Transient 
    private String costDateStr;

    public String getCostDateStr() {
		return costDateStr;
	}

	public void setCostDateStr(String costDateStr) {
		this.costDateStr = costDateStr;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIP_FEE_ACTUAL_REG.SUBMITTER
     *
     * @mbggenerated
     */
    private String submitter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIP_FEE_ACTUAL_REG.INPUTIME
     *
     * @mbggenerated
     */
    private Date inputime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIP_FEE_ACTUAL_REG.id
     *
     * @return the value of PIP_FEE_ACTUAL_REG.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    } 
    
    

    public String getFee_type() {
		return fee_type;
	}

	public void setFee_type(String fee_type) {
		this.fee_type = fee_type;
	}

	public String getProject_name() {
		return project_name;
	}

	public void setProject_name(String project_name) {
		this.project_name = project_name;
	}

	public String getLcc_name() {
		return lcc_name;
	}

	public void setLcc_name(String lcc_name) {
		this.lcc_name = lcc_name;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIP_FEE_ACTUAL_REG.id
     *
     * @param id the value for PIP_FEE_ACTUAL_REG.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIP_FEE_ACTUAL_REG.PROJECTID
     *
     * @return the value of PIP_FEE_ACTUAL_REG.PROJECTID
     *
     * @mbggenerated
     */
    public String getProjectid() {
        return projectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIP_FEE_ACTUAL_REG.PROJECTID
     *
     * @param projectid the value for PIP_FEE_ACTUAL_REG.PROJECTID
     *
     * @mbggenerated
     */
    public void setProjectid(String projectid) {
        this.projectid = projectid == null ? null : projectid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIP_FEE_ACTUAL_REG.LCCID
     *
     * @return the value of PIP_FEE_ACTUAL_REG.LCCID
     *
     * @mbggenerated
     */
    public String getLccid() {
        return lccid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIP_FEE_ACTUAL_REG.LCCID
     *
     * @param lccid the value for PIP_FEE_ACTUAL_REG.LCCID
     *
     * @mbggenerated
     */
    public void setLccid(String lccid) {
        this.lccid = lccid == null ? null : lccid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIP_FEE_ACTUAL_REG.ACTUAL_COST
     *
     * @return the value of PIP_FEE_ACTUAL_REG.ACTUAL_COST
     *
     * @mbggenerated
     */
    public int getActualCost() {
        return actualCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIP_FEE_ACTUAL_REG.ACTUAL_COST
     *
     * @param actualCost the value for PIP_FEE_ACTUAL_REG.ACTUAL_COST
     *
     * @mbggenerated
     */
    public void setActualCost(int actualCost) {
        this.actualCost = actualCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIP_FEE_ACTUAL_REG.COST_DATE
     *
     * @return the value of PIP_FEE_ACTUAL_REG.COST_DATE
     *
     * @mbggenerated
     */
    public Date getCostDate() {
        return costDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIP_FEE_ACTUAL_REG.COST_DATE
     *
     * @param costDate the value for PIP_FEE_ACTUAL_REG.COST_DATE
     *
     * @mbggenerated
     */
    public void setCostDate(Date costDate) {
    	
        this.costDate = costDate;
    	SimpleDateFormat format = new  SimpleDateFormat("yyyy-MM-dd");
    	this.costDateStr=format.format(costDate);
    }  

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIP_FEE_ACTUAL_REG.SUBMITTER
     *
     * @return the value of PIP_FEE_ACTUAL_REG.SUBMITTER
     *
     * @mbggenerated
     */
    public String getSubmitter() {
        return submitter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIP_FEE_ACTUAL_REG.SUBMITTER
     *
     * @param submitter the value for PIP_FEE_ACTUAL_REG.SUBMITTER
     *
     * @mbggenerated
     */
    public void setSubmitter(String submitter) {
        this.submitter = submitter == null ? null : submitter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIP_FEE_ACTUAL_REG.INPUTIME
     *
     * @return the value of PIP_FEE_ACTUAL_REG.INPUTIME
     *
     * @mbggenerated
     */
    public Date getInputime() {
        return inputime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIP_FEE_ACTUAL_REG.INPUTIME
     *
     * @param inputime the value for PIP_FEE_ACTUAL_REG.INPUTIME
     *
     * @mbggenerated
     */
    public void setInputime(Date inputime) {
        this.inputime = inputime;
    }
}