package com.bdcor.pip.web.data.domain;

import java.util.Date;

public class PipCommDictDistrict {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIP_COMM_DICT_DISTRICT.DICT_CODE
     *
     * @mbggenerated
     */
    private String dictCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIP_COMM_DICT_DISTRICT.VCODE
     *
     * @mbggenerated
     */
    private String vcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIP_COMM_DICT_DISTRICT.VNAME
     *
     * @mbggenerated
     */
    private String vname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIP_COMM_DICT_DISTRICT.CREATE_BY
     *
     * @mbggenerated
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIP_COMM_DICT_DISTRICT.CREATE_DATE
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIP_COMM_DICT_DISTRICT.UPDATE_BY
     *
     * @mbggenerated
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIP_COMM_DICT_DISTRICT.UPDATE_DATE
     *
     * @mbggenerated
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIP_COMM_DICT_DISTRICT.IS_REMOVED
     *
     * @mbggenerated
     */
    private Short isRemoved;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIP_COMM_DICT_DISTRICT.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIP_COMM_DICT_DISTRICT.DICT_CODE
     *
     * @return the value of PIP_COMM_DICT_DISTRICT.DICT_CODE
     *
     * @mbggenerated
     */
    public String getDictCode() {
        return dictCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIP_COMM_DICT_DISTRICT.DICT_CODE
     *
     * @param dictCode the value for PIP_COMM_DICT_DISTRICT.DICT_CODE
     *
     * @mbggenerated
     */
    public void setDictCode(String dictCode) {
        this.dictCode = dictCode == null ? null : dictCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIP_COMM_DICT_DISTRICT.VCODE
     *
     * @return the value of PIP_COMM_DICT_DISTRICT.VCODE
     *
     * @mbggenerated
     */
    public String getVcode() {
        return vcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIP_COMM_DICT_DISTRICT.VCODE
     *
     * @param vcode the value for PIP_COMM_DICT_DISTRICT.VCODE
     *
     * @mbggenerated
     */
    public void setVcode(String vcode) {
        this.vcode = vcode == null ? null : vcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIP_COMM_DICT_DISTRICT.VNAME
     *
     * @return the value of PIP_COMM_DICT_DISTRICT.VNAME
     *
     * @mbggenerated
     */
    public String getVname() {
        return vname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIP_COMM_DICT_DISTRICT.VNAME
     *
     * @param vname the value for PIP_COMM_DICT_DISTRICT.VNAME
     *
     * @mbggenerated
     */
    public void setVname(String vname) {
        this.vname = vname == null ? null : vname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIP_COMM_DICT_DISTRICT.CREATE_BY
     *
     * @return the value of PIP_COMM_DICT_DISTRICT.CREATE_BY
     *
     * @mbggenerated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIP_COMM_DICT_DISTRICT.CREATE_BY
     *
     * @param createBy the value for PIP_COMM_DICT_DISTRICT.CREATE_BY
     *
     * @mbggenerated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIP_COMM_DICT_DISTRICT.CREATE_DATE
     *
     * @return the value of PIP_COMM_DICT_DISTRICT.CREATE_DATE
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIP_COMM_DICT_DISTRICT.CREATE_DATE
     *
     * @param createDate the value for PIP_COMM_DICT_DISTRICT.CREATE_DATE
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIP_COMM_DICT_DISTRICT.UPDATE_BY
     *
     * @return the value of PIP_COMM_DICT_DISTRICT.UPDATE_BY
     *
     * @mbggenerated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIP_COMM_DICT_DISTRICT.UPDATE_BY
     *
     * @param updateBy the value for PIP_COMM_DICT_DISTRICT.UPDATE_BY
     *
     * @mbggenerated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIP_COMM_DICT_DISTRICT.UPDATE_DATE
     *
     * @return the value of PIP_COMM_DICT_DISTRICT.UPDATE_DATE
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIP_COMM_DICT_DISTRICT.UPDATE_DATE
     *
     * @param updateDate the value for PIP_COMM_DICT_DISTRICT.UPDATE_DATE
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIP_COMM_DICT_DISTRICT.IS_REMOVED
     *
     * @return the value of PIP_COMM_DICT_DISTRICT.IS_REMOVED
     *
     * @mbggenerated
     */
    public Short getIsRemoved() {
        return isRemoved;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIP_COMM_DICT_DISTRICT.IS_REMOVED
     *
     * @param isRemoved the value for PIP_COMM_DICT_DISTRICT.IS_REMOVED
     *
     * @mbggenerated
     */
    public void setIsRemoved(Short isRemoved) {
        this.isRemoved = isRemoved;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIP_COMM_DICT_DISTRICT.ID
     *
     * @return the value of PIP_COMM_DICT_DISTRICT.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIP_COMM_DICT_DISTRICT.ID
     *
     * @param id the value for PIP_COMM_DICT_DISTRICT.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }
}