package com.bdcor.pip.web.material.supp.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import org.springframework.format.annotation.DateTimeFormat;

import com.bdcor.pip.client.tools.DateUtils;

public class MaterExport {

	private String stockName;// 仓库名字
	private String supplierName;// 供货商名字
	private String activeclassName;// 出库类别
	private String lccName;// 本单位名字
	private String exportLccName;// 目标单位名字
	private String type;// 1新增 2修改
	private String exportStockCode;// 目标库房
	private String exportStockName;// 目标库房名字
	private String detail;// 出库明细 库存id:出库数量;库存id:出库数量;...
	private String createDateStr ; //创建日期
	public String getCreateDateStr() {
		return DateUtils.fromatDateTime("yyyy-MM-dd", getCreateDate());
	}
	private List<MaterExportDetail> materExportDetails  =new ArrayList<MaterExportDetail>();
	public void setMaterExportDetails(List<MaterExportDetail> materExportDetails) {
		this.materExportDetails = materExportDetails;
	}
	public List<MaterExportDetail> getMaterExportDetails() {
		return materExportDetails;
	}
	public String getStockName() {
		return stockName;
	}

	public void setStockName(String stockName) {
		this.stockName = stockName;
	}

	public String getSupplierName() {
		return supplierName;
	}

	public void setSupplierName(String supplierName) {
		this.supplierName = supplierName;
	}

	public String getActiveclassName() {
		return activeclassName;
	}

	public void setActiveclassName(String activeclassName) {
		this.activeclassName = activeclassName;
	}

	public String getLccName() {
		return lccName;
	}

	public void setLccName(String lccName) {
		this.lccName = lccName;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getExportLccName() {
		return exportLccName;
	}

	public void setExportLccName(String exportLccName) {
		this.exportLccName = exportLccName;
	}

	public String getExportStockCode() {
		return exportStockCode;
	}

	public void setExportStockCode(String exportStockCode) {
		this.exportStockCode = exportStockCode;
	}

	public String getExportStockName() {
		return exportStockName;
	}

	public void setExportStockName(String exportStockName) {
		this.exportStockName = exportStockName;
	}

	public String getDetail() {
		return detail;
	}

	public void setDetail(String detail) {
		this.detail = detail;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PIP_MMS_EXPORT_MASTER.EXORDER_NO
	 * 
	 * @mbggenerated Thu Sep 11 19:23:15 CST 2014
	 */
	private String exorderNo;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PIP_MMS_EXPORT_MASTER.PROJECT_ID
	 * 
	 * @mbggenerated Thu Sep 11 19:23:15 CST 2014
	 */
	private String projectId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PIP_MMS_EXPORT_MASTER.EXORDER_NO
	 * 
	 * @return the value of PIP_MMS_EXPORT_MASTER.EXORDER_NO
	 * 
	 * @mbggenerated Thu Sep 11 19:23:15 CST 2014
	 */
	public String getExorderNo() {
		return exorderNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PIP_MMS_EXPORT_MASTER.EXORDER_NO
	 * 
	 * @param exorderNo
	 *            the value for PIP_MMS_EXPORT_MASTER.EXORDER_NO
	 * 
	 * @mbggenerated Thu Sep 11 19:23:15 CST 2014
	 */
	public void setExorderNo(String exorderNo) {
		this.exorderNo = exorderNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PIP_MMS_EXPORT_MASTER.PROJECT_ID
	 * 
	 * @return the value of PIP_MMS_EXPORT_MASTER.PROJECT_ID
	 * 
	 * @mbggenerated Thu Sep 11 19:23:15 CST 2014
	 */
	public String getProjectId() {
		return projectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PIP_MMS_EXPORT_MASTER.PROJECT_ID
	 * 
	 * @param projectId
	 *            the value for PIP_MMS_EXPORT_MASTER.PROJECT_ID
	 * 
	 * @mbggenerated Thu Sep 11 19:23:15 CST 2014
	 */
	public void setProjectId(String projectId) {
		this.projectId = projectId;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PIP_MMS_EXPORT_MASTER.ACTIVECLASS_CODE
	 * 
	 * @mbggenerated Thu Sep 11 19:23:15 CST 2014
	 */
	private String activeclassCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PIP_MMS_EXPORT_MASTER.LCC_CODE
	 * 
	 * @mbggenerated Thu Sep 11 19:23:15 CST 2014
	 */
	private String lccCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PIP_MMS_EXPORT_MASTER.USER_CODE
	 * 
	 * @mbggenerated Thu Sep 11 19:23:15 CST 2014
	 */
	private String userCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PIP_MMS_EXPORT_MASTER.USER_NAME
	 * 
	 * @mbggenerated Thu Sep 11 19:23:15 CST 2014
	 */
	private String userName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PIP_MMS_EXPORT_MASTER.CREATE_DATE
	 * 
	 * @mbggenerated Thu Sep 11 19:23:15 CST 2014
	 */
	@DateTimeFormat(pattern = "yyyy-MM-dd")
	private Date createDate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PIP_MMS_EXPORT_MASTER.CREATE_BY
	 * 
	 * @mbggenerated Thu Sep 11 19:23:15 CST 2014
	 */
	private String createBy;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PIP_MMS_EXPORT_MASTER.IS_REMOVED
	 * 
	 * @mbggenerated Thu Sep 11 19:23:15 CST 2014
	 */
	private Short isRemoved;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PIP_MMS_EXPORT_MASTER.STOCK_CODE
	 * 
	 * @mbggenerated Thu Sep 11 19:23:15 CST 2014
	 */
	private String stockCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PIP_MMS_EXPORT_MASTER.SUPPLIER_CODE
	 * 
	 * @mbggenerated Thu Sep 11 19:23:15 CST 2014
	 */
	private String supplierCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PIP_MMS_EXPORT_MASTER.EXPORT_DATE
	 * 
	 * @mbggenerated Thu Sep 11 19:23:15 CST 2014
	 */
	@DateTimeFormat(pattern = "yyyy-MM-dd")
	private Date exportDate;
	
	private String exportDateStr ;
	public String getExportDateStr() {
		return DateUtils.fromatDateTime("yyyy-MM-dd", getExportDate());
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PIP_MMS_EXPORT_MASTER.EXPORT_LCC_CODE
	 * 
	 * @mbggenerated Thu Sep 11 19:23:15 CST 2014
	 */
	private String exportLccCode;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PIP_MMS_EXPORT_MASTER.ACTIVECLASS_CODE
	 * 
	 * @return the value of PIP_MMS_EXPORT_MASTER.ACTIVECLASS_CODE
	 * 
	 * @mbggenerated Thu Sep 11 19:23:15 CST 2014
	 */
	public String getActiveclassCode() {
		return activeclassCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PIP_MMS_EXPORT_MASTER.ACTIVECLASS_CODE
	 * 
	 * @param activeclassCode
	 *            the value for PIP_MMS_EXPORT_MASTER.ACTIVECLASS_CODE
	 * 
	 * @mbggenerated Thu Sep 11 19:23:15 CST 2014
	 */
	public void setActiveclassCode(String activeclassCode) {
		this.activeclassCode = activeclassCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PIP_MMS_EXPORT_MASTER.LCC_CODE
	 * 
	 * @return the value of PIP_MMS_EXPORT_MASTER.LCC_CODE
	 * 
	 * @mbggenerated Thu Sep 11 19:23:15 CST 2014
	 */
	public String getLccCode() {
		return lccCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PIP_MMS_EXPORT_MASTER.LCC_CODE
	 * 
	 * @param lccCode
	 *            the value for PIP_MMS_EXPORT_MASTER.LCC_CODE
	 * 
	 * @mbggenerated Thu Sep 11 19:23:15 CST 2014
	 */
	public void setLccCode(String lccCode) {
		this.lccCode = lccCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PIP_MMS_EXPORT_MASTER.USER_CODE
	 * 
	 * @return the value of PIP_MMS_EXPORT_MASTER.USER_CODE
	 * 
	 * @mbggenerated Thu Sep 11 19:23:15 CST 2014
	 */
	public String getUserCode() {
		return userCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PIP_MMS_EXPORT_MASTER.USER_CODE
	 * 
	 * @param userCode
	 *            the value for PIP_MMS_EXPORT_MASTER.USER_CODE
	 * 
	 * @mbggenerated Thu Sep 11 19:23:15 CST 2014
	 */
	public void setUserCode(String userCode) {
		this.userCode = userCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PIP_MMS_EXPORT_MASTER.USER_NAME
	 * 
	 * @return the value of PIP_MMS_EXPORT_MASTER.USER_NAME
	 * 
	 * @mbggenerated Thu Sep 11 19:23:15 CST 2014
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PIP_MMS_EXPORT_MASTER.USER_NAME
	 * 
	 * @param userName
	 *            the value for PIP_MMS_EXPORT_MASTER.USER_NAME
	 * 
	 * @mbggenerated Thu Sep 11 19:23:15 CST 2014
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PIP_MMS_EXPORT_MASTER.CREATE_DATE
	 * 
	 * @return the value of PIP_MMS_EXPORT_MASTER.CREATE_DATE
	 * 
	 * @mbggenerated Thu Sep 11 19:23:15 CST 2014
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PIP_MMS_EXPORT_MASTER.CREATE_DATE
	 * 
	 * @param createDate
	 *            the value for PIP_MMS_EXPORT_MASTER.CREATE_DATE
	 * 
	 * @mbggenerated Thu Sep 11 19:23:15 CST 2014
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PIP_MMS_EXPORT_MASTER.CREATE_BY
	 * 
	 * @return the value of PIP_MMS_EXPORT_MASTER.CREATE_BY
	 * 
	 * @mbggenerated Thu Sep 11 19:23:15 CST 2014
	 */
	public String getCreateBy() {
		return createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PIP_MMS_EXPORT_MASTER.CREATE_BY
	 * 
	 * @param createBy
	 *            the value for PIP_MMS_EXPORT_MASTER.CREATE_BY
	 * 
	 * @mbggenerated Thu Sep 11 19:23:15 CST 2014
	 */
	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PIP_MMS_EXPORT_MASTER.IS_REMOVED
	 * 
	 * @return the value of PIP_MMS_EXPORT_MASTER.IS_REMOVED
	 * 
	 * @mbggenerated Thu Sep 11 19:23:15 CST 2014
	 */
	public Short getIsRemoved() {
		return isRemoved;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PIP_MMS_EXPORT_MASTER.IS_REMOVED
	 * 
	 * @param isRemoved
	 *            the value for PIP_MMS_EXPORT_MASTER.IS_REMOVED
	 * 
	 * @mbggenerated Thu Sep 11 19:23:15 CST 2014
	 */
	public void setIsRemoved(Short isRemoved) {
		this.isRemoved = isRemoved;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PIP_MMS_EXPORT_MASTER.STOCK_CODE
	 * 
	 * @return the value of PIP_MMS_EXPORT_MASTER.STOCK_CODE
	 * 
	 * @mbggenerated Thu Sep 11 19:23:15 CST 2014
	 */
	public String getStockCode() {
		return stockCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PIP_MMS_EXPORT_MASTER.STOCK_CODE
	 * 
	 * @param stockCode
	 *            the value for PIP_MMS_EXPORT_MASTER.STOCK_CODE
	 * 
	 * @mbggenerated Thu Sep 11 19:23:15 CST 2014
	 */
	public void setStockCode(String stockCode) {
		this.stockCode = stockCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PIP_MMS_EXPORT_MASTER.SUPPLIER_CODE
	 * 
	 * @return the value of PIP_MMS_EXPORT_MASTER.SUPPLIER_CODE
	 * 
	 * @mbggenerated Thu Sep 11 19:23:15 CST 2014
	 */
	public String getSupplierCode() {
		return supplierCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PIP_MMS_EXPORT_MASTER.SUPPLIER_CODE
	 * 
	 * @param supplierCode
	 *            the value for PIP_MMS_EXPORT_MASTER.SUPPLIER_CODE
	 * 
	 * @mbggenerated Thu Sep 11 19:23:15 CST 2014
	 */
	public void setSupplierCode(String supplierCode) {
		this.supplierCode = supplierCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PIP_MMS_EXPORT_MASTER.EXPORT_DATE
	 * 
	 * @return the value of PIP_MMS_EXPORT_MASTER.EXPORT_DATE
	 * 
	 * @mbggenerated Thu Sep 11 19:23:15 CST 2014
	 */
	public Date getExportDate() {
		return exportDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PIP_MMS_EXPORT_MASTER.EXPORT_DATE
	 * 
	 * @param exportDate
	 *            the value for PIP_MMS_EXPORT_MASTER.EXPORT_DATE
	 * 
	 * @mbggenerated Thu Sep 11 19:23:15 CST 2014
	 */
	public void setExportDate(Date exportDate) {
		this.exportDate = exportDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PIP_MMS_EXPORT_MASTER.EXPORT_LCC_CODE
	 * 
	 * @return the value of PIP_MMS_EXPORT_MASTER.EXPORT_LCC_CODE
	 * 
	 * @mbggenerated Thu Sep 11 19:23:15 CST 2014
	 */
	public String getExportLccCode() {
		return exportLccCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PIP_MMS_EXPORT_MASTER.EXPORT_LCC_CODE
	 * 
	 * @param exportLccCode
	 *            the value for PIP_MMS_EXPORT_MASTER.EXPORT_LCC_CODE
	 * 
	 * @mbggenerated Thu Sep 11 19:23:15 CST 2014
	 */
	public void setExportLccCode(String exportLccCode) {
		this.exportLccCode = exportLccCode;
	}
}