package com.bdcor.pip.web.data.dao;

import com.bdcor.pip.core.persistence.MyBatisRepository;
import com.bdcor.pip.web.data.domain.PipCommPatientInput;
import com.bdcor.pip.web.data.domain.PipCommPatientInputExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

@MyBatisRepository
public interface PipCommPatientInputMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIP_COMM_PATIENT_INPUT
     *
     * @mbggenerated
     */
    int countByExample(PipCommPatientInputExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIP_COMM_PATIENT_INPUT
     *
     * @mbggenerated
     */
    int deleteByExample(PipCommPatientInputExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIP_COMM_PATIENT_INPUT
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIP_COMM_PATIENT_INPUT
     *
     * @mbggenerated
     */
    int insert(PipCommPatientInput record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIP_COMM_PATIENT_INPUT
     *
     * @mbggenerated
     */
    int insertSelective(PipCommPatientInput record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIP_COMM_PATIENT_INPUT
     *
     * @mbggenerated
     */
    List<PipCommPatientInput> selectByExample(PipCommPatientInputExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIP_COMM_PATIENT_INPUT
     *
     * @mbggenerated
     */
    PipCommPatientInput selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIP_COMM_PATIENT_INPUT
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PipCommPatientInput record, @Param("example") PipCommPatientInputExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIP_COMM_PATIENT_INPUT
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PipCommPatientInput record, @Param("example") PipCommPatientInputExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIP_COMM_PATIENT_INPUT
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PipCommPatientInput record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIP_COMM_PATIENT_INPUT
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PipCommPatientInput record);
    
    public List getEntityId();
}