package com.bdcor.pip.web.data.dao;

import com.bdcor.pip.core.persistence.MyBatisRepository;
import com.bdcor.pip.web.data.domain.PipCommPatientDropLog;
import com.bdcor.pip.web.data.domain.PipCommPatientDropLogExample;
import com.bdcor.pip.web.data.filter.PatientDropLogFilter;

import java.util.List;

import org.apache.ibatis.annotations.Param;

@MyBatisRepository
public interface PipCommPatientDropLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIP_COMM_PATIENT_DROP_LOG
     *
     * @mbggenerated
     */
    int countByExample(PipCommPatientDropLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIP_COMM_PATIENT_DROP_LOG
     *
     * @mbggenerated
     */
    int deleteByExample(PipCommPatientDropLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIP_COMM_PATIENT_DROP_LOG
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String patientId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIP_COMM_PATIENT_DROP_LOG
     *
     * @mbggenerated
     */
    int insert(PipCommPatientDropLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIP_COMM_PATIENT_DROP_LOG
     *
     * @mbggenerated
     */
    int insertSelective(PipCommPatientDropLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIP_COMM_PATIENT_DROP_LOG
     *
     * @mbggenerated
     */
    List<PipCommPatientDropLog> selectByExample(PipCommPatientDropLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIP_COMM_PATIENT_DROP_LOG
     *
     * @mbggenerated
     */
    PipCommPatientDropLog selectByPrimaryKey(String patientId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIP_COMM_PATIENT_DROP_LOG
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PipCommPatientDropLog record, @Param("example") PipCommPatientDropLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIP_COMM_PATIENT_DROP_LOG
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PipCommPatientDropLog record, @Param("example") PipCommPatientDropLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIP_COMM_PATIENT_DROP_LOG
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PipCommPatientDropLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIP_COMM_PATIENT_DROP_LOG
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PipCommPatientDropLog record);
    
    
    List<PipCommPatientDropLog> query(PatientDropLogFilter filter);
}