package com.bdcor.pip.web.data.dao;

import com.bdcor.pip.core.persistence.MyBatisRepository;
import com.bdcor.pip.web.data.domain.PipCommPatientQcDrop;
import com.bdcor.pip.web.data.domain.PipCommPatientQcDropExample;
import com.bdcor.pip.web.data.domain.PipCommPatientQcDropKey;

import java.util.List;

import org.apache.ibatis.annotations.Param;

@MyBatisRepository
public interface PipCommPatientQcDropMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PIP_COMM_PATIENT_QC_DROP
	 * @mbggenerated
	 */
	int countByExample(PipCommPatientQcDropExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PIP_COMM_PATIENT_QC_DROP
	 * @mbggenerated
	 */
	int deleteByExample(PipCommPatientQcDropExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PIP_COMM_PATIENT_QC_DROP
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(PipCommPatientQcDropKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PIP_COMM_PATIENT_QC_DROP
	 * @mbggenerated
	 */
	int insert(PipCommPatientQcDrop record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PIP_COMM_PATIENT_QC_DROP
	 * @mbggenerated
	 */
	int insertSelective(PipCommPatientQcDrop record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PIP_COMM_PATIENT_QC_DROP
	 * @mbggenerated
	 */
	List<PipCommPatientQcDrop> selectByExample(
			PipCommPatientQcDropExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PIP_COMM_PATIENT_QC_DROP
	 * @mbggenerated
	 */
	PipCommPatientQcDrop selectByPrimaryKey(PipCommPatientQcDropKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PIP_COMM_PATIENT_QC_DROP
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") PipCommPatientQcDrop record,
			@Param("example") PipCommPatientQcDropExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PIP_COMM_PATIENT_QC_DROP
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") PipCommPatientQcDrop record,
			@Param("example") PipCommPatientQcDropExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PIP_COMM_PATIENT_QC_DROP
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(PipCommPatientQcDrop record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PIP_COMM_PATIENT_QC_DROP
	 * @mbggenerated
	 */
	int updateByPrimaryKey(PipCommPatientQcDrop record);
}