package com.bdcor.pip.web.data.dao;

import com.bdcor.pip.core.persistence.MyBatisRepository;
import com.bdcor.pip.web.data.domain.PipCommPatientDropLog;
import com.bdcor.pip.web.data.domain.PipCommPatientQcLog;
import com.bdcor.pip.web.data.domain.PipCommPatientQcLogExample;
import com.bdcor.pip.web.data.domain.PipCommPatientQcLogKey;
import com.bdcor.pip.web.data.filter.PatientDropLogFilter;

import java.util.List;

import org.apache.ibatis.annotations.Param;

@MyBatisRepository
public interface PipCommPatientQcLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIP_COMM_PATIENT_QC_LOG
     *
     * @mbggenerated
     */
    int countByExample(PipCommPatientQcLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIP_COMM_PATIENT_QC_LOG
     *
     * @mbggenerated
     */
    int deleteByExample(PipCommPatientQcLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIP_COMM_PATIENT_QC_LOG
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(PipCommPatientQcLogKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIP_COMM_PATIENT_QC_LOG
     *
     * @mbggenerated
     */
    int insert(PipCommPatientQcLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIP_COMM_PATIENT_QC_LOG
     *
     * @mbggenerated
     */
    int insertSelective(PipCommPatientQcLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIP_COMM_PATIENT_QC_LOG
     *
     * @mbggenerated
     */
    List<PipCommPatientQcLog> selectByExample(PipCommPatientQcLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIP_COMM_PATIENT_QC_LOG
     *
     * @mbggenerated
     */
    PipCommPatientQcLog selectByPrimaryKey(PipCommPatientQcLogKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIP_COMM_PATIENT_QC_LOG
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PipCommPatientQcLog record, @Param("example") PipCommPatientQcLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIP_COMM_PATIENT_QC_LOG
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PipCommPatientQcLog record, @Param("example") PipCommPatientQcLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIP_COMM_PATIENT_QC_LOG
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PipCommPatientQcLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIP_COMM_PATIENT_QC_LOG
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PipCommPatientQcLog record);
    
    List<PipCommPatientQcLog> query(PatientDropLogFilter filter);
}