package com.bdcor.pip.web.data.dao;

import com.bdcor.pip.core.persistence.MyBatisRepository;
import com.bdcor.pip.web.data.domain.PipReportVar;
import com.bdcor.pip.web.data.domain.PipReportVarExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

@MyBatisRepository
public interface PipReportVarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIP_REPORT_VAR
     *
     * @mbggenerated
     */
    int countByExample(PipReportVarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIP_REPORT_VAR
     *
     * @mbggenerated
     */
    int deleteByExample(PipReportVarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIP_REPORT_VAR
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String varId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIP_REPORT_VAR
     *
     * @mbggenerated
     */
    int insert(PipReportVar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIP_REPORT_VAR
     *
     * @mbggenerated
     */
    int insertSelective(PipReportVar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIP_REPORT_VAR
     *
     * @mbggenerated
     */
    List<PipReportVar> selectByExample(PipReportVarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIP_REPORT_VAR
     *
     * @mbggenerated
     */
    PipReportVar selectByPrimaryKey(String varId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIP_REPORT_VAR
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PipReportVar record, @Param("example") PipReportVarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIP_REPORT_VAR
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PipReportVar record, @Param("example") PipReportVarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIP_REPORT_VAR
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PipReportVar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIP_REPORT_VAR
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PipReportVar record);
}