package com.bdcor.pip.web.data.dao;

import com.bdcor.pip.core.persistence.MyBatisRepository;
import com.bdcor.pip.web.data.domain.UqsAnswerDrop;
import com.bdcor.pip.web.data.domain.UqsAnswerDropExample;
import com.bdcor.pip.web.data.domain.UqsAnswerDropKey;

import java.util.List;

import org.apache.ibatis.annotations.Param;

@MyBatisRepository
public interface UqsAnswerDropMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIP_UQS_ANSWER_DROP
     *
     * @mbggenerated
     */
    int countByExample(UqsAnswerDropExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIP_UQS_ANSWER_DROP
     *
     * @mbggenerated
     */
    int deleteByExample(UqsAnswerDropExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIP_UQS_ANSWER_DROP
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(UqsAnswerDropKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIP_UQS_ANSWER_DROP
     *
     * @mbggenerated
     */
    int insert(UqsAnswerDrop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIP_UQS_ANSWER_DROP
     *
     * @mbggenerated
     */
    int insertSelective(UqsAnswerDrop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIP_UQS_ANSWER_DROP
     *
     * @mbggenerated
     */
    List<UqsAnswerDrop> selectByExample(UqsAnswerDropExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIP_UQS_ANSWER_DROP
     *
     * @mbggenerated
     */
    UqsAnswerDrop selectByPrimaryKey(UqsAnswerDropKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIP_UQS_ANSWER_DROP
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UqsAnswerDrop record, @Param("example") UqsAnswerDropExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIP_UQS_ANSWER_DROP
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UqsAnswerDrop record, @Param("example") UqsAnswerDropExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIP_UQS_ANSWER_DROP
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UqsAnswerDrop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIP_UQS_ANSWER_DROP
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UqsAnswerDrop record);
}