package com.bdcor.pip.web.data.dao;

import com.bdcor.pip.core.persistence.MyBatisRepository;
import com.bdcor.pip.web.data.domain.UqsHandleView;
import com.bdcor.pip.web.data.domain.UqsHandleViewExample;
import com.bdcor.pip.web.progress.filter.ProgressFilter;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

@MyBatisRepository
public interface UqsHandleViewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UQS_HANDLE_VIEW
     *
     * @mbggenerated
     */
    int countByExample(UqsHandleViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UQS_HANDLE_VIEW
     *
     * @mbggenerated
     */
    int deleteByExample(UqsHandleViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UQS_HANDLE_VIEW
     *
     * @mbggenerated
     */
    int insert(UqsHandleView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UQS_HANDLE_VIEW
     *
     * @mbggenerated
     */
    int insertSelective(UqsHandleView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UQS_HANDLE_VIEW
     *
     * @mbggenerated
     */
    List<UqsHandleView> selectByExample(UqsHandleViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UQS_HANDLE_VIEW
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UqsHandleView record, @Param("example") UqsHandleViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UQS_HANDLE_VIEW
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UqsHandleView record, @Param("example") UqsHandleViewExample example);
    
    
    public List<Map> reportUqsForLcc(ProgressFilter filter);
    
    public List<Map> reportProgressForLcc(ProgressFilter filter);
    
    public List<Map> reportCompletenessForLcc(ProgressFilter filter);
    
    public List<Map> listUqs0(ProgressFilter filter);
    
    public List<Map> listUqs1(ProgressFilter filter);
    
    public List<Map> listUqs2(ProgressFilter filter);

    public List<Map> listUqs3(ProgressFilter filter);
    
    public List<Map> listUqs4(ProgressFilter filter);
    
    public List<Map> listUqs5(ProgressFilter filter);
    
    public List<Map> listUqs6(ProgressFilter filter);
    
    public List<Map> listRisk(ProgressFilter filter);
    
    public List<Map> mapForArea(ProgressFilter filter);
    
    public List<Map> mapForLcc(ProgressFilter filter);
    
    public List<Map> mapForChina(ProgressFilter filter);
    
    public List<Map> exportForLcc(@Param("lccCode") String lccCode);
    
    public List<Map> uqs1Trend(ProgressFilter filter);
    
    public List<Map> uqs2Trend(ProgressFilter filter);
    
    public List<Map> uqs3Trend(ProgressFilter filter);
    
    public List<Map> uqs34Trend(ProgressFilter filter);
    
    public List<Map> uqs4Trend(ProgressFilter filter);
    
    public List<Map> uqs5Trend(ProgressFilter filter);
    
    public List<Map> uqs6Trend(ProgressFilter filter);
    
    public List<Map> riskTrend(ProgressFilter filter);
    
    public List<Map> ecgTrend(ProgressFilter filter);
    
    public List<Map> cchTrend(ProgressFilter filter);
    
    public List<Map> echTrend(ProgressFilter filter);
    
    public List<Map> sampleTrend(ProgressFilter filter);
    
    public List<Map> tubeTrend(ProgressFilter filter);
    
}