package com.bdcor.pip.web.data.dao;

import org.apache.ibatis.annotations.Param;
import com.bdcor.pip.core.persistence.MyBatisRepository;
import com.bdcor.pip.web.data.domain.UqsQuestion;
import com.bdcor.pip.web.data.domain.UqsQuestionExample;
import com.bdcor.pip.web.data.domain.UqsQuestionKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

@MyBatisRepository
public interface UqsQuestionMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PIP_UQS_QUESTION
	 * @mbggenerated
	 */
	int countByExample(UqsQuestionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PIP_UQS_QUESTION
	 * @mbggenerated
	 */
	int deleteByExample(UqsQuestionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PIP_UQS_QUESTION
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(UqsQuestionKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PIP_UQS_QUESTION
	 * @mbggenerated
	 */
	int insert(UqsQuestion record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PIP_UQS_QUESTION
	 * @mbggenerated
	 */
	int insertSelective(UqsQuestion record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PIP_UQS_QUESTION
	 * @mbggenerated
	 */
	List<UqsQuestion> selectByExample(UqsQuestionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PIP_UQS_QUESTION
	 * @mbggenerated
	 */
	UqsQuestion selectByPrimaryKey(UqsQuestionKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PIP_UQS_QUESTION
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") UqsQuestion record,
			@Param("example") UqsQuestionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PIP_UQS_QUESTION
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") UqsQuestion record,
			@Param("example") UqsQuestionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PIP_UQS_QUESTION
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(UqsQuestion record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PIP_UQS_QUESTION
	 * @mbggenerated
	 */
	int updateByPrimaryKey(UqsQuestion record);
}