package com.bdcor.pip.web.data.dao;

import com.bdcor.pip.core.persistence.MyBatisRepository;
import com.bdcor.pip.web.data.domain.UqsOption;
import com.bdcor.pip.web.data.domain.UqsOptionExample;
import com.bdcor.pip.web.data.domain.UqsOptionKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

@MyBatisRepository
public interface UqsOptionMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PIP_UQS_OPTION
	 * @mbggenerated
	 */
	int countByExample(UqsOptionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PIP_UQS_OPTION
	 * @mbggenerated
	 */
	int deleteByExample(UqsOptionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PIP_UQS_OPTION
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(UqsOptionKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PIP_UQS_OPTION
	 * @mbggenerated
	 */
	int insert(UqsOption record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PIP_UQS_OPTION
	 * @mbggenerated
	 */
	int insertSelective(UqsOption record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PIP_UQS_OPTION
	 * @mbggenerated
	 */
	List<UqsOption> selectByExample(UqsOptionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PIP_UQS_OPTION
	 * @mbggenerated
	 */
	UqsOption selectByPrimaryKey(UqsOptionKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PIP_UQS_OPTION
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") UqsOption record,
			@Param("example") UqsOptionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PIP_UQS_OPTION
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") UqsOption record,
			@Param("example") UqsOptionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PIP_UQS_OPTION
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(UqsOption record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PIP_UQS_OPTION
	 * @mbggenerated
	 */
	int updateByPrimaryKey(UqsOption record);
}