package com.bdcor.pip.web.material.supp.domain;

import java.math.BigDecimal;
import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.format.annotation.NumberFormat;
import org.springframework.format.annotation.NumberFormat.Style;

import com.bdcor.pip.client.tools.DateUtils;

public class MasterImportDetail {
	private String type;// 1新增 2修改
	private String classCode;// 物质分类
	private String periodValidityStr ; //截止日期字符串
	private String lccCode;
	private String lccName;
	private Date orderDate;
	
	public String getLccCode()
	{
		return lccCode;
	}

	public void setLccCode(String lccCode)
	{
		this.lccCode = lccCode;
	}

	public String getLccName()
	{
		return lccName;
	}

	public void setLccName(String lccName)
	{
		this.lccName = lccName;
	}

	public Date getOrderDate()
	{
		return orderDate;
	}

	public void setOrderDate(Date orderDate)
	{
		this.orderDate = orderDate;
	}

	public String getPeriodValidityStr() {
		return DateUtils.fromatDateTime("yyyy-MM-dd", getPeriodValidity());
	}
	

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PIP_MMS_IMPORT_DETAIL.ID
	 * 
	 * @mbggenerated Tue Sep 09 10:13:05 CST 2014
	 */
	private Long id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PIP_MMS_IMPORT_DETAIL.PROJECT_ID
	 * 
	 * @mbggenerated Tue Sep 09 10:13:05 CST 2014
	 */
	private String projectId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PIP_MMS_IMPORT_DETAIL.IMORDER_NO
	 * 
	 * @mbggenerated Tue Sep 09 10:13:05 CST 2014
	 */
	private String imorderNo;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PIP_MMS_IMPORT_DETAIL.MATERLINFO_CODE
	 * 
	 * @mbggenerated Tue Sep 09 10:13:05 CST 2014
	 */
	private String materlinfoCode;

	private String materlName;
	private String materlCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PIP_MMS_IMPORT_DETAIL.MATERL_BATCH
	 * 
	 * @mbggenerated Tue Sep 09 10:13:05 CST 2014
	 */
	private String materlBatch;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PIP_MMS_IMPORT_DETAIL.MATERL_PRICE
	 * 
	 * @mbggenerated Tue Sep 09 10:13:05 CST 2014
	 */
	@NumberFormat(style = Style.CURRENCY)
	private BigDecimal materlPrice;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PIP_MMS_IMPORT_DETAIL.WHOLESALE_PRICE
	 * 
	 * @mbggenerated Tue Sep 09 10:13:05 CST 2014
	 */
	@NumberFormat(style = Style.CURRENCY)
	private BigDecimal wholesalePrice;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PIP_MMS_IMPORT_DETAIL.IMPORT_UNIT
	 * 
	 * @mbggenerated Tue Sep 09 10:13:05 CST 2014
	 */
	private String importUnit;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PIP_MMS_IMPORT_DETAIL.IMPORT_AMOUNT
	 * 
	 * @mbggenerated Tue Sep 09 10:13:05 CST 2014
	 */
	@NumberFormat(style = Style.CURRENCY)
	private Long importAmount;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PIP_MMS_IMPORT_DETAIL.STORE_UNIT
	 * 
	 * @mbggenerated Tue Sep 09 10:13:05 CST 2014
	 */
	private String storeUnit;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PIP_MMS_IMPORT_DETAIL.COEFFICIENT_CHANGE
	 * 
	 * @mbggenerated Tue Sep 09 10:13:05 CST 2014
	 */
	@NumberFormat(style = Style.CURRENCY)
	private BigDecimal coefficientChange;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PIP_MMS_IMPORT_DETAIL.PERIOD_VALIDITY
	 * 
	 * @mbggenerated Tue Sep 09 10:13:05 CST 2014
	 */
	@DateTimeFormat(pattern = "yyyy-MM-dd")
	private Date periodValidity;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PIP_MMS_IMPORT_DETAIL.SUPPLIER_CODE
	 * 
	 * @mbggenerated Tue Sep 09 10:13:05 CST 2014
	 */
	private String supplierCode;
	private String supplierName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PIP_MMS_IMPORT_DETAIL.CREATE_DATE
	 * 
	 * @mbggenerated Tue Sep 09 10:13:05 CST 2014
	 */
	@DateTimeFormat(pattern = "yyyy-MM-dd")
	private Date createDate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PIP_MMS_IMPORT_DETAIL.CREATE_BY
	 * 
	 * @mbggenerated Tue Sep 09 10:13:05 CST 2014
	 */
	private String createBy;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PIP_MMS_IMPORT_DETAIL.ASSETS_STATUS
	 * 
	 * @mbggenerated Tue Sep 09 10:13:05 CST 2014
	 */
	private Short assetsStatus;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PIP_MMS_IMPORT_DETAIL.IS_MEASURE
	 * 
	 * @mbggenerated Tue Sep 09 10:13:05 CST 2014
	 */
	private Short isMeasure;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PIP_MMS_IMPORT_DETAIL.NEXT_MEASURE_DATE
	 * 
	 * @mbggenerated Tue Sep 09 10:13:05 CST 2014
	 */
	@DateTimeFormat(pattern = "yyyy-MM-dd")
	private Date nextMeasureDate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PIP_MMS_IMPORT_DETAIL.MEASURE_PERIOD
	 * 
	 * @mbggenerated Tue Sep 09 10:13:05 CST 2014
	 */
	@NumberFormat(style = Style.CURRENCY)
	private Long measurePeriod;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PIP_MMS_IMPORT_DETAIL.ARCHIVES_NO
	 * 
	 * @mbggenerated Tue Sep 09 10:13:05 CST 2014
	 */
	private String archivesNo;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PIP_MMS_IMPORT_DETAIL.ID
	 * 
	 * @return the value of PIP_MMS_IMPORT_DETAIL.ID
	 * 
	 * @mbggenerated Tue Sep 09 10:13:05 CST 2014
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PIP_MMS_IMPORT_DETAIL.ID
	 * 
	 * @param id
	 *            the value for PIP_MMS_IMPORT_DETAIL.ID
	 * 
	 * @mbggenerated Tue Sep 09 10:13:05 CST 2014
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PIP_MMS_IMPORT_DETAIL.PROJECT_ID
	 * 
	 * @return the value of PIP_MMS_IMPORT_DETAIL.PROJECT_ID
	 * 
	 * @mbggenerated Tue Sep 09 10:13:05 CST 2014
	 */
	public String getProjectId() {
		return projectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PIP_MMS_IMPORT_DETAIL.PROJECT_ID
	 * 
	 * @param projectId
	 *            the value for PIP_MMS_IMPORT_DETAIL.PROJECT_ID
	 * 
	 * @mbggenerated Tue Sep 09 10:13:05 CST 2014
	 */
	public void setProjectId(String projectId) {
		this.projectId = projectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PIP_MMS_IMPORT_DETAIL.IMORDER_NO
	 * 
	 * @return the value of PIP_MMS_IMPORT_DETAIL.IMORDER_NO
	 * 
	 * @mbggenerated Tue Sep 09 10:13:05 CST 2014
	 */
	public String getImorderNo() {
		return imorderNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PIP_MMS_IMPORT_DETAIL.IMORDER_NO
	 * 
	 * @param imorderNo
	 *            the value for PIP_MMS_IMPORT_DETAIL.IMORDER_NO
	 * 
	 * @mbggenerated Tue Sep 09 10:13:05 CST 2014
	 */
	public void setImorderNo(String imorderNo) {
		this.imorderNo = imorderNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PIP_MMS_IMPORT_DETAIL.MATERLINFO_CODE
	 * 
	 * @return the value of PIP_MMS_IMPORT_DETAIL.MATERLINFO_CODE
	 * 
	 * @mbggenerated Tue Sep 09 10:13:05 CST 2014
	 */
	public String getMaterlinfoCode() {
		return materlinfoCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PIP_MMS_IMPORT_DETAIL.MATERLINFO_CODE
	 * 
	 * @param materlinfoCode
	 *            the value for PIP_MMS_IMPORT_DETAIL.MATERLINFO_CODE
	 * 
	 * @mbggenerated Tue Sep 09 10:13:05 CST 2014
	 */
	public void setMaterlinfoCode(String materlinfoCode) {
		this.materlinfoCode = materlinfoCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PIP_MMS_IMPORT_DETAIL.MATERL_BATCH
	 * 
	 * @return the value of PIP_MMS_IMPORT_DETAIL.MATERL_BATCH
	 * 
	 * @mbggenerated Tue Sep 09 10:13:05 CST 2014
	 */
	public String getMaterlBatch() {
		return materlBatch;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PIP_MMS_IMPORT_DETAIL.MATERL_BATCH
	 * 
	 * @param materlBatch
	 *            the value for PIP_MMS_IMPORT_DETAIL.MATERL_BATCH
	 * 
	 * @mbggenerated Tue Sep 09 10:13:05 CST 2014
	 */
	public void setMaterlBatch(String materlBatch) {
		this.materlBatch = materlBatch;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PIP_MMS_IMPORT_DETAIL.MATERL_PRICE
	 * 
	 * @return the value of PIP_MMS_IMPORT_DETAIL.MATERL_PRICE
	 * 
	 * @mbggenerated Tue Sep 09 10:13:05 CST 2014
	 */
	public BigDecimal getMaterlPrice() {
		return materlPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PIP_MMS_IMPORT_DETAIL.MATERL_PRICE
	 * 
	 * @param materlPrice
	 *            the value for PIP_MMS_IMPORT_DETAIL.MATERL_PRICE
	 * 
	 * @mbggenerated Tue Sep 09 10:13:05 CST 2014
	 */
	public void setMaterlPrice(BigDecimal materlPrice) {
		this.materlPrice = materlPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PIP_MMS_IMPORT_DETAIL.WHOLESALE_PRICE
	 * 
	 * @return the value of PIP_MMS_IMPORT_DETAIL.WHOLESALE_PRICE
	 * 
	 * @mbggenerated Tue Sep 09 10:13:05 CST 2014
	 */
	public BigDecimal getWholesalePrice() {
		return wholesalePrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PIP_MMS_IMPORT_DETAIL.WHOLESALE_PRICE
	 * 
	 * @param wholesalePrice
	 *            the value for PIP_MMS_IMPORT_DETAIL.WHOLESALE_PRICE
	 * 
	 * @mbggenerated Tue Sep 09 10:13:05 CST 2014
	 */
	public void setWholesalePrice(BigDecimal wholesalePrice) {
		this.wholesalePrice = wholesalePrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PIP_MMS_IMPORT_DETAIL.IMPORT_UNIT
	 * 
	 * @return the value of PIP_MMS_IMPORT_DETAIL.IMPORT_UNIT
	 * 
	 * @mbggenerated Tue Sep 09 10:13:05 CST 2014
	 */
	public String getImportUnit() {
		return importUnit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PIP_MMS_IMPORT_DETAIL.IMPORT_UNIT
	 * 
	 * @param importUnit
	 *            the value for PIP_MMS_IMPORT_DETAIL.IMPORT_UNIT
	 * 
	 * @mbggenerated Tue Sep 09 10:13:05 CST 2014
	 */
	public void setImportUnit(String importUnit) {
		this.importUnit = importUnit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PIP_MMS_IMPORT_DETAIL.IMPORT_AMOUNT
	 * 
	 * @return the value of PIP_MMS_IMPORT_DETAIL.IMPORT_AMOUNT
	 * 
	 * @mbggenerated Tue Sep 09 10:13:05 CST 2014
	 */
	public Long getImportAmount() {
		return importAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PIP_MMS_IMPORT_DETAIL.IMPORT_AMOUNT
	 * 
	 * @param importAmount
	 *            the value for PIP_MMS_IMPORT_DETAIL.IMPORT_AMOUNT
	 * 
	 * @mbggenerated Tue Sep 09 10:13:05 CST 2014
	 */
	public void setImportAmount(Long importAmount) {
		this.importAmount = importAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PIP_MMS_IMPORT_DETAIL.STORE_UNIT
	 * 
	 * @return the value of PIP_MMS_IMPORT_DETAIL.STORE_UNIT
	 * 
	 * @mbggenerated Tue Sep 09 10:13:05 CST 2014
	 */
	public String getStoreUnit() {
		return storeUnit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PIP_MMS_IMPORT_DETAIL.STORE_UNIT
	 * 
	 * @param storeUnit
	 *            the value for PIP_MMS_IMPORT_DETAIL.STORE_UNIT
	 * 
	 * @mbggenerated Tue Sep 09 10:13:05 CST 2014
	 */
	public void setStoreUnit(String storeUnit) {
		this.storeUnit = storeUnit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PIP_MMS_IMPORT_DETAIL.COEFFICIENT_CHANGE
	 * 
	 * @return the value of PIP_MMS_IMPORT_DETAIL.COEFFICIENT_CHANGE
	 * 
	 * @mbggenerated Tue Sep 09 10:13:05 CST 2014
	 */
	public BigDecimal getCoefficientChange() {
		return coefficientChange;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PIP_MMS_IMPORT_DETAIL.COEFFICIENT_CHANGE
	 * 
	 * @param coefficientChange
	 *            the value for PIP_MMS_IMPORT_DETAIL.COEFFICIENT_CHANGE
	 * 
	 * @mbggenerated Tue Sep 09 10:13:05 CST 2014
	 */
	public void setCoefficientChange(BigDecimal coefficientChange) {
		this.coefficientChange = coefficientChange;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PIP_MMS_IMPORT_DETAIL.PERIOD_VALIDITY
	 * 
	 * @return the value of PIP_MMS_IMPORT_DETAIL.PERIOD_VALIDITY
	 * 
	 * @mbggenerated Tue Sep 09 10:13:05 CST 2014
	 */
	public Date getPeriodValidity() {
		return periodValidity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PIP_MMS_IMPORT_DETAIL.PERIOD_VALIDITY
	 * 
	 * @param periodValidity
	 *            the value for PIP_MMS_IMPORT_DETAIL.PERIOD_VALIDITY
	 * 
	 * @mbggenerated Tue Sep 09 10:13:05 CST 2014
	 */
	public void setPeriodValidity(Date periodValidity) {
		this.periodValidity = periodValidity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PIP_MMS_IMPORT_DETAIL.SUPPLIER_CODE
	 * 
	 * @return the value of PIP_MMS_IMPORT_DETAIL.SUPPLIER_CODE
	 * 
	 * @mbggenerated Tue Sep 09 10:13:05 CST 2014
	 */
	public String getSupplierCode() {
		return supplierCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PIP_MMS_IMPORT_DETAIL.SUPPLIER_CODE
	 * 
	 * @param supplierCode
	 *            the value for PIP_MMS_IMPORT_DETAIL.SUPPLIER_CODE
	 * 
	 * @mbggenerated Tue Sep 09 10:13:05 CST 2014
	 */
	public void setSupplierCode(String supplierCode) {
		this.supplierCode = supplierCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PIP_MMS_IMPORT_DETAIL.CREATE_DATE
	 * 
	 * @return the value of PIP_MMS_IMPORT_DETAIL.CREATE_DATE
	 * 
	 * @mbggenerated Tue Sep 09 10:13:05 CST 2014
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PIP_MMS_IMPORT_DETAIL.CREATE_DATE
	 * 
	 * @param createDate
	 *            the value for PIP_MMS_IMPORT_DETAIL.CREATE_DATE
	 * 
	 * @mbggenerated Tue Sep 09 10:13:05 CST 2014
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PIP_MMS_IMPORT_DETAIL.CREATE_BY
	 * 
	 * @return the value of PIP_MMS_IMPORT_DETAIL.CREATE_BY
	 * 
	 * @mbggenerated Tue Sep 09 10:13:05 CST 2014
	 */
	public String getCreateBy() {
		return createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PIP_MMS_IMPORT_DETAIL.CREATE_BY
	 * 
	 * @param createBy
	 *            the value for PIP_MMS_IMPORT_DETAIL.CREATE_BY
	 * 
	 * @mbggenerated Tue Sep 09 10:13:05 CST 2014
	 */
	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PIP_MMS_IMPORT_DETAIL.ASSETS_STATUS
	 * 
	 * @return the value of PIP_MMS_IMPORT_DETAIL.ASSETS_STATUS
	 * 
	 * @mbggenerated Tue Sep 09 10:13:05 CST 2014
	 */
	public Short getAssetsStatus() {
		return assetsStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PIP_MMS_IMPORT_DETAIL.ASSETS_STATUS
	 * 
	 * @param assetsStatus
	 *            the value for PIP_MMS_IMPORT_DETAIL.ASSETS_STATUS
	 * 
	 * @mbggenerated Tue Sep 09 10:13:05 CST 2014
	 */
	public void setAssetsStatus(Short assetsStatus) {
		this.assetsStatus = assetsStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PIP_MMS_IMPORT_DETAIL.IS_MEASURE
	 * 
	 * @return the value of PIP_MMS_IMPORT_DETAIL.IS_MEASURE
	 * 
	 * @mbggenerated Tue Sep 09 10:13:05 CST 2014
	 */
	public Short getIsMeasure() {
		return isMeasure;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PIP_MMS_IMPORT_DETAIL.IS_MEASURE
	 * 
	 * @param isMeasure
	 *            the value for PIP_MMS_IMPORT_DETAIL.IS_MEASURE
	 * 
	 * @mbggenerated Tue Sep 09 10:13:05 CST 2014
	 */
	public void setIsMeasure(Short isMeasure) {
		this.isMeasure = isMeasure;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PIP_MMS_IMPORT_DETAIL.NEXT_MEASURE_DATE
	 * 
	 * @return the value of PIP_MMS_IMPORT_DETAIL.NEXT_MEASURE_DATE
	 * 
	 * @mbggenerated Tue Sep 09 10:13:05 CST 2014
	 */
	public Date getNextMeasureDate() {
		return nextMeasureDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PIP_MMS_IMPORT_DETAIL.NEXT_MEASURE_DATE
	 * 
	 * @param nextMeasureDate
	 *            the value for PIP_MMS_IMPORT_DETAIL.NEXT_MEASURE_DATE
	 * 
	 * @mbggenerated Tue Sep 09 10:13:05 CST 2014
	 */
	public void setNextMeasureDate(Date nextMeasureDate) {
		this.nextMeasureDate = nextMeasureDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PIP_MMS_IMPORT_DETAIL.MEASURE_PERIOD
	 * 
	 * @return the value of PIP_MMS_IMPORT_DETAIL.MEASURE_PERIOD
	 * 
	 * @mbggenerated Tue Sep 09 10:13:05 CST 2014
	 */
	public Long getMeasurePeriod() {
		return measurePeriod;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PIP_MMS_IMPORT_DETAIL.MEASURE_PERIOD
	 * 
	 * @param measurePeriod
	 *            the value for PIP_MMS_IMPORT_DETAIL.MEASURE_PERIOD
	 * 
	 * @mbggenerated Tue Sep 09 10:13:05 CST 2014
	 */
	public void setMeasurePeriod(Long measurePeriod) {
		this.measurePeriod = measurePeriod;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PIP_MMS_IMPORT_DETAIL.ARCHIVES_NO
	 * 
	 * @return the value of PIP_MMS_IMPORT_DETAIL.ARCHIVES_NO
	 * 
	 * @mbggenerated Tue Sep 09 10:13:05 CST 2014
	 */
	public String getArchivesNo() {
		return archivesNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PIP_MMS_IMPORT_DETAIL.ARCHIVES_NO
	 * 
	 * @param archivesNo
	 *            the value for PIP_MMS_IMPORT_DETAIL.ARCHIVES_NO
	 * 
	 * @mbggenerated Tue Sep 09 10:13:05 CST 2014
	 */
	public void setArchivesNo(String archivesNo) {
		this.archivesNo = archivesNo;
	}

	public String getMaterlName() {
		return materlName;
	}

	public void setMaterlName(String materlName) {
		this.materlName = materlName;
	}

	public String getSupplierName() {
		return supplierName;
	}

	public void setSupplierName(String supplierName) {
		this.supplierName = supplierName;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getMaterlCode() {
		return materlCode;
	}

	public void setMaterlCode(String materlCode) {
		this.materlCode = materlCode;
	}

	public String getClassCode() {
		return classCode;
	}

	public void setClassCode(String classCode) {
		this.classCode = classCode;
	}

}