package com.bdcor.pip.web.data.domain;

import java.util.Date;

public class PipCommLccMsgKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIP_COMM_LCC_MSG.CREATE_DATE
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIP_COMM_LCC_MSG.FROM_LCC_CODE
     *
     * @mbggenerated
     */
    private String fromLccCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIP_COMM_LCC_MSG.PROJECT_ID
     *
     * @mbggenerated
     */
    private String projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIP_COMM_LCC_MSG.TO_LCC_CODE
     *
     * @mbggenerated
     */
    private String toLccCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIP_COMM_LCC_MSG.CREATE_DATE
     *
     * @return the value of PIP_COMM_LCC_MSG.CREATE_DATE
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIP_COMM_LCC_MSG.CREATE_DATE
     *
     * @param createDate the value for PIP_COMM_LCC_MSG.CREATE_DATE
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIP_COMM_LCC_MSG.FROM_LCC_CODE
     *
     * @return the value of PIP_COMM_LCC_MSG.FROM_LCC_CODE
     *
     * @mbggenerated
     */
    public String getFromLccCode() {
        return fromLccCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIP_COMM_LCC_MSG.FROM_LCC_CODE
     *
     * @param fromLccCode the value for PIP_COMM_LCC_MSG.FROM_LCC_CODE
     *
     * @mbggenerated
     */
    public void setFromLccCode(String fromLccCode) {
        this.fromLccCode = fromLccCode == null ? null : fromLccCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIP_COMM_LCC_MSG.PROJECT_ID
     *
     * @return the value of PIP_COMM_LCC_MSG.PROJECT_ID
     *
     * @mbggenerated
     */
    public String getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIP_COMM_LCC_MSG.PROJECT_ID
     *
     * @param projectId the value for PIP_COMM_LCC_MSG.PROJECT_ID
     *
     * @mbggenerated
     */
    public void setProjectId(String projectId) {
        this.projectId = projectId == null ? null : projectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIP_COMM_LCC_MSG.TO_LCC_CODE
     *
     * @return the value of PIP_COMM_LCC_MSG.TO_LCC_CODE
     *
     * @mbggenerated
     */
    public String getToLccCode() {
        return toLccCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIP_COMM_LCC_MSG.TO_LCC_CODE
     *
     * @param toLccCode the value for PIP_COMM_LCC_MSG.TO_LCC_CODE
     *
     * @mbggenerated
     */
    public void setToLccCode(String toLccCode) {
        this.toLccCode = toLccCode == null ? null : toLccCode.trim();
    }
}