package com.bdcor.pip.web.data.domain;

import java.util.Date;

public class PipCommPatientDropLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIP_COMM_PATIENT_DROP_LOG.PATIENT_ID
     *
     * @mbggenerated
     */
    private String patientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIP_COMM_PATIENT_DROP_LOG.TARGET_ID
     *
     * @mbggenerated
     */
    private String targetId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIP_COMM_PATIENT_DROP_LOG.SOURCE_ID
     *
     * @mbggenerated
     */
    private String sourceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIP_COMM_PATIENT_DROP_LOG.TYPE
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIP_COMM_PATIENT_DROP_LOG.ID_NUMBER
     *
     * @mbggenerated
     */
    private String idNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIP_COMM_PATIENT_DROP_LOG.ITEMS
     *
     * @mbggenerated
     */
    private String items;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIP_COMM_PATIENT_DROP_LOG.CREATE_BY
     *
     * @mbggenerated
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIP_COMM_PATIENT_DROP_LOG.CREATE_DATE
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIP_COMM_PATIENT_DROP_LOG.PATIENT_ID
     *
     * @return the value of PIP_COMM_PATIENT_DROP_LOG.PATIENT_ID
     *
     * @mbggenerated
     */
    public String getPatientId() {
        return patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIP_COMM_PATIENT_DROP_LOG.PATIENT_ID
     *
     * @param patientId the value for PIP_COMM_PATIENT_DROP_LOG.PATIENT_ID
     *
     * @mbggenerated
     */
    public void setPatientId(String patientId) {
        this.patientId = patientId == null ? null : patientId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIP_COMM_PATIENT_DROP_LOG.TARGET_ID
     *
     * @return the value of PIP_COMM_PATIENT_DROP_LOG.TARGET_ID
     *
     * @mbggenerated
     */
    public String getTargetId() {
        return targetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIP_COMM_PATIENT_DROP_LOG.TARGET_ID
     *
     * @param targetId the value for PIP_COMM_PATIENT_DROP_LOG.TARGET_ID
     *
     * @mbggenerated
     */
    public void setTargetId(String targetId) {
        this.targetId = targetId == null ? null : targetId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIP_COMM_PATIENT_DROP_LOG.SOURCE_ID
     *
     * @return the value of PIP_COMM_PATIENT_DROP_LOG.SOURCE_ID
     *
     * @mbggenerated
     */
    public String getSourceId() {
        return sourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIP_COMM_PATIENT_DROP_LOG.SOURCE_ID
     *
     * @param sourceId the value for PIP_COMM_PATIENT_DROP_LOG.SOURCE_ID
     *
     * @mbggenerated
     */
    public void setSourceId(String sourceId) {
        this.sourceId = sourceId == null ? null : sourceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIP_COMM_PATIENT_DROP_LOG.TYPE
     *
     * @return the value of PIP_COMM_PATIENT_DROP_LOG.TYPE
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIP_COMM_PATIENT_DROP_LOG.TYPE
     *
     * @param type the value for PIP_COMM_PATIENT_DROP_LOG.TYPE
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIP_COMM_PATIENT_DROP_LOG.ID_NUMBER
     *
     * @return the value of PIP_COMM_PATIENT_DROP_LOG.ID_NUMBER
     *
     * @mbggenerated
     */
    public String getIdNumber() {
        return idNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIP_COMM_PATIENT_DROP_LOG.ID_NUMBER
     *
     * @param idNumber the value for PIP_COMM_PATIENT_DROP_LOG.ID_NUMBER
     *
     * @mbggenerated
     */
    public void setIdNumber(String idNumber) {
        this.idNumber = idNumber == null ? null : idNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIP_COMM_PATIENT_DROP_LOG.ITEMS
     *
     * @return the value of PIP_COMM_PATIENT_DROP_LOG.ITEMS
     *
     * @mbggenerated
     */
    public String getItems() {
        return items;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIP_COMM_PATIENT_DROP_LOG.ITEMS
     *
     * @param items the value for PIP_COMM_PATIENT_DROP_LOG.ITEMS
     *
     * @mbggenerated
     */
    public void setItems(String items) {
        this.items = items == null ? null : items.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIP_COMM_PATIENT_DROP_LOG.CREATE_BY
     *
     * @return the value of PIP_COMM_PATIENT_DROP_LOG.CREATE_BY
     *
     * @mbggenerated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIP_COMM_PATIENT_DROP_LOG.CREATE_BY
     *
     * @param createBy the value for PIP_COMM_PATIENT_DROP_LOG.CREATE_BY
     *
     * @mbggenerated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIP_COMM_PATIENT_DROP_LOG.CREATE_DATE
     *
     * @return the value of PIP_COMM_PATIENT_DROP_LOG.CREATE_DATE
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIP_COMM_PATIENT_DROP_LOG.CREATE_DATE
     *
     * @param createDate the value for PIP_COMM_PATIENT_DROP_LOG.CREATE_DATE
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}