package com.bdcor.pip.web.data.domain;

public class PipReportVar {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIP_REPORT_VAR.VAR_ID
     *
     * @mbggenerated
     */
    private String varId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIP_REPORT_VAR.VAR_NAME
     *
     * @mbggenerated
     */
    private String varName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIP_REPORT_VAR.AGG_METHOD
     *
     * @mbggenerated
     */
    private String aggMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIP_REPORT_VAR.REMARK
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIP_REPORT_VAR.VAR_TYPE
     *
     * @mbggenerated
     */
    private String varType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIP_REPORT_VAR.CONDITIONS
     *
     * @mbggenerated
     */
    private String conditions;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIP_REPORT_VAR.RELATION
     *
     * @mbggenerated
     */
    private String relation;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIP_REPORT_VAR.VAR_ID
     *
     * @return the value of PIP_REPORT_VAR.VAR_ID
     *
     * @mbggenerated
     */
    public String getVarId() {
        return varId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIP_REPORT_VAR.VAR_ID
     *
     * @param varId the value for PIP_REPORT_VAR.VAR_ID
     *
     * @mbggenerated
     */
    public void setVarId(String varId) {
        this.varId = varId == null ? null : varId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIP_REPORT_VAR.VAR_NAME
     *
     * @return the value of PIP_REPORT_VAR.VAR_NAME
     *
     * @mbggenerated
     */
    public String getVarName() {
        return varName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIP_REPORT_VAR.VAR_NAME
     *
     * @param varName the value for PIP_REPORT_VAR.VAR_NAME
     *
     * @mbggenerated
     */
    public void setVarName(String varName) {
        this.varName = varName == null ? null : varName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIP_REPORT_VAR.AGG_METHOD
     *
     * @return the value of PIP_REPORT_VAR.AGG_METHOD
     *
     * @mbggenerated
     */
    public String getAggMethod() {
        return aggMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIP_REPORT_VAR.AGG_METHOD
     *
     * @param aggMethod the value for PIP_REPORT_VAR.AGG_METHOD
     *
     * @mbggenerated
     */
    public void setAggMethod(String aggMethod) {
        this.aggMethod = aggMethod == null ? null : aggMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIP_REPORT_VAR.REMARK
     *
     * @return the value of PIP_REPORT_VAR.REMARK
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIP_REPORT_VAR.REMARK
     *
     * @param remark the value for PIP_REPORT_VAR.REMARK
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIP_REPORT_VAR.VAR_TYPE
     *
     * @return the value of PIP_REPORT_VAR.VAR_TYPE
     *
     * @mbggenerated
     */
    public String getVarType() {
        return varType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIP_REPORT_VAR.VAR_TYPE
     *
     * @param varType the value for PIP_REPORT_VAR.VAR_TYPE
     *
     * @mbggenerated
     */
    public void setVarType(String varType) {
        this.varType = varType == null ? null : varType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIP_REPORT_VAR.CONDITIONS
     *
     * @return the value of PIP_REPORT_VAR.CONDITIONS
     *
     * @mbggenerated
     */
    public String getConditions() {
        return conditions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIP_REPORT_VAR.CONDITIONS
     *
     * @param conditions the value for PIP_REPORT_VAR.CONDITIONS
     *
     * @mbggenerated
     */
    public void setConditions(String conditions) {
        this.conditions = conditions == null ? null : conditions.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIP_REPORT_VAR.RELATION
     *
     * @return the value of PIP_REPORT_VAR.RELATION
     *
     * @mbggenerated
     */
    public String getRelation() {
        return relation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIP_REPORT_VAR.RELATION
     *
     * @param relation the value for PIP_REPORT_VAR.RELATION
     *
     * @mbggenerated
     */
    public void setRelation(String relation) {
        this.relation = relation == null ? null : relation.trim();
    }
}