package com.bdcor.pip.web.data.domain;

import java.util.Date;

public class PipSysNews {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PIP_SYS_NEWS.ID
	 * @mbggenerated
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PIP_SYS_NEWS.TITLE
	 * @mbggenerated
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PIP_SYS_NEWS.NAME
	 * @mbggenerated
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PIP_SYS_NEWS.AUTHOR
	 * @mbggenerated
	 */
	private String author;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PIP_SYS_NEWS.FILE_NAME
	 * @mbggenerated
	 */
	private String fileName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PIP_SYS_NEWS.CREATE_DATE
	 * @mbggenerated
	 */
	private Date createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PIP_SYS_NEWS.REMARK
	 * @mbggenerated
	 */
	private String remark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PIP_SYS_NEWS.TYPE
	 * @mbggenerated
	 */
	private String type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PIP_SYS_NEWS.CHANNEL
	 * @mbggenerated
	 */

	private String channel;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PIP_SYS_NEWS.ID
	 * @return  the value of PIP_SYS_NEWS.ID
	 * @mbggenerated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PIP_SYS_NEWS.ID
	 * @param id  the value for PIP_SYS_NEWS.ID
	 * @mbggenerated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PIP_SYS_NEWS.TITLE
	 * @return  the value of PIP_SYS_NEWS.TITLE
	 * @mbggenerated
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PIP_SYS_NEWS.TITLE
	 * @param title  the value for PIP_SYS_NEWS.TITLE
	 * @mbggenerated
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PIP_SYS_NEWS.NAME
	 * @return  the value of PIP_SYS_NEWS.NAME
	 * @mbggenerated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PIP_SYS_NEWS.NAME
	 * @param name  the value for PIP_SYS_NEWS.NAME
	 * @mbggenerated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PIP_SYS_NEWS.AUTHOR
	 * @return  the value of PIP_SYS_NEWS.AUTHOR
	 * @mbggenerated
	 */
	public String getAuthor() {
		return author;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PIP_SYS_NEWS.AUTHOR
	 * @param author  the value for PIP_SYS_NEWS.AUTHOR
	 * @mbggenerated
	 */
	public void setAuthor(String author) {
		this.author = author == null ? null : author.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PIP_SYS_NEWS.FILE_NAME
	 * @return  the value of PIP_SYS_NEWS.FILE_NAME
	 * @mbggenerated
	 */
	public String getFileName() {
		return fileName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PIP_SYS_NEWS.FILE_NAME
	 * @param fileName  the value for PIP_SYS_NEWS.FILE_NAME
	 * @mbggenerated
	 */
	public void setFileName(String fileName) {
		this.fileName = fileName == null ? null : fileName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PIP_SYS_NEWS.CREATE_DATE
	 * @return  the value of PIP_SYS_NEWS.CREATE_DATE
	 * @mbggenerated
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PIP_SYS_NEWS.CREATE_DATE
	 * @param createDate  the value for PIP_SYS_NEWS.CREATE_DATE
	 * @mbggenerated
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PIP_SYS_NEWS.REMARK
	 * @return  the value of PIP_SYS_NEWS.REMARK
	 * @mbggenerated
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PIP_SYS_NEWS.REMARK
	 * @param remark  the value for PIP_SYS_NEWS.REMARK
	 * @mbggenerated
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PIP_SYS_NEWS.TYPE
	 * @return  the value of PIP_SYS_NEWS.TYPE
	 * @mbggenerated
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PIP_SYS_NEWS.TYPE
	 * @param type  the value for PIP_SYS_NEWS.TYPE
	 * @mbggenerated
	 */
	public void setType(String type) {
		this.type = type == null ? null : type.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PIP_SYS_NEWS.CHANNEL
	 * @return  the value of PIP_SYS_NEWS.CHANNEL
	 * @mbggenerated
	 */
	public String getChannel() {
		return channel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PIP_SYS_NEWS.CHANNEL
	 * @param channel  the value for PIP_SYS_NEWS.CHANNEL
	 * @mbggenerated
	 */
	public void setChannel(String channel) {
		this.channel = channel == null ? null : channel.trim();
	}

	private String newsContent;

	public String getNewsContent() {
		return newsContent;
	}

	public void setNewsContent(String newsContent) {
		this.newsContent = newsContent;
	}
}