package com.bdcor.pip.web.data.domain;

public class ReportFactoryView {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPORT_FACTORY_VIEW.PROJECT_ID
     *
     * @mbggenerated
     */
    private String projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPORT_FACTORY_VIEW.LCC_CODE
     *
     * @mbggenerated
     */
    private String lccCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPORT_FACTORY_VIEW.ITEM_DATE
     *
     * @mbggenerated
     */
    private String itemDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPORT_FACTORY_VIEW.VAR1
     *
     * @mbggenerated
     */
    private String var1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPORT_FACTORY_VIEW.VAR2
     *
     * @mbggenerated
     */
    private String var2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPORT_FACTORY_VIEW.VAR3
     *
     * @mbggenerated
     */
    private String var3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPORT_FACTORY_VIEW.VAR4
     *
     * @mbggenerated
     */
    private String var4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPORT_FACTORY_VIEW.VAR5
     *
     * @mbggenerated
     */
    private String var5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPORT_FACTORY_VIEW.VAR6
     *
     * @mbggenerated
     */
    private String var6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPORT_FACTORY_VIEW.VAR7
     *
     * @mbggenerated
     */
    private String var7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPORT_FACTORY_VIEW.VAR8
     *
     * @mbggenerated
     */
    private String var8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPORT_FACTORY_VIEW.VAR9
     *
     * @mbggenerated
     */
    private String var9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPORT_FACTORY_VIEW.VAR10
     *
     * @mbggenerated
     */
    private String var10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPORT_FACTORY_VIEW.VAR11
     *
     * @mbggenerated
     */
    private String var11;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPORT_FACTORY_VIEW.VAR12
     *
     * @mbggenerated
     */
    private String var12;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPORT_FACTORY_VIEW.VAR13
     *
     * @mbggenerated
     */
    private String var13;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPORT_FACTORY_VIEW.VAR14
     *
     * @mbggenerated
     */
    private String var14;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPORT_FACTORY_VIEW.VAR15
     *
     * @mbggenerated
     */
    private String var15;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPORT_FACTORY_VIEW.VAR16
     *
     * @mbggenerated
     */
    private String var16;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPORT_FACTORY_VIEW.VAR17
     *
     * @mbggenerated
     */
    private String var17;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPORT_FACTORY_VIEW.VAR18
     *
     * @mbggenerated
     */
    private String var18;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPORT_FACTORY_VIEW.VAR19
     *
     * @mbggenerated
     */
    private String var19;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPORT_FACTORY_VIEW.VAR20
     *
     * @mbggenerated
     */
    private String var20;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPORT_FACTORY_VIEW.NUM1
     *
     * @mbggenerated
     */
    private Short num1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPORT_FACTORY_VIEW.NUM2
     *
     * @mbggenerated
     */
    private Short num2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPORT_FACTORY_VIEW.NUM3
     *
     * @mbggenerated
     */
    private Short num3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPORT_FACTORY_VIEW.NUM4
     *
     * @mbggenerated
     */
    private Short num4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPORT_FACTORY_VIEW.NUM5
     *
     * @mbggenerated
     */
    private Short num5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPORT_FACTORY_VIEW.NUM6
     *
     * @mbggenerated
     */
    private Short num6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPORT_FACTORY_VIEW.NUM7
     *
     * @mbggenerated
     */
    private Short num7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPORT_FACTORY_VIEW.NUM8
     *
     * @mbggenerated
     */
    private Short num8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPORT_FACTORY_VIEW.NUM9
     *
     * @mbggenerated
     */
    private Short num9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPORT_FACTORY_VIEW.NUM10
     *
     * @mbggenerated
     */
    private Short num10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPORT_FACTORY_VIEW.NUM11
     *
     * @mbggenerated
     */
    private Short num11;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPORT_FACTORY_VIEW.NUM12
     *
     * @mbggenerated
     */
    private Short num12;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPORT_FACTORY_VIEW.NUM13
     *
     * @mbggenerated
     */
    private Short num13;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPORT_FACTORY_VIEW.NUM14
     *
     * @mbggenerated
     */
    private Short num14;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPORT_FACTORY_VIEW.NUM15
     *
     * @mbggenerated
     */
    private Short num15;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPORT_FACTORY_VIEW.NUM16
     *
     * @mbggenerated
     */
    private Short num16;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPORT_FACTORY_VIEW.NUM17
     *
     * @mbggenerated
     */
    private Short num17;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPORT_FACTORY_VIEW.NUM18
     *
     * @mbggenerated
     */
    private Short num18;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPORT_FACTORY_VIEW.NUM19
     *
     * @mbggenerated
     */
    private Short num19;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPORT_FACTORY_VIEW.NUM20
     *
     * @mbggenerated
     */
    private Short num20;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPORT_FACTORY_VIEW.PROJECT_ID
     *
     * @return the value of REPORT_FACTORY_VIEW.PROJECT_ID
     *
     * @mbggenerated
     */
    public String getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPORT_FACTORY_VIEW.PROJECT_ID
     *
     * @param projectId the value for REPORT_FACTORY_VIEW.PROJECT_ID
     *
     * @mbggenerated
     */
    public void setProjectId(String projectId) {
        this.projectId = projectId == null ? null : projectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPORT_FACTORY_VIEW.LCC_CODE
     *
     * @return the value of REPORT_FACTORY_VIEW.LCC_CODE
     *
     * @mbggenerated
     */
    public String getLccCode() {
        return lccCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPORT_FACTORY_VIEW.LCC_CODE
     *
     * @param lccCode the value for REPORT_FACTORY_VIEW.LCC_CODE
     *
     * @mbggenerated
     */
    public void setLccCode(String lccCode) {
        this.lccCode = lccCode == null ? null : lccCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPORT_FACTORY_VIEW.ITEM_DATE
     *
     * @return the value of REPORT_FACTORY_VIEW.ITEM_DATE
     *
     * @mbggenerated
     */
    public String getItemDate() {
        return itemDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPORT_FACTORY_VIEW.ITEM_DATE
     *
     * @param itemDate the value for REPORT_FACTORY_VIEW.ITEM_DATE
     *
     * @mbggenerated
     */
    public void setItemDate(String itemDate) {
        this.itemDate = itemDate == null ? null : itemDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPORT_FACTORY_VIEW.VAR1
     *
     * @return the value of REPORT_FACTORY_VIEW.VAR1
     *
     * @mbggenerated
     */
    public String getVar1() {
        return var1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPORT_FACTORY_VIEW.VAR1
     *
     * @param var1 the value for REPORT_FACTORY_VIEW.VAR1
     *
     * @mbggenerated
     */
    public void setVar1(String var1) {
        this.var1 = var1 == null ? null : var1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPORT_FACTORY_VIEW.VAR2
     *
     * @return the value of REPORT_FACTORY_VIEW.VAR2
     *
     * @mbggenerated
     */
    public String getVar2() {
        return var2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPORT_FACTORY_VIEW.VAR2
     *
     * @param var2 the value for REPORT_FACTORY_VIEW.VAR2
     *
     * @mbggenerated
     */
    public void setVar2(String var2) {
        this.var2 = var2 == null ? null : var2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPORT_FACTORY_VIEW.VAR3
     *
     * @return the value of REPORT_FACTORY_VIEW.VAR3
     *
     * @mbggenerated
     */
    public String getVar3() {
        return var3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPORT_FACTORY_VIEW.VAR3
     *
     * @param var3 the value for REPORT_FACTORY_VIEW.VAR3
     *
     * @mbggenerated
     */
    public void setVar3(String var3) {
        this.var3 = var3 == null ? null : var3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPORT_FACTORY_VIEW.VAR4
     *
     * @return the value of REPORT_FACTORY_VIEW.VAR4
     *
     * @mbggenerated
     */
    public String getVar4() {
        return var4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPORT_FACTORY_VIEW.VAR4
     *
     * @param var4 the value for REPORT_FACTORY_VIEW.VAR4
     *
     * @mbggenerated
     */
    public void setVar4(String var4) {
        this.var4 = var4 == null ? null : var4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPORT_FACTORY_VIEW.VAR5
     *
     * @return the value of REPORT_FACTORY_VIEW.VAR5
     *
     * @mbggenerated
     */
    public String getVar5() {
        return var5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPORT_FACTORY_VIEW.VAR5
     *
     * @param var5 the value for REPORT_FACTORY_VIEW.VAR5
     *
     * @mbggenerated
     */
    public void setVar5(String var5) {
        this.var5 = var5 == null ? null : var5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPORT_FACTORY_VIEW.VAR6
     *
     * @return the value of REPORT_FACTORY_VIEW.VAR6
     *
     * @mbggenerated
     */
    public String getVar6() {
        return var6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPORT_FACTORY_VIEW.VAR6
     *
     * @param var6 the value for REPORT_FACTORY_VIEW.VAR6
     *
     * @mbggenerated
     */
    public void setVar6(String var6) {
        this.var6 = var6 == null ? null : var6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPORT_FACTORY_VIEW.VAR7
     *
     * @return the value of REPORT_FACTORY_VIEW.VAR7
     *
     * @mbggenerated
     */
    public String getVar7() {
        return var7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPORT_FACTORY_VIEW.VAR7
     *
     * @param var7 the value for REPORT_FACTORY_VIEW.VAR7
     *
     * @mbggenerated
     */
    public void setVar7(String var7) {
        this.var7 = var7 == null ? null : var7.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPORT_FACTORY_VIEW.VAR8
     *
     * @return the value of REPORT_FACTORY_VIEW.VAR8
     *
     * @mbggenerated
     */
    public String getVar8() {
        return var8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPORT_FACTORY_VIEW.VAR8
     *
     * @param var8 the value for REPORT_FACTORY_VIEW.VAR8
     *
     * @mbggenerated
     */
    public void setVar8(String var8) {
        this.var8 = var8 == null ? null : var8.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPORT_FACTORY_VIEW.VAR9
     *
     * @return the value of REPORT_FACTORY_VIEW.VAR9
     *
     * @mbggenerated
     */
    public String getVar9() {
        return var9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPORT_FACTORY_VIEW.VAR9
     *
     * @param var9 the value for REPORT_FACTORY_VIEW.VAR9
     *
     * @mbggenerated
     */
    public void setVar9(String var9) {
        this.var9 = var9 == null ? null : var9.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPORT_FACTORY_VIEW.VAR10
     *
     * @return the value of REPORT_FACTORY_VIEW.VAR10
     *
     * @mbggenerated
     */
    public String getVar10() {
        return var10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPORT_FACTORY_VIEW.VAR10
     *
     * @param var10 the value for REPORT_FACTORY_VIEW.VAR10
     *
     * @mbggenerated
     */
    public void setVar10(String var10) {
        this.var10 = var10 == null ? null : var10.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPORT_FACTORY_VIEW.VAR11
     *
     * @return the value of REPORT_FACTORY_VIEW.VAR11
     *
     * @mbggenerated
     */
    public String getVar11() {
        return var11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPORT_FACTORY_VIEW.VAR11
     *
     * @param var11 the value for REPORT_FACTORY_VIEW.VAR11
     *
     * @mbggenerated
     */
    public void setVar11(String var11) {
        this.var11 = var11 == null ? null : var11.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPORT_FACTORY_VIEW.VAR12
     *
     * @return the value of REPORT_FACTORY_VIEW.VAR12
     *
     * @mbggenerated
     */
    public String getVar12() {
        return var12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPORT_FACTORY_VIEW.VAR12
     *
     * @param var12 the value for REPORT_FACTORY_VIEW.VAR12
     *
     * @mbggenerated
     */
    public void setVar12(String var12) {
        this.var12 = var12 == null ? null : var12.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPORT_FACTORY_VIEW.VAR13
     *
     * @return the value of REPORT_FACTORY_VIEW.VAR13
     *
     * @mbggenerated
     */
    public String getVar13() {
        return var13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPORT_FACTORY_VIEW.VAR13
     *
     * @param var13 the value for REPORT_FACTORY_VIEW.VAR13
     *
     * @mbggenerated
     */
    public void setVar13(String var13) {
        this.var13 = var13 == null ? null : var13.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPORT_FACTORY_VIEW.VAR14
     *
     * @return the value of REPORT_FACTORY_VIEW.VAR14
     *
     * @mbggenerated
     */
    public String getVar14() {
        return var14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPORT_FACTORY_VIEW.VAR14
     *
     * @param var14 the value for REPORT_FACTORY_VIEW.VAR14
     *
     * @mbggenerated
     */
    public void setVar14(String var14) {
        this.var14 = var14 == null ? null : var14.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPORT_FACTORY_VIEW.VAR15
     *
     * @return the value of REPORT_FACTORY_VIEW.VAR15
     *
     * @mbggenerated
     */
    public String getVar15() {
        return var15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPORT_FACTORY_VIEW.VAR15
     *
     * @param var15 the value for REPORT_FACTORY_VIEW.VAR15
     *
     * @mbggenerated
     */
    public void setVar15(String var15) {
        this.var15 = var15 == null ? null : var15.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPORT_FACTORY_VIEW.VAR16
     *
     * @return the value of REPORT_FACTORY_VIEW.VAR16
     *
     * @mbggenerated
     */
    public String getVar16() {
        return var16;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPORT_FACTORY_VIEW.VAR16
     *
     * @param var16 the value for REPORT_FACTORY_VIEW.VAR16
     *
     * @mbggenerated
     */
    public void setVar16(String var16) {
        this.var16 = var16 == null ? null : var16.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPORT_FACTORY_VIEW.VAR17
     *
     * @return the value of REPORT_FACTORY_VIEW.VAR17
     *
     * @mbggenerated
     */
    public String getVar17() {
        return var17;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPORT_FACTORY_VIEW.VAR17
     *
     * @param var17 the value for REPORT_FACTORY_VIEW.VAR17
     *
     * @mbggenerated
     */
    public void setVar17(String var17) {
        this.var17 = var17 == null ? null : var17.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPORT_FACTORY_VIEW.VAR18
     *
     * @return the value of REPORT_FACTORY_VIEW.VAR18
     *
     * @mbggenerated
     */
    public String getVar18() {
        return var18;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPORT_FACTORY_VIEW.VAR18
     *
     * @param var18 the value for REPORT_FACTORY_VIEW.VAR18
     *
     * @mbggenerated
     */
    public void setVar18(String var18) {
        this.var18 = var18 == null ? null : var18.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPORT_FACTORY_VIEW.VAR19
     *
     * @return the value of REPORT_FACTORY_VIEW.VAR19
     *
     * @mbggenerated
     */
    public String getVar19() {
        return var19;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPORT_FACTORY_VIEW.VAR19
     *
     * @param var19 the value for REPORT_FACTORY_VIEW.VAR19
     *
     * @mbggenerated
     */
    public void setVar19(String var19) {
        this.var19 = var19 == null ? null : var19.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPORT_FACTORY_VIEW.VAR20
     *
     * @return the value of REPORT_FACTORY_VIEW.VAR20
     *
     * @mbggenerated
     */
    public String getVar20() {
        return var20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPORT_FACTORY_VIEW.VAR20
     *
     * @param var20 the value for REPORT_FACTORY_VIEW.VAR20
     *
     * @mbggenerated
     */
    public void setVar20(String var20) {
        this.var20 = var20 == null ? null : var20.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPORT_FACTORY_VIEW.NUM1
     *
     * @return the value of REPORT_FACTORY_VIEW.NUM1
     *
     * @mbggenerated
     */
    public Short getNum1() {
        return num1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPORT_FACTORY_VIEW.NUM1
     *
     * @param num1 the value for REPORT_FACTORY_VIEW.NUM1
     *
     * @mbggenerated
     */
    public void setNum1(Short num1) {
        this.num1 = num1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPORT_FACTORY_VIEW.NUM2
     *
     * @return the value of REPORT_FACTORY_VIEW.NUM2
     *
     * @mbggenerated
     */
    public Short getNum2() {
        return num2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPORT_FACTORY_VIEW.NUM2
     *
     * @param num2 the value for REPORT_FACTORY_VIEW.NUM2
     *
     * @mbggenerated
     */
    public void setNum2(Short num2) {
        this.num2 = num2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPORT_FACTORY_VIEW.NUM3
     *
     * @return the value of REPORT_FACTORY_VIEW.NUM3
     *
     * @mbggenerated
     */
    public Short getNum3() {
        return num3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPORT_FACTORY_VIEW.NUM3
     *
     * @param num3 the value for REPORT_FACTORY_VIEW.NUM3
     *
     * @mbggenerated
     */
    public void setNum3(Short num3) {
        this.num3 = num3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPORT_FACTORY_VIEW.NUM4
     *
     * @return the value of REPORT_FACTORY_VIEW.NUM4
     *
     * @mbggenerated
     */
    public Short getNum4() {
        return num4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPORT_FACTORY_VIEW.NUM4
     *
     * @param num4 the value for REPORT_FACTORY_VIEW.NUM4
     *
     * @mbggenerated
     */
    public void setNum4(Short num4) {
        this.num4 = num4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPORT_FACTORY_VIEW.NUM5
     *
     * @return the value of REPORT_FACTORY_VIEW.NUM5
     *
     * @mbggenerated
     */
    public Short getNum5() {
        return num5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPORT_FACTORY_VIEW.NUM5
     *
     * @param num5 the value for REPORT_FACTORY_VIEW.NUM5
     *
     * @mbggenerated
     */
    public void setNum5(Short num5) {
        this.num5 = num5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPORT_FACTORY_VIEW.NUM6
     *
     * @return the value of REPORT_FACTORY_VIEW.NUM6
     *
     * @mbggenerated
     */
    public Short getNum6() {
        return num6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPORT_FACTORY_VIEW.NUM6
     *
     * @param num6 the value for REPORT_FACTORY_VIEW.NUM6
     *
     * @mbggenerated
     */
    public void setNum6(Short num6) {
        this.num6 = num6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPORT_FACTORY_VIEW.NUM7
     *
     * @return the value of REPORT_FACTORY_VIEW.NUM7
     *
     * @mbggenerated
     */
    public Short getNum7() {
        return num7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPORT_FACTORY_VIEW.NUM7
     *
     * @param num7 the value for REPORT_FACTORY_VIEW.NUM7
     *
     * @mbggenerated
     */
    public void setNum7(Short num7) {
        this.num7 = num7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPORT_FACTORY_VIEW.NUM8
     *
     * @return the value of REPORT_FACTORY_VIEW.NUM8
     *
     * @mbggenerated
     */
    public Short getNum8() {
        return num8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPORT_FACTORY_VIEW.NUM8
     *
     * @param num8 the value for REPORT_FACTORY_VIEW.NUM8
     *
     * @mbggenerated
     */
    public void setNum8(Short num8) {
        this.num8 = num8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPORT_FACTORY_VIEW.NUM9
     *
     * @return the value of REPORT_FACTORY_VIEW.NUM9
     *
     * @mbggenerated
     */
    public Short getNum9() {
        return num9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPORT_FACTORY_VIEW.NUM9
     *
     * @param num9 the value for REPORT_FACTORY_VIEW.NUM9
     *
     * @mbggenerated
     */
    public void setNum9(Short num9) {
        this.num9 = num9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPORT_FACTORY_VIEW.NUM10
     *
     * @return the value of REPORT_FACTORY_VIEW.NUM10
     *
     * @mbggenerated
     */
    public Short getNum10() {
        return num10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPORT_FACTORY_VIEW.NUM10
     *
     * @param num10 the value for REPORT_FACTORY_VIEW.NUM10
     *
     * @mbggenerated
     */
    public void setNum10(Short num10) {
        this.num10 = num10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPORT_FACTORY_VIEW.NUM11
     *
     * @return the value of REPORT_FACTORY_VIEW.NUM11
     *
     * @mbggenerated
     */
    public Short getNum11() {
        return num11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPORT_FACTORY_VIEW.NUM11
     *
     * @param num11 the value for REPORT_FACTORY_VIEW.NUM11
     *
     * @mbggenerated
     */
    public void setNum11(Short num11) {
        this.num11 = num11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPORT_FACTORY_VIEW.NUM12
     *
     * @return the value of REPORT_FACTORY_VIEW.NUM12
     *
     * @mbggenerated
     */
    public Short getNum12() {
        return num12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPORT_FACTORY_VIEW.NUM12
     *
     * @param num12 the value for REPORT_FACTORY_VIEW.NUM12
     *
     * @mbggenerated
     */
    public void setNum12(Short num12) {
        this.num12 = num12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPORT_FACTORY_VIEW.NUM13
     *
     * @return the value of REPORT_FACTORY_VIEW.NUM13
     *
     * @mbggenerated
     */
    public Short getNum13() {
        return num13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPORT_FACTORY_VIEW.NUM13
     *
     * @param num13 the value for REPORT_FACTORY_VIEW.NUM13
     *
     * @mbggenerated
     */
    public void setNum13(Short num13) {
        this.num13 = num13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPORT_FACTORY_VIEW.NUM14
     *
     * @return the value of REPORT_FACTORY_VIEW.NUM14
     *
     * @mbggenerated
     */
    public Short getNum14() {
        return num14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPORT_FACTORY_VIEW.NUM14
     *
     * @param num14 the value for REPORT_FACTORY_VIEW.NUM14
     *
     * @mbggenerated
     */
    public void setNum14(Short num14) {
        this.num14 = num14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPORT_FACTORY_VIEW.NUM15
     *
     * @return the value of REPORT_FACTORY_VIEW.NUM15
     *
     * @mbggenerated
     */
    public Short getNum15() {
        return num15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPORT_FACTORY_VIEW.NUM15
     *
     * @param num15 the value for REPORT_FACTORY_VIEW.NUM15
     *
     * @mbggenerated
     */
    public void setNum15(Short num15) {
        this.num15 = num15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPORT_FACTORY_VIEW.NUM16
     *
     * @return the value of REPORT_FACTORY_VIEW.NUM16
     *
     * @mbggenerated
     */
    public Short getNum16() {
        return num16;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPORT_FACTORY_VIEW.NUM16
     *
     * @param num16 the value for REPORT_FACTORY_VIEW.NUM16
     *
     * @mbggenerated
     */
    public void setNum16(Short num16) {
        this.num16 = num16;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPORT_FACTORY_VIEW.NUM17
     *
     * @return the value of REPORT_FACTORY_VIEW.NUM17
     *
     * @mbggenerated
     */
    public Short getNum17() {
        return num17;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPORT_FACTORY_VIEW.NUM17
     *
     * @param num17 the value for REPORT_FACTORY_VIEW.NUM17
     *
     * @mbggenerated
     */
    public void setNum17(Short num17) {
        this.num17 = num17;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPORT_FACTORY_VIEW.NUM18
     *
     * @return the value of REPORT_FACTORY_VIEW.NUM18
     *
     * @mbggenerated
     */
    public Short getNum18() {
        return num18;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPORT_FACTORY_VIEW.NUM18
     *
     * @param num18 the value for REPORT_FACTORY_VIEW.NUM18
     *
     * @mbggenerated
     */
    public void setNum18(Short num18) {
        this.num18 = num18;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPORT_FACTORY_VIEW.NUM19
     *
     * @return the value of REPORT_FACTORY_VIEW.NUM19
     *
     * @mbggenerated
     */
    public Short getNum19() {
        return num19;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPORT_FACTORY_VIEW.NUM19
     *
     * @param num19 the value for REPORT_FACTORY_VIEW.NUM19
     *
     * @mbggenerated
     */
    public void setNum19(Short num19) {
        this.num19 = num19;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPORT_FACTORY_VIEW.NUM20
     *
     * @return the value of REPORT_FACTORY_VIEW.NUM20
     *
     * @mbggenerated
     */
    public Short getNum20() {
        return num20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPORT_FACTORY_VIEW.NUM20
     *
     * @param num20 the value for REPORT_FACTORY_VIEW.NUM20
     *
     * @mbggenerated
     */
    public void setNum20(Short num20) {
        this.num20 = num20;
    }
}