package com.bdcor.pip.web.data.domain;

public class UqsAttributeKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIP_UQS_ATTRIBUTE.ATTRIBUTE_ID
     *
     * @mbggenerated
     */
    private String attributeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIP_UQS_ATTRIBUTE.OPTION_ID
     *
     * @mbggenerated
     */
    private String optionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIP_UQS_ATTRIBUTE.PROJECT_ID
     *
     * @mbggenerated
     */
    private String projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIP_UQS_ATTRIBUTE.QUESTIONNAIRE_ID
     *
     * @mbggenerated
     */
    private String questionnaireId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIP_UQS_ATTRIBUTE.QUESTIONSET_ID
     *
     * @mbggenerated
     */
    private String questionsetId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIP_UQS_ATTRIBUTE.QUESTION_ID
     *
     * @mbggenerated
     */
    private String questionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIP_UQS_ATTRIBUTE.ATTRIBUTE_ID
     *
     * @return the value of PIP_UQS_ATTRIBUTE.ATTRIBUTE_ID
     *
     * @mbggenerated
     */
    public String getAttributeId() {
        return attributeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIP_UQS_ATTRIBUTE.ATTRIBUTE_ID
     *
     * @param attributeId the value for PIP_UQS_ATTRIBUTE.ATTRIBUTE_ID
     *
     * @mbggenerated
     */
    public void setAttributeId(String attributeId) {
        this.attributeId = attributeId == null ? null : attributeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIP_UQS_ATTRIBUTE.OPTION_ID
     *
     * @return the value of PIP_UQS_ATTRIBUTE.OPTION_ID
     *
     * @mbggenerated
     */
    public String getOptionId() {
        return optionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIP_UQS_ATTRIBUTE.OPTION_ID
     *
     * @param optionId the value for PIP_UQS_ATTRIBUTE.OPTION_ID
     *
     * @mbggenerated
     */
    public void setOptionId(String optionId) {
        this.optionId = optionId == null ? null : optionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIP_UQS_ATTRIBUTE.PROJECT_ID
     *
     * @return the value of PIP_UQS_ATTRIBUTE.PROJECT_ID
     *
     * @mbggenerated
     */
    public String getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIP_UQS_ATTRIBUTE.PROJECT_ID
     *
     * @param projectId the value for PIP_UQS_ATTRIBUTE.PROJECT_ID
     *
     * @mbggenerated
     */
    public void setProjectId(String projectId) {
        this.projectId = projectId == null ? null : projectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIP_UQS_ATTRIBUTE.QUESTIONNAIRE_ID
     *
     * @return the value of PIP_UQS_ATTRIBUTE.QUESTIONNAIRE_ID
     *
     * @mbggenerated
     */
    public String getQuestionnaireId() {
        return questionnaireId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIP_UQS_ATTRIBUTE.QUESTIONNAIRE_ID
     *
     * @param questionnaireId the value for PIP_UQS_ATTRIBUTE.QUESTIONNAIRE_ID
     *
     * @mbggenerated
     */
    public void setQuestionnaireId(String questionnaireId) {
        this.questionnaireId = questionnaireId == null ? null : questionnaireId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIP_UQS_ATTRIBUTE.QUESTIONSET_ID
     *
     * @return the value of PIP_UQS_ATTRIBUTE.QUESTIONSET_ID
     *
     * @mbggenerated
     */
    public String getQuestionsetId() {
        return questionsetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIP_UQS_ATTRIBUTE.QUESTIONSET_ID
     *
     * @param questionsetId the value for PIP_UQS_ATTRIBUTE.QUESTIONSET_ID
     *
     * @mbggenerated
     */
    public void setQuestionsetId(String questionsetId) {
        this.questionsetId = questionsetId == null ? null : questionsetId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIP_UQS_ATTRIBUTE.QUESTION_ID
     *
     * @return the value of PIP_UQS_ATTRIBUTE.QUESTION_ID
     *
     * @mbggenerated
     */
    public String getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIP_UQS_ATTRIBUTE.QUESTION_ID
     *
     * @param questionId the value for PIP_UQS_ATTRIBUTE.QUESTION_ID
     *
     * @mbggenerated
     */
    public void setQuestionId(String questionId) {
        this.questionId = questionId == null ? null : questionId.trim();
    }
}