package com.bdcor.pip.web.data.domain;

public class UqsQuestionSetKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIP_UQS_QUESTIONSET.PROJECT_ID
     *
     * @mbggenerated
     */
    private String projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIP_UQS_QUESTIONSET.QUESTIONNAIRE_ID
     *
     * @mbggenerated
     */
    private String questionnaireId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIP_UQS_QUESTIONSET.QUESTIONSET_ID
     *
     * @mbggenerated
     */
    private String questionsetId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIP_UQS_QUESTIONSET.PROJECT_ID
     *
     * @return the value of PIP_UQS_QUESTIONSET.PROJECT_ID
     *
     * @mbggenerated
     */
    public String getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIP_UQS_QUESTIONSET.PROJECT_ID
     *
     * @param projectId the value for PIP_UQS_QUESTIONSET.PROJECT_ID
     *
     * @mbggenerated
     */
    public void setProjectId(String projectId) {
        this.projectId = projectId == null ? null : projectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIP_UQS_QUESTIONSET.QUESTIONNAIRE_ID
     *
     * @return the value of PIP_UQS_QUESTIONSET.QUESTIONNAIRE_ID
     *
     * @mbggenerated
     */
    public String getQuestionnaireId() {
        return questionnaireId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIP_UQS_QUESTIONSET.QUESTIONNAIRE_ID
     *
     * @param questionnaireId the value for PIP_UQS_QUESTIONSET.QUESTIONNAIRE_ID
     *
     * @mbggenerated
     */
    public void setQuestionnaireId(String questionnaireId) {
        this.questionnaireId = questionnaireId == null ? null : questionnaireId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIP_UQS_QUESTIONSET.QUESTIONSET_ID
     *
     * @return the value of PIP_UQS_QUESTIONSET.QUESTIONSET_ID
     *
     * @mbggenerated
     */
    public String getQuestionsetId() {
        return questionsetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIP_UQS_QUESTIONSET.QUESTIONSET_ID
     *
     * @param questionsetId the value for PIP_UQS_QUESTIONSET.QUESTIONSET_ID
     *
     * @mbggenerated
     */
    public void setQuestionsetId(String questionsetId) {
        this.questionsetId = questionsetId == null ? null : questionsetId.trim();
    }
}