package com.bdcor.pip.web.data.domain;

import java.util.ArrayList;
import java.util.List;

public class UqsScanViewExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table UQS_SCAN_VIEW
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table UQS_SCAN_VIEW
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table UQS_SCAN_VIEW
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UQS_SCAN_VIEW
     *
     * @mbggenerated
     */
    public UqsScanViewExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UQS_SCAN_VIEW
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UQS_SCAN_VIEW
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UQS_SCAN_VIEW
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UQS_SCAN_VIEW
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UQS_SCAN_VIEW
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UQS_SCAN_VIEW
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UQS_SCAN_VIEW
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UQS_SCAN_VIEW
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UQS_SCAN_VIEW
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UQS_SCAN_VIEW
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table UQS_SCAN_VIEW
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPatientIdIsNull() {
            addCriterion("PATIENT_ID is null");
            return (Criteria) this;
        }

        public Criteria andPatientIdIsNotNull() {
            addCriterion("PATIENT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andPatientIdEqualTo(String value) {
            addCriterion("PATIENT_ID =", value, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdNotEqualTo(String value) {
            addCriterion("PATIENT_ID <>", value, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdGreaterThan(String value) {
            addCriterion("PATIENT_ID >", value, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdGreaterThanOrEqualTo(String value) {
            addCriterion("PATIENT_ID >=", value, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdLessThan(String value) {
            addCriterion("PATIENT_ID <", value, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdLessThanOrEqualTo(String value) {
            addCriterion("PATIENT_ID <=", value, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdLike(String value) {
            addCriterion("PATIENT_ID like", value, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdNotLike(String value) {
            addCriterion("PATIENT_ID not like", value, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdIn(List<String> values) {
            addCriterion("PATIENT_ID in", values, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdNotIn(List<String> values) {
            addCriterion("PATIENT_ID not in", values, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdBetween(String value1, String value2) {
            addCriterion("PATIENT_ID between", value1, value2, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdNotBetween(String value1, String value2) {
            addCriterion("PATIENT_ID not between", value1, value2, "patientId");
            return (Criteria) this;
        }

        public Criteria andLccCodeIsNull() {
            addCriterion("LCC_CODE is null");
            return (Criteria) this;
        }

        public Criteria andLccCodeIsNotNull() {
            addCriterion("LCC_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andLccCodeEqualTo(String value) {
            addCriterion("LCC_CODE =", value, "lccCode");
            return (Criteria) this;
        }

        public Criteria andLccCodeNotEqualTo(String value) {
            addCriterion("LCC_CODE <>", value, "lccCode");
            return (Criteria) this;
        }

        public Criteria andLccCodeGreaterThan(String value) {
            addCriterion("LCC_CODE >", value, "lccCode");
            return (Criteria) this;
        }

        public Criteria andLccCodeGreaterThanOrEqualTo(String value) {
            addCriterion("LCC_CODE >=", value, "lccCode");
            return (Criteria) this;
        }

        public Criteria andLccCodeLessThan(String value) {
            addCriterion("LCC_CODE <", value, "lccCode");
            return (Criteria) this;
        }

        public Criteria andLccCodeLessThanOrEqualTo(String value) {
            addCriterion("LCC_CODE <=", value, "lccCode");
            return (Criteria) this;
        }

        public Criteria andLccCodeLike(String value) {
            addCriterion("LCC_CODE like", value, "lccCode");
            return (Criteria) this;
        }

        public Criteria andLccCodeNotLike(String value) {
            addCriterion("LCC_CODE not like", value, "lccCode");
            return (Criteria) this;
        }

        public Criteria andLccCodeIn(List<String> values) {
            addCriterion("LCC_CODE in", values, "lccCode");
            return (Criteria) this;
        }

        public Criteria andLccCodeNotIn(List<String> values) {
            addCriterion("LCC_CODE not in", values, "lccCode");
            return (Criteria) this;
        }

        public Criteria andLccCodeBetween(String value1, String value2) {
            addCriterion("LCC_CODE between", value1, value2, "lccCode");
            return (Criteria) this;
        }

        public Criteria andLccCodeNotBetween(String value1, String value2) {
            addCriterion("LCC_CODE not between", value1, value2, "lccCode");
            return (Criteria) this;
        }

        public Criteria andPatientNameIsNull() {
            addCriterion("PATIENT_NAME is null");
            return (Criteria) this;
        }

        public Criteria andPatientNameIsNotNull() {
            addCriterion("PATIENT_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andPatientNameEqualTo(String value) {
            addCriterion("PATIENT_NAME =", value, "patientName");
            return (Criteria) this;
        }

        public Criteria andPatientNameNotEqualTo(String value) {
            addCriterion("PATIENT_NAME <>", value, "patientName");
            return (Criteria) this;
        }

        public Criteria andPatientNameGreaterThan(String value) {
            addCriterion("PATIENT_NAME >", value, "patientName");
            return (Criteria) this;
        }

        public Criteria andPatientNameGreaterThanOrEqualTo(String value) {
            addCriterion("PATIENT_NAME >=", value, "patientName");
            return (Criteria) this;
        }

        public Criteria andPatientNameLessThan(String value) {
            addCriterion("PATIENT_NAME <", value, "patientName");
            return (Criteria) this;
        }

        public Criteria andPatientNameLessThanOrEqualTo(String value) {
            addCriterion("PATIENT_NAME <=", value, "patientName");
            return (Criteria) this;
        }

        public Criteria andPatientNameLike(String value) {
            addCriterion("PATIENT_NAME like", value, "patientName");
            return (Criteria) this;
        }

        public Criteria andPatientNameNotLike(String value) {
            addCriterion("PATIENT_NAME not like", value, "patientName");
            return (Criteria) this;
        }

        public Criteria andPatientNameIn(List<String> values) {
            addCriterion("PATIENT_NAME in", values, "patientName");
            return (Criteria) this;
        }

        public Criteria andPatientNameNotIn(List<String> values) {
            addCriterion("PATIENT_NAME not in", values, "patientName");
            return (Criteria) this;
        }

        public Criteria andPatientNameBetween(String value1, String value2) {
            addCriterion("PATIENT_NAME between", value1, value2, "patientName");
            return (Criteria) this;
        }

        public Criteria andPatientNameNotBetween(String value1, String value2) {
            addCriterion("PATIENT_NAME not between", value1, value2, "patientName");
            return (Criteria) this;
        }

        public Criteria andSexIsNull() {
            addCriterion("SEX is null");
            return (Criteria) this;
        }

        public Criteria andSexIsNotNull() {
            addCriterion("SEX is not null");
            return (Criteria) this;
        }

        public Criteria andSexEqualTo(String value) {
            addCriterion("SEX =", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotEqualTo(String value) {
            addCriterion("SEX <>", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThan(String value) {
            addCriterion("SEX >", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThanOrEqualTo(String value) {
            addCriterion("SEX >=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThan(String value) {
            addCriterion("SEX <", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThanOrEqualTo(String value) {
            addCriterion("SEX <=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLike(String value) {
            addCriterion("SEX like", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotLike(String value) {
            addCriterion("SEX not like", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexIn(List<String> values) {
            addCriterion("SEX in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotIn(List<String> values) {
            addCriterion("SEX not in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexBetween(String value1, String value2) {
            addCriterion("SEX between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotBetween(String value1, String value2) {
            addCriterion("SEX not between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andNationIsNull() {
            addCriterion("NATION is null");
            return (Criteria) this;
        }

        public Criteria andNationIsNotNull() {
            addCriterion("NATION is not null");
            return (Criteria) this;
        }

        public Criteria andNationEqualTo(String value) {
            addCriterion("NATION =", value, "nation");
            return (Criteria) this;
        }

        public Criteria andNationNotEqualTo(String value) {
            addCriterion("NATION <>", value, "nation");
            return (Criteria) this;
        }

        public Criteria andNationGreaterThan(String value) {
            addCriterion("NATION >", value, "nation");
            return (Criteria) this;
        }

        public Criteria andNationGreaterThanOrEqualTo(String value) {
            addCriterion("NATION >=", value, "nation");
            return (Criteria) this;
        }

        public Criteria andNationLessThan(String value) {
            addCriterion("NATION <", value, "nation");
            return (Criteria) this;
        }

        public Criteria andNationLessThanOrEqualTo(String value) {
            addCriterion("NATION <=", value, "nation");
            return (Criteria) this;
        }

        public Criteria andNationLike(String value) {
            addCriterion("NATION like", value, "nation");
            return (Criteria) this;
        }

        public Criteria andNationNotLike(String value) {
            addCriterion("NATION not like", value, "nation");
            return (Criteria) this;
        }

        public Criteria andNationIn(List<String> values) {
            addCriterion("NATION in", values, "nation");
            return (Criteria) this;
        }

        public Criteria andNationNotIn(List<String> values) {
            addCriterion("NATION not in", values, "nation");
            return (Criteria) this;
        }

        public Criteria andNationBetween(String value1, String value2) {
            addCriterion("NATION between", value1, value2, "nation");
            return (Criteria) this;
        }

        public Criteria andNationNotBetween(String value1, String value2) {
            addCriterion("NATION not between", value1, value2, "nation");
            return (Criteria) this;
        }

        public Criteria andIdNumberIsNull() {
            addCriterion("ID_NUMBER is null");
            return (Criteria) this;
        }

        public Criteria andIdNumberIsNotNull() {
            addCriterion("ID_NUMBER is not null");
            return (Criteria) this;
        }

        public Criteria andIdNumberEqualTo(String value) {
            addCriterion("ID_NUMBER =", value, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberNotEqualTo(String value) {
            addCriterion("ID_NUMBER <>", value, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberGreaterThan(String value) {
            addCriterion("ID_NUMBER >", value, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberGreaterThanOrEqualTo(String value) {
            addCriterion("ID_NUMBER >=", value, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberLessThan(String value) {
            addCriterion("ID_NUMBER <", value, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberLessThanOrEqualTo(String value) {
            addCriterion("ID_NUMBER <=", value, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberLike(String value) {
            addCriterion("ID_NUMBER like", value, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberNotLike(String value) {
            addCriterion("ID_NUMBER not like", value, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberIn(List<String> values) {
            addCriterion("ID_NUMBER in", values, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberNotIn(List<String> values) {
            addCriterion("ID_NUMBER not in", values, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberBetween(String value1, String value2) {
            addCriterion("ID_NUMBER between", value1, value2, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberNotBetween(String value1, String value2) {
            addCriterion("ID_NUMBER not between", value1, value2, "idNumber");
            return (Criteria) this;
        }

        public Criteria andRiskCodeIsNull() {
            addCriterion("RISK_CODE is null");
            return (Criteria) this;
        }

        public Criteria andRiskCodeIsNotNull() {
            addCriterion("RISK_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andRiskCodeEqualTo(String value) {
            addCriterion("RISK_CODE =", value, "riskCode");
            return (Criteria) this;
        }

        public Criteria andRiskCodeNotEqualTo(String value) {
            addCriterion("RISK_CODE <>", value, "riskCode");
            return (Criteria) this;
        }

        public Criteria andRiskCodeGreaterThan(String value) {
            addCriterion("RISK_CODE >", value, "riskCode");
            return (Criteria) this;
        }

        public Criteria andRiskCodeGreaterThanOrEqualTo(String value) {
            addCriterion("RISK_CODE >=", value, "riskCode");
            return (Criteria) this;
        }

        public Criteria andRiskCodeLessThan(String value) {
            addCriterion("RISK_CODE <", value, "riskCode");
            return (Criteria) this;
        }

        public Criteria andRiskCodeLessThanOrEqualTo(String value) {
            addCriterion("RISK_CODE <=", value, "riskCode");
            return (Criteria) this;
        }

        public Criteria andRiskCodeLike(String value) {
            addCriterion("RISK_CODE like", value, "riskCode");
            return (Criteria) this;
        }

        public Criteria andRiskCodeNotLike(String value) {
            addCriterion("RISK_CODE not like", value, "riskCode");
            return (Criteria) this;
        }

        public Criteria andRiskCodeIn(List<String> values) {
            addCriterion("RISK_CODE in", values, "riskCode");
            return (Criteria) this;
        }

        public Criteria andRiskCodeNotIn(List<String> values) {
            addCriterion("RISK_CODE not in", values, "riskCode");
            return (Criteria) this;
        }

        public Criteria andRiskCodeBetween(String value1, String value2) {
            addCriterion("RISK_CODE between", value1, value2, "riskCode");
            return (Criteria) this;
        }

        public Criteria andRiskCodeNotBetween(String value1, String value2) {
            addCriterion("RISK_CODE not between", value1, value2, "riskCode");
            return (Criteria) this;
        }

        public Criteria andUqs1IsNull() {
            addCriterion("UQS1 is null");
            return (Criteria) this;
        }

        public Criteria andUqs1IsNotNull() {
            addCriterion("UQS1 is not null");
            return (Criteria) this;
        }

        public Criteria andUqs1EqualTo(String value) {
            addCriterion("UQS1 =", value, "uqs1");
            return (Criteria) this;
        }

        public Criteria andUqs1NotEqualTo(String value) {
            addCriterion("UQS1 <>", value, "uqs1");
            return (Criteria) this;
        }

        public Criteria andUqs1GreaterThan(String value) {
            addCriterion("UQS1 >", value, "uqs1");
            return (Criteria) this;
        }

        public Criteria andUqs1GreaterThanOrEqualTo(String value) {
            addCriterion("UQS1 >=", value, "uqs1");
            return (Criteria) this;
        }

        public Criteria andUqs1LessThan(String value) {
            addCriterion("UQS1 <", value, "uqs1");
            return (Criteria) this;
        }

        public Criteria andUqs1LessThanOrEqualTo(String value) {
            addCriterion("UQS1 <=", value, "uqs1");
            return (Criteria) this;
        }

        public Criteria andUqs1Like(String value) {
            addCriterion("UQS1 like", value, "uqs1");
            return (Criteria) this;
        }

        public Criteria andUqs1NotLike(String value) {
            addCriterion("UQS1 not like", value, "uqs1");
            return (Criteria) this;
        }

        public Criteria andUqs1In(List<String> values) {
            addCriterion("UQS1 in", values, "uqs1");
            return (Criteria) this;
        }

        public Criteria andUqs1NotIn(List<String> values) {
            addCriterion("UQS1 not in", values, "uqs1");
            return (Criteria) this;
        }

        public Criteria andUqs1Between(String value1, String value2) {
            addCriterion("UQS1 between", value1, value2, "uqs1");
            return (Criteria) this;
        }

        public Criteria andUqs1NotBetween(String value1, String value2) {
            addCriterion("UQS1 not between", value1, value2, "uqs1");
            return (Criteria) this;
        }

        public Criteria andUqs2IsNull() {
            addCriterion("UQS2 is null");
            return (Criteria) this;
        }

        public Criteria andUqs2IsNotNull() {
            addCriterion("UQS2 is not null");
            return (Criteria) this;
        }

        public Criteria andUqs2EqualTo(String value) {
            addCriterion("UQS2 =", value, "uqs2");
            return (Criteria) this;
        }

        public Criteria andUqs2NotEqualTo(String value) {
            addCriterion("UQS2 <>", value, "uqs2");
            return (Criteria) this;
        }

        public Criteria andUqs2GreaterThan(String value) {
            addCriterion("UQS2 >", value, "uqs2");
            return (Criteria) this;
        }

        public Criteria andUqs2GreaterThanOrEqualTo(String value) {
            addCriterion("UQS2 >=", value, "uqs2");
            return (Criteria) this;
        }

        public Criteria andUqs2LessThan(String value) {
            addCriterion("UQS2 <", value, "uqs2");
            return (Criteria) this;
        }

        public Criteria andUqs2LessThanOrEqualTo(String value) {
            addCriterion("UQS2 <=", value, "uqs2");
            return (Criteria) this;
        }

        public Criteria andUqs2Like(String value) {
            addCriterion("UQS2 like", value, "uqs2");
            return (Criteria) this;
        }

        public Criteria andUqs2NotLike(String value) {
            addCriterion("UQS2 not like", value, "uqs2");
            return (Criteria) this;
        }

        public Criteria andUqs2In(List<String> values) {
            addCriterion("UQS2 in", values, "uqs2");
            return (Criteria) this;
        }

        public Criteria andUqs2NotIn(List<String> values) {
            addCriterion("UQS2 not in", values, "uqs2");
            return (Criteria) this;
        }

        public Criteria andUqs2Between(String value1, String value2) {
            addCriterion("UQS2 between", value1, value2, "uqs2");
            return (Criteria) this;
        }

        public Criteria andUqs2NotBetween(String value1, String value2) {
            addCriterion("UQS2 not between", value1, value2, "uqs2");
            return (Criteria) this;
        }

        public Criteria andUqs3IsNull() {
            addCriterion("UQS3 is null");
            return (Criteria) this;
        }

        public Criteria andUqs3IsNotNull() {
            addCriterion("UQS3 is not null");
            return (Criteria) this;
        }

        public Criteria andUqs3EqualTo(String value) {
            addCriterion("UQS3 =", value, "uqs3");
            return (Criteria) this;
        }

        public Criteria andUqs3NotEqualTo(String value) {
            addCriterion("UQS3 <>", value, "uqs3");
            return (Criteria) this;
        }

        public Criteria andUqs3GreaterThan(String value) {
            addCriterion("UQS3 >", value, "uqs3");
            return (Criteria) this;
        }

        public Criteria andUqs3GreaterThanOrEqualTo(String value) {
            addCriterion("UQS3 >=", value, "uqs3");
            return (Criteria) this;
        }

        public Criteria andUqs3LessThan(String value) {
            addCriterion("UQS3 <", value, "uqs3");
            return (Criteria) this;
        }

        public Criteria andUqs3LessThanOrEqualTo(String value) {
            addCriterion("UQS3 <=", value, "uqs3");
            return (Criteria) this;
        }

        public Criteria andUqs3Like(String value) {
            addCriterion("UQS3 like", value, "uqs3");
            return (Criteria) this;
        }

        public Criteria andUqs3NotLike(String value) {
            addCriterion("UQS3 not like", value, "uqs3");
            return (Criteria) this;
        }

        public Criteria andUqs3In(List<String> values) {
            addCriterion("UQS3 in", values, "uqs3");
            return (Criteria) this;
        }

        public Criteria andUqs3NotIn(List<String> values) {
            addCriterion("UQS3 not in", values, "uqs3");
            return (Criteria) this;
        }

        public Criteria andUqs3Between(String value1, String value2) {
            addCriterion("UQS3 between", value1, value2, "uqs3");
            return (Criteria) this;
        }

        public Criteria andUqs3NotBetween(String value1, String value2) {
            addCriterion("UQS3 not between", value1, value2, "uqs3");
            return (Criteria) this;
        }

        public Criteria andUqs4IsNull() {
            addCriterion("UQS4 is null");
            return (Criteria) this;
        }

        public Criteria andUqs4IsNotNull() {
            addCriterion("UQS4 is not null");
            return (Criteria) this;
        }

        public Criteria andUqs4EqualTo(String value) {
            addCriterion("UQS4 =", value, "uqs4");
            return (Criteria) this;
        }

        public Criteria andUqs4NotEqualTo(String value) {
            addCriterion("UQS4 <>", value, "uqs4");
            return (Criteria) this;
        }

        public Criteria andUqs4GreaterThan(String value) {
            addCriterion("UQS4 >", value, "uqs4");
            return (Criteria) this;
        }

        public Criteria andUqs4GreaterThanOrEqualTo(String value) {
            addCriterion("UQS4 >=", value, "uqs4");
            return (Criteria) this;
        }

        public Criteria andUqs4LessThan(String value) {
            addCriterion("UQS4 <", value, "uqs4");
            return (Criteria) this;
        }

        public Criteria andUqs4LessThanOrEqualTo(String value) {
            addCriterion("UQS4 <=", value, "uqs4");
            return (Criteria) this;
        }

        public Criteria andUqs4Like(String value) {
            addCriterion("UQS4 like", value, "uqs4");
            return (Criteria) this;
        }

        public Criteria andUqs4NotLike(String value) {
            addCriterion("UQS4 not like", value, "uqs4");
            return (Criteria) this;
        }

        public Criteria andUqs4In(List<String> values) {
            addCriterion("UQS4 in", values, "uqs4");
            return (Criteria) this;
        }

        public Criteria andUqs4NotIn(List<String> values) {
            addCriterion("UQS4 not in", values, "uqs4");
            return (Criteria) this;
        }

        public Criteria andUqs4Between(String value1, String value2) {
            addCriterion("UQS4 between", value1, value2, "uqs4");
            return (Criteria) this;
        }

        public Criteria andUqs4NotBetween(String value1, String value2) {
            addCriterion("UQS4 not between", value1, value2, "uqs4");
            return (Criteria) this;
        }

        public Criteria andUqs5IsNull() {
            addCriterion("UQS5 is null");
            return (Criteria) this;
        }

        public Criteria andUqs5IsNotNull() {
            addCriterion("UQS5 is not null");
            return (Criteria) this;
        }

        public Criteria andUqs5EqualTo(String value) {
            addCriterion("UQS5 =", value, "uqs5");
            return (Criteria) this;
        }

        public Criteria andUqs5NotEqualTo(String value) {
            addCriterion("UQS5 <>", value, "uqs5");
            return (Criteria) this;
        }

        public Criteria andUqs5GreaterThan(String value) {
            addCriterion("UQS5 >", value, "uqs5");
            return (Criteria) this;
        }

        public Criteria andUqs5GreaterThanOrEqualTo(String value) {
            addCriterion("UQS5 >=", value, "uqs5");
            return (Criteria) this;
        }

        public Criteria andUqs5LessThan(String value) {
            addCriterion("UQS5 <", value, "uqs5");
            return (Criteria) this;
        }

        public Criteria andUqs5LessThanOrEqualTo(String value) {
            addCriterion("UQS5 <=", value, "uqs5");
            return (Criteria) this;
        }

        public Criteria andUqs5Like(String value) {
            addCriterion("UQS5 like", value, "uqs5");
            return (Criteria) this;
        }

        public Criteria andUqs5NotLike(String value) {
            addCriterion("UQS5 not like", value, "uqs5");
            return (Criteria) this;
        }

        public Criteria andUqs5In(List<String> values) {
            addCriterion("UQS5 in", values, "uqs5");
            return (Criteria) this;
        }

        public Criteria andUqs5NotIn(List<String> values) {
            addCriterion("UQS5 not in", values, "uqs5");
            return (Criteria) this;
        }

        public Criteria andUqs5Between(String value1, String value2) {
            addCriterion("UQS5 between", value1, value2, "uqs5");
            return (Criteria) this;
        }

        public Criteria andUqs5NotBetween(String value1, String value2) {
            addCriterion("UQS5 not between", value1, value2, "uqs5");
            return (Criteria) this;
        }

        public Criteria andUqs6IsNull() {
            addCriterion("UQS6 is null");
            return (Criteria) this;
        }

        public Criteria andUqs6IsNotNull() {
            addCriterion("UQS6 is not null");
            return (Criteria) this;
        }

        public Criteria andUqs6EqualTo(String value) {
            addCriterion("UQS6 =", value, "uqs6");
            return (Criteria) this;
        }

        public Criteria andUqs6NotEqualTo(String value) {
            addCriterion("UQS6 <>", value, "uqs6");
            return (Criteria) this;
        }

        public Criteria andUqs6GreaterThan(String value) {
            addCriterion("UQS6 >", value, "uqs6");
            return (Criteria) this;
        }

        public Criteria andUqs6GreaterThanOrEqualTo(String value) {
            addCriterion("UQS6 >=", value, "uqs6");
            return (Criteria) this;
        }

        public Criteria andUqs6LessThan(String value) {
            addCriterion("UQS6 <", value, "uqs6");
            return (Criteria) this;
        }

        public Criteria andUqs6LessThanOrEqualTo(String value) {
            addCriterion("UQS6 <=", value, "uqs6");
            return (Criteria) this;
        }

        public Criteria andUqs6Like(String value) {
            addCriterion("UQS6 like", value, "uqs6");
            return (Criteria) this;
        }

        public Criteria andUqs6NotLike(String value) {
            addCriterion("UQS6 not like", value, "uqs6");
            return (Criteria) this;
        }

        public Criteria andUqs6In(List<String> values) {
            addCriterion("UQS6 in", values, "uqs6");
            return (Criteria) this;
        }

        public Criteria andUqs6NotIn(List<String> values) {
            addCriterion("UQS6 not in", values, "uqs6");
            return (Criteria) this;
        }

        public Criteria andUqs6Between(String value1, String value2) {
            addCriterion("UQS6 between", value1, value2, "uqs6");
            return (Criteria) this;
        }

        public Criteria andUqs6NotBetween(String value1, String value2) {
            addCriterion("UQS6 not between", value1, value2, "uqs6");
            return (Criteria) this;
        }

        public Criteria andUqs1DateIsNull() {
            addCriterion("UQS1_DATE is null");
            return (Criteria) this;
        }

        public Criteria andUqs1DateIsNotNull() {
            addCriterion("UQS1_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andUqs1DateEqualTo(String value) {
            addCriterion("UQS1_DATE =", value, "uqs1Date");
            return (Criteria) this;
        }

        public Criteria andUqs1DateNotEqualTo(String value) {
            addCriterion("UQS1_DATE <>", value, "uqs1Date");
            return (Criteria) this;
        }

        public Criteria andUqs1DateGreaterThan(String value) {
            addCriterion("UQS1_DATE >", value, "uqs1Date");
            return (Criteria) this;
        }

        public Criteria andUqs1DateGreaterThanOrEqualTo(String value) {
            addCriterion("UQS1_DATE >=", value, "uqs1Date");
            return (Criteria) this;
        }

        public Criteria andUqs1DateLessThan(String value) {
            addCriterion("UQS1_DATE <", value, "uqs1Date");
            return (Criteria) this;
        }

        public Criteria andUqs1DateLessThanOrEqualTo(String value) {
            addCriterion("UQS1_DATE <=", value, "uqs1Date");
            return (Criteria) this;
        }

        public Criteria andUqs1DateLike(String value) {
            addCriterion("UQS1_DATE like", value, "uqs1Date");
            return (Criteria) this;
        }

        public Criteria andUqs1DateNotLike(String value) {
            addCriterion("UQS1_DATE not like", value, "uqs1Date");
            return (Criteria) this;
        }

        public Criteria andUqs1DateIn(List<String> values) {
            addCriterion("UQS1_DATE in", values, "uqs1Date");
            return (Criteria) this;
        }

        public Criteria andUqs1DateNotIn(List<String> values) {
            addCriterion("UQS1_DATE not in", values, "uqs1Date");
            return (Criteria) this;
        }

        public Criteria andUqs1DateBetween(String value1, String value2) {
            addCriterion("UQS1_DATE between", value1, value2, "uqs1Date");
            return (Criteria) this;
        }

        public Criteria andUqs1DateNotBetween(String value1, String value2) {
            addCriterion("UQS1_DATE not between", value1, value2, "uqs1Date");
            return (Criteria) this;
        }

        public Criteria andUqs2DateIsNull() {
            addCriterion("UQS2_DATE is null");
            return (Criteria) this;
        }

        public Criteria andUqs2DateIsNotNull() {
            addCriterion("UQS2_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andUqs2DateEqualTo(String value) {
            addCriterion("UQS2_DATE =", value, "uqs2Date");
            return (Criteria) this;
        }

        public Criteria andUqs2DateNotEqualTo(String value) {
            addCriterion("UQS2_DATE <>", value, "uqs2Date");
            return (Criteria) this;
        }

        public Criteria andUqs2DateGreaterThan(String value) {
            addCriterion("UQS2_DATE >", value, "uqs2Date");
            return (Criteria) this;
        }

        public Criteria andUqs2DateGreaterThanOrEqualTo(String value) {
            addCriterion("UQS2_DATE >=", value, "uqs2Date");
            return (Criteria) this;
        }

        public Criteria andUqs2DateLessThan(String value) {
            addCriterion("UQS2_DATE <", value, "uqs2Date");
            return (Criteria) this;
        }

        public Criteria andUqs2DateLessThanOrEqualTo(String value) {
            addCriterion("UQS2_DATE <=", value, "uqs2Date");
            return (Criteria) this;
        }

        public Criteria andUqs2DateLike(String value) {
            addCriterion("UQS2_DATE like", value, "uqs2Date");
            return (Criteria) this;
        }

        public Criteria andUqs2DateNotLike(String value) {
            addCriterion("UQS2_DATE not like", value, "uqs2Date");
            return (Criteria) this;
        }

        public Criteria andUqs2DateIn(List<String> values) {
            addCriterion("UQS2_DATE in", values, "uqs2Date");
            return (Criteria) this;
        }

        public Criteria andUqs2DateNotIn(List<String> values) {
            addCriterion("UQS2_DATE not in", values, "uqs2Date");
            return (Criteria) this;
        }

        public Criteria andUqs2DateBetween(String value1, String value2) {
            addCriterion("UQS2_DATE between", value1, value2, "uqs2Date");
            return (Criteria) this;
        }

        public Criteria andUqs2DateNotBetween(String value1, String value2) {
            addCriterion("UQS2_DATE not between", value1, value2, "uqs2Date");
            return (Criteria) this;
        }

        public Criteria andUqs3DateIsNull() {
            addCriterion("UQS3_DATE is null");
            return (Criteria) this;
        }

        public Criteria andUqs3DateIsNotNull() {
            addCriterion("UQS3_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andUqs3DateEqualTo(String value) {
            addCriterion("UQS3_DATE =", value, "uqs3Date");
            return (Criteria) this;
        }

        public Criteria andUqs3DateNotEqualTo(String value) {
            addCriterion("UQS3_DATE <>", value, "uqs3Date");
            return (Criteria) this;
        }

        public Criteria andUqs3DateGreaterThan(String value) {
            addCriterion("UQS3_DATE >", value, "uqs3Date");
            return (Criteria) this;
        }

        public Criteria andUqs3DateGreaterThanOrEqualTo(String value) {
            addCriterion("UQS3_DATE >=", value, "uqs3Date");
            return (Criteria) this;
        }

        public Criteria andUqs3DateLessThan(String value) {
            addCriterion("UQS3_DATE <", value, "uqs3Date");
            return (Criteria) this;
        }

        public Criteria andUqs3DateLessThanOrEqualTo(String value) {
            addCriterion("UQS3_DATE <=", value, "uqs3Date");
            return (Criteria) this;
        }

        public Criteria andUqs3DateLike(String value) {
            addCriterion("UQS3_DATE like", value, "uqs3Date");
            return (Criteria) this;
        }

        public Criteria andUqs3DateNotLike(String value) {
            addCriterion("UQS3_DATE not like", value, "uqs3Date");
            return (Criteria) this;
        }

        public Criteria andUqs3DateIn(List<String> values) {
            addCriterion("UQS3_DATE in", values, "uqs3Date");
            return (Criteria) this;
        }

        public Criteria andUqs3DateNotIn(List<String> values) {
            addCriterion("UQS3_DATE not in", values, "uqs3Date");
            return (Criteria) this;
        }

        public Criteria andUqs3DateBetween(String value1, String value2) {
            addCriterion("UQS3_DATE between", value1, value2, "uqs3Date");
            return (Criteria) this;
        }

        public Criteria andUqs3DateNotBetween(String value1, String value2) {
            addCriterion("UQS3_DATE not between", value1, value2, "uqs3Date");
            return (Criteria) this;
        }

        public Criteria andUqs4DateIsNull() {
            addCriterion("UQS4_DATE is null");
            return (Criteria) this;
        }

        public Criteria andUqs4DateIsNotNull() {
            addCriterion("UQS4_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andUqs4DateEqualTo(String value) {
            addCriterion("UQS4_DATE =", value, "uqs4Date");
            return (Criteria) this;
        }

        public Criteria andUqs4DateNotEqualTo(String value) {
            addCriterion("UQS4_DATE <>", value, "uqs4Date");
            return (Criteria) this;
        }

        public Criteria andUqs4DateGreaterThan(String value) {
            addCriterion("UQS4_DATE >", value, "uqs4Date");
            return (Criteria) this;
        }

        public Criteria andUqs4DateGreaterThanOrEqualTo(String value) {
            addCriterion("UQS4_DATE >=", value, "uqs4Date");
            return (Criteria) this;
        }

        public Criteria andUqs4DateLessThan(String value) {
            addCriterion("UQS4_DATE <", value, "uqs4Date");
            return (Criteria) this;
        }

        public Criteria andUqs4DateLessThanOrEqualTo(String value) {
            addCriterion("UQS4_DATE <=", value, "uqs4Date");
            return (Criteria) this;
        }

        public Criteria andUqs4DateLike(String value) {
            addCriterion("UQS4_DATE like", value, "uqs4Date");
            return (Criteria) this;
        }

        public Criteria andUqs4DateNotLike(String value) {
            addCriterion("UQS4_DATE not like", value, "uqs4Date");
            return (Criteria) this;
        }

        public Criteria andUqs4DateIn(List<String> values) {
            addCriterion("UQS4_DATE in", values, "uqs4Date");
            return (Criteria) this;
        }

        public Criteria andUqs4DateNotIn(List<String> values) {
            addCriterion("UQS4_DATE not in", values, "uqs4Date");
            return (Criteria) this;
        }

        public Criteria andUqs4DateBetween(String value1, String value2) {
            addCriterion("UQS4_DATE between", value1, value2, "uqs4Date");
            return (Criteria) this;
        }

        public Criteria andUqs4DateNotBetween(String value1, String value2) {
            addCriterion("UQS4_DATE not between", value1, value2, "uqs4Date");
            return (Criteria) this;
        }

        public Criteria andUqs5DateIsNull() {
            addCriterion("UQS5_DATE is null");
            return (Criteria) this;
        }

        public Criteria andUqs5DateIsNotNull() {
            addCriterion("UQS5_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andUqs5DateEqualTo(String value) {
            addCriterion("UQS5_DATE =", value, "uqs5Date");
            return (Criteria) this;
        }

        public Criteria andUqs5DateNotEqualTo(String value) {
            addCriterion("UQS5_DATE <>", value, "uqs5Date");
            return (Criteria) this;
        }

        public Criteria andUqs5DateGreaterThan(String value) {
            addCriterion("UQS5_DATE >", value, "uqs5Date");
            return (Criteria) this;
        }

        public Criteria andUqs5DateGreaterThanOrEqualTo(String value) {
            addCriterion("UQS5_DATE >=", value, "uqs5Date");
            return (Criteria) this;
        }

        public Criteria andUqs5DateLessThan(String value) {
            addCriterion("UQS5_DATE <", value, "uqs5Date");
            return (Criteria) this;
        }

        public Criteria andUqs5DateLessThanOrEqualTo(String value) {
            addCriterion("UQS5_DATE <=", value, "uqs5Date");
            return (Criteria) this;
        }

        public Criteria andUqs5DateLike(String value) {
            addCriterion("UQS5_DATE like", value, "uqs5Date");
            return (Criteria) this;
        }

        public Criteria andUqs5DateNotLike(String value) {
            addCriterion("UQS5_DATE not like", value, "uqs5Date");
            return (Criteria) this;
        }

        public Criteria andUqs5DateIn(List<String> values) {
            addCriterion("UQS5_DATE in", values, "uqs5Date");
            return (Criteria) this;
        }

        public Criteria andUqs5DateNotIn(List<String> values) {
            addCriterion("UQS5_DATE not in", values, "uqs5Date");
            return (Criteria) this;
        }

        public Criteria andUqs5DateBetween(String value1, String value2) {
            addCriterion("UQS5_DATE between", value1, value2, "uqs5Date");
            return (Criteria) this;
        }

        public Criteria andUqs5DateNotBetween(String value1, String value2) {
            addCriterion("UQS5_DATE not between", value1, value2, "uqs5Date");
            return (Criteria) this;
        }

        public Criteria andUqs6DateIsNull() {
            addCriterion("UQS6_DATE is null");
            return (Criteria) this;
        }

        public Criteria andUqs6DateIsNotNull() {
            addCriterion("UQS6_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andUqs6DateEqualTo(String value) {
            addCriterion("UQS6_DATE =", value, "uqs6Date");
            return (Criteria) this;
        }

        public Criteria andUqs6DateNotEqualTo(String value) {
            addCriterion("UQS6_DATE <>", value, "uqs6Date");
            return (Criteria) this;
        }

        public Criteria andUqs6DateGreaterThan(String value) {
            addCriterion("UQS6_DATE >", value, "uqs6Date");
            return (Criteria) this;
        }

        public Criteria andUqs6DateGreaterThanOrEqualTo(String value) {
            addCriterion("UQS6_DATE >=", value, "uqs6Date");
            return (Criteria) this;
        }

        public Criteria andUqs6DateLessThan(String value) {
            addCriterion("UQS6_DATE <", value, "uqs6Date");
            return (Criteria) this;
        }

        public Criteria andUqs6DateLessThanOrEqualTo(String value) {
            addCriterion("UQS6_DATE <=", value, "uqs6Date");
            return (Criteria) this;
        }

        public Criteria andUqs6DateLike(String value) {
            addCriterion("UQS6_DATE like", value, "uqs6Date");
            return (Criteria) this;
        }

        public Criteria andUqs6DateNotLike(String value) {
            addCriterion("UQS6_DATE not like", value, "uqs6Date");
            return (Criteria) this;
        }

        public Criteria andUqs6DateIn(List<String> values) {
            addCriterion("UQS6_DATE in", values, "uqs6Date");
            return (Criteria) this;
        }

        public Criteria andUqs6DateNotIn(List<String> values) {
            addCriterion("UQS6_DATE not in", values, "uqs6Date");
            return (Criteria) this;
        }

        public Criteria andUqs6DateBetween(String value1, String value2) {
            addCriterion("UQS6_DATE between", value1, value2, "uqs6Date");
            return (Criteria) this;
        }

        public Criteria andUqs6DateNotBetween(String value1, String value2) {
            addCriterion("UQS6_DATE not between", value1, value2, "uqs6Date");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table UQS_SCAN_VIEW
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table UQS_SCAN_VIEW
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}