package com.bdcor.pip.web.data.dao;

import com.bdcor.pip.core.persistence.MyBatisRepository;
import com.bdcor.pip.web.data.domain.PipCommPatientQcLog;
import com.bdcor.pip.web.data.domain.PipCommPatientUpdateLog;
import com.bdcor.pip.web.data.domain.PipCommPatientUpdateLogExample;
import com.bdcor.pip.web.data.filter.PatientDropLogFilter;

import java.util.List;

import org.apache.ibatis.annotations.Param;


@MyBatisRepository
public interface PipCommPatientUpdateLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIP_COMM_PATIENT_UPDATE_LOG
     *
     * @mbggenerated
     */
    int countByExample(PipCommPatientUpdateLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIP_COMM_PATIENT_UPDATE_LOG
     *
     * @mbggenerated
     */
    int deleteByExample(PipCommPatientUpdateLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIP_COMM_PATIENT_UPDATE_LOG
     *
     * @mbggenerated
     */
    int insert(PipCommPatientUpdateLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIP_COMM_PATIENT_UPDATE_LOG
     *
     * @mbggenerated
     */
    int insertSelective(PipCommPatientUpdateLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIP_COMM_PATIENT_UPDATE_LOG
     *
     * @mbggenerated
     */
    List<PipCommPatientUpdateLog> selectByExample(PipCommPatientUpdateLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIP_COMM_PATIENT_UPDATE_LOG
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PipCommPatientUpdateLog record, @Param("example") PipCommPatientUpdateLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIP_COMM_PATIENT_UPDATE_LOG
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PipCommPatientUpdateLog record, @Param("example") PipCommPatientUpdateLogExample example);
    
    List<PipCommPatientUpdateLog> query(PatientDropLogFilter filter);
}