package com.bdcor.pip.web.data.dao;

import org.apache.ibatis.annotations.Param;

import com.bdcor.pip.core.persistence.MyBatisRepository;
import com.bdcor.pip.web.data.domain.UqsQuestionSet;
import com.bdcor.pip.web.data.domain.UqsQuestionSetExample;
import com.bdcor.pip.web.data.domain.UqsQuestionSetKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

@MyBatisRepository
public interface UqsQuestionSetMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PIP_UQS_QUESTIONSET
	 * @mbggenerated
	 */
	int countByExample(UqsQuestionSetExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PIP_UQS_QUESTIONSET
	 * @mbggenerated
	 */
	int deleteByExample(UqsQuestionSetExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PIP_UQS_QUESTIONSET
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(UqsQuestionSetKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PIP_UQS_QUESTIONSET
	 * @mbggenerated
	 */
	int insert(UqsQuestionSet record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PIP_UQS_QUESTIONSET
	 * @mbggenerated
	 */
	int insertSelective(UqsQuestionSet record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PIP_UQS_QUESTIONSET
	 * @mbggenerated
	 */
	List<UqsQuestionSet> selectByExample(UqsQuestionSetExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PIP_UQS_QUESTIONSET
	 * @mbggenerated
	 */
	UqsQuestionSet selectByPrimaryKey(UqsQuestionSetKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PIP_UQS_QUESTIONSET
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") UqsQuestionSet record,
			@Param("example") UqsQuestionSetExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PIP_UQS_QUESTIONSET
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") UqsQuestionSet record,
			@Param("example") UqsQuestionSetExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PIP_UQS_QUESTIONSET
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(UqsQuestionSet record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PIP_UQS_QUESTIONSET
	 * @mbggenerated
	 */
	int updateByPrimaryKey(UqsQuestionSet record);
}