package com.bdcor.pip.web.data.dao;

import com.bdcor.pip.core.persistence.MyBatisRepository;
import com.bdcor.pip.web.data.domain.UqsScanView;
import com.bdcor.pip.web.data.domain.UqsScanViewExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

@MyBatisRepository
public interface UqsScanViewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UQS_SCAN_VIEW
     *
     * @mbggenerated
     */
    int countByExample(UqsScanViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UQS_SCAN_VIEW
     *
     * @mbggenerated
     */
    int deleteByExample(UqsScanViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UQS_SCAN_VIEW
     *
     * @mbggenerated
     */
    int insert(UqsScanView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UQS_SCAN_VIEW
     *
     * @mbggenerated
     */
    int insertSelective(UqsScanView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UQS_SCAN_VIEW
     *
     * @mbggenerated
     */
    List<UqsScanView> selectByExample(UqsScanViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UQS_SCAN_VIEW
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UqsScanView record, @Param("example") UqsScanViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UQS_SCAN_VIEW
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UqsScanView record, @Param("example") UqsScanViewExample example);
}