package com.bdcor.pip.web.data.dao;

import com.bdcor.pip.core.persistence.MyBatisRepository;
import com.bdcor.pip.web.data.domain.PipFeeInfo;
import com.bdcor.pip.web.data.domain.PipFeeInfoExample;
import com.bdcor.pip.web.data.domain.PipFeeInfoKey;
import com.bdcor.pip.web.data.filter.FeeInfoFilter;

import java.util.List;

import org.apache.ibatis.annotations.Param;

@MyBatisRepository
public interface PipFeeInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIP_FEE_INFO
     *
     * @mbggenerated
     */
    int countByExample(PipFeeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIP_FEE_INFO
     *
     * @mbggenerated
     */
    int deleteByExample(PipFeeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIP_FEE_INFO
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(PipFeeInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIP_FEE_INFO
     *
     * @mbggenerated
     */
    int insert(PipFeeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIP_FEE_INFO
     *
     * @mbggenerated
     */
    int insertSelective(PipFeeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIP_FEE_INFO
     *
     * @mbggenerated
     */
    List<PipFeeInfo> selectByExample(PipFeeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIP_FEE_INFO
     *
     * @mbggenerated
     */
    PipFeeInfo selectByPrimaryKey(PipFeeInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIP_FEE_INFO
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PipFeeInfo record, @Param("example") PipFeeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIP_FEE_INFO
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PipFeeInfo record, @Param("example") PipFeeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIP_FEE_INFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PipFeeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIP_FEE_INFO
     *
     * @mbggenerated
     */
   /* int updateByPrimaryKey(PipFeeInfo record);*/
    
    public List getMapData(@Param("projectId") String projectId,@Param("stType") String stType);
    
    public List getMapDataCity(@Param("projectId") String projectId,@Param("stType") String stType);
    
    public List getChinaData(@Param("projectId") String projectId);
    
    public List getLccDetail(@Param("projectId") String projectId);
    
    public List getLccDetailByDay(FeeInfoFilter filter);
    
    public List getLccDetailByMonth(FeeInfoFilter filter);
    
    public List getLccDetailByWeek(FeeInfoFilter filter);
}