package com.bdcor.pip.web.material.supp.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import org.springframework.format.annotation.DateTimeFormat;

import com.bdcor.pip.client.tools.DateUtils;

public class MasterImport {
	private String imorderNo;
	private String projectId;

	private String type;// 类型,1=新增 2=修改

	private String activeclassName;// 入库类别名
	private String supplierName;// 供货商名称
	private String stockName;// 库房名称;
	private String lccName;// 单位名称
	@DateTimeFormat(pattern="yyyy-MM-dd")
	private Date exportDate;
	private String exportLccCode;
	private String exportLccName;
	@DateTimeFormat(pattern="yyyy-MM-dd")
	private Date orderDate;
	
	public Date getExportDate()
	{
		return exportDate;
	}

	public void setExportDate(Date exportDate)
	{
		this.exportDate = exportDate;
	}

	public String getExportLccCode()
	{
		return exportLccCode;
	}

	public void setExportLccCode(String exportLccCode)
	{
		this.exportLccCode = exportLccCode;
	}

	public String getExportLccName()
	{
		return exportLccName;
	}

	public void setExportLccName(String exportLccName)
	{
		this.exportLccName = exportLccName;
	}

	public Date getOrderDate()
	{
		return orderDate;
	}

	public void setOrderDate(Date orderDate)
	{
		this.orderDate = orderDate;
	}

	private String createDateStr; //创建时间
	public String getCreateDateStr() {
		return DateUtils.fromatDateTime("yyyy-MM-dd", getCreateDate());
	}

	private List<MasterImportDetail> masterImportDetails = new ArrayList<MasterImportDetail>();

	public void setMasterImportDetails(
			List<MasterImportDetail> masterImportDetails) {
		this.masterImportDetails = masterImportDetails;
	}

	public List<MasterImportDetail> getMasterImportDetails() {
		return masterImportDetails;
	}

	public String getImorderNo() {
		return imorderNo;
	}

	public void setImorderNo(String imorderNo) {
		this.imorderNo = imorderNo;
	}

	public String getProjectId() {
		return projectId;
	}

	public void setProjectId(String projectId) {
		this.projectId = projectId;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getStockName() {
		return stockName;
	}

	public void setStockName(String stockName) {
		this.stockName = stockName;
	}

	public String getActiveclassName() {
		return activeclassName;
	}

	public void setActiveclassName(String activeclassName) {
		this.activeclassName = activeclassName;
	}

	public String getSupplierName() {
		return supplierName;
	}

	public void setSupplierName(String supplierName) {
		this.supplierName = supplierName;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PIP_MMS_IMPORT_MASTER.ACTIVECLASS_CODE
	 * 
	 * @mbggenerated Sat Sep 06 10:21:13 CST 2014
	 */
	private String activeclassCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PIP_MMS_IMPORT_MASTER.LCC_CODE
	 * 
	 * @mbggenerated Sat Sep 06 10:21:13 CST 2014
	 */
	private String lccCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PIP_MMS_IMPORT_MASTER.USER_CODE
	 * 
	 * @mbggenerated Sat Sep 06 10:21:13 CST 2014
	 */
	private String userCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PIP_MMS_IMPORT_MASTER.USER_NAME
	 * 
	 * @mbggenerated Sat Sep 06 10:21:13 CST 2014
	 */
	private String userName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PIP_MMS_IMPORT_MASTER.CREATE_DATE
	 * 
	 * @mbggenerated Sat Sep 06 10:21:13 CST 2014
	 */
	@DateTimeFormat(pattern = "yyyy-MM-dd")
	private Date createDate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PIP_MMS_IMPORT_MASTER.CREATE_BY
	 * 
	 * @mbggenerated Sat Sep 06 10:21:13 CST 2014
	 */
	private String createBy;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PIP_MMS_IMPORT_MASTER.IS_REMOVED
	 * 
	 * @mbggenerated Sat Sep 06 10:21:13 CST 2014
	 */
	private Short isRemoved;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PIP_MMS_IMPORT_MASTER.STOCK_CODE
	 * 
	 * @mbggenerated Sat Sep 06 10:21:13 CST 2014
	 */
	private String stockCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PIP_MMS_IMPORT_MASTER.SUPPLIER_CODE
	 * 
	 * @mbggenerated Sat Sep 06 10:21:13 CST 2014
	 */
	private String supplierCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PIP_MMS_IMPORT_MASTER.IMPORT_STATE
	 * 
	 * @mbggenerated Sat Sep 06 10:21:13 CST 2014
	 */
	private Short importState;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PIP_MMS_IMPORT_MASTER.ACTIVECLASS_CODE
	 * 
	 * @return the value of PIP_MMS_IMPORT_MASTER.ACTIVECLASS_CODE
	 * 
	 * @mbggenerated Sat Sep 06 10:21:13 CST 2014
	 */
	public String getActiveclassCode() {
		return activeclassCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PIP_MMS_IMPORT_MASTER.ACTIVECLASS_CODE
	 * 
	 * @param activeclassCode
	 *            the value for PIP_MMS_IMPORT_MASTER.ACTIVECLASS_CODE
	 * 
	 * @mbggenerated Sat Sep 06 10:21:13 CST 2014
	 */
	public void setActiveclassCode(String activeclassCode) {
		this.activeclassCode = activeclassCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PIP_MMS_IMPORT_MASTER.LCC_CODE
	 * 
	 * @return the value of PIP_MMS_IMPORT_MASTER.LCC_CODE
	 * 
	 * @mbggenerated Sat Sep 06 10:21:13 CST 2014
	 */
	public String getLccCode() {
		return lccCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PIP_MMS_IMPORT_MASTER.LCC_CODE
	 * 
	 * @param lccCode
	 *            the value for PIP_MMS_IMPORT_MASTER.LCC_CODE
	 * 
	 * @mbggenerated Sat Sep 06 10:21:13 CST 2014
	 */
	public void setLccCode(String lccCode) {
		this.lccCode = lccCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PIP_MMS_IMPORT_MASTER.USER_CODE
	 * 
	 * @return the value of PIP_MMS_IMPORT_MASTER.USER_CODE
	 * 
	 * @mbggenerated Sat Sep 06 10:21:13 CST 2014
	 */
	public String getUserCode() {
		return userCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PIP_MMS_IMPORT_MASTER.USER_CODE
	 * 
	 * @param userCode
	 *            the value for PIP_MMS_IMPORT_MASTER.USER_CODE
	 * 
	 * @mbggenerated Sat Sep 06 10:21:13 CST 2014
	 */
	public void setUserCode(String userCode) {
		this.userCode = userCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PIP_MMS_IMPORT_MASTER.USER_NAME
	 * 
	 * @return the value of PIP_MMS_IMPORT_MASTER.USER_NAME
	 * 
	 * @mbggenerated Sat Sep 06 10:21:13 CST 2014
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PIP_MMS_IMPORT_MASTER.USER_NAME
	 * 
	 * @param userName
	 *            the value for PIP_MMS_IMPORT_MASTER.USER_NAME
	 * 
	 * @mbggenerated Sat Sep 06 10:21:13 CST 2014
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PIP_MMS_IMPORT_MASTER.CREATE_DATE
	 * 
	 * @return the value of PIP_MMS_IMPORT_MASTER.CREATE_DATE
	 * 
	 * @mbggenerated Sat Sep 06 10:21:13 CST 2014
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PIP_MMS_IMPORT_MASTER.CREATE_DATE
	 * 
	 * @param createDate
	 *            the value for PIP_MMS_IMPORT_MASTER.CREATE_DATE
	 * 
	 * @mbggenerated Sat Sep 06 10:21:13 CST 2014
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PIP_MMS_IMPORT_MASTER.CREATE_BY
	 * 
	 * @return the value of PIP_MMS_IMPORT_MASTER.CREATE_BY
	 * 
	 * @mbggenerated Sat Sep 06 10:21:13 CST 2014
	 */
	public String getCreateBy() {
		return createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PIP_MMS_IMPORT_MASTER.CREATE_BY
	 * 
	 * @param createBy
	 *            the value for PIP_MMS_IMPORT_MASTER.CREATE_BY
	 * 
	 * @mbggenerated Sat Sep 06 10:21:13 CST 2014
	 */
	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PIP_MMS_IMPORT_MASTER.IS_REMOVED
	 * 
	 * @return the value of PIP_MMS_IMPORT_MASTER.IS_REMOVED
	 * 
	 * @mbggenerated Sat Sep 06 10:21:13 CST 2014
	 */
	public Short getIsRemoved() {
		return isRemoved;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PIP_MMS_IMPORT_MASTER.IS_REMOVED
	 * 
	 * @param isRemoved
	 *            the value for PIP_MMS_IMPORT_MASTER.IS_REMOVED
	 * 
	 * @mbggenerated Sat Sep 06 10:21:13 CST 2014
	 */
	public void setIsRemoved(Short isRemoved) {
		this.isRemoved = isRemoved;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PIP_MMS_IMPORT_MASTER.STOCK_CODE
	 * 
	 * @return the value of PIP_MMS_IMPORT_MASTER.STOCK_CODE
	 * 
	 * @mbggenerated Sat Sep 06 10:21:13 CST 2014
	 */
	public String getStockCode() {
		return stockCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PIP_MMS_IMPORT_MASTER.STOCK_CODE
	 * 
	 * @param stockCode
	 *            the value for PIP_MMS_IMPORT_MASTER.STOCK_CODE
	 * 
	 * @mbggenerated Sat Sep 06 10:21:13 CST 2014
	 */
	public void setStockCode(String stockCode) {
		this.stockCode = stockCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PIP_MMS_IMPORT_MASTER.SUPPLIER_CODE
	 * 
	 * @return the value of PIP_MMS_IMPORT_MASTER.SUPPLIER_CODE
	 * 
	 * @mbggenerated Sat Sep 06 10:21:13 CST 2014
	 */
	public String getSupplierCode() {
		return supplierCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PIP_MMS_IMPORT_MASTER.SUPPLIER_CODE
	 * 
	 * @param supplierCode
	 *            the value for PIP_MMS_IMPORT_MASTER.SUPPLIER_CODE
	 * 
	 * @mbggenerated Sat Sep 06 10:21:13 CST 2014
	 */
	public void setSupplierCode(String supplierCode) {
		this.supplierCode = supplierCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PIP_MMS_IMPORT_MASTER.IMPORT_STATE
	 * 
	 * @return the value of PIP_MMS_IMPORT_MASTER.IMPORT_STATE
	 * 
	 * @mbggenerated Sat Sep 06 10:21:13 CST 2014
	 */
	public Short getImportState() {
		return importState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PIP_MMS_IMPORT_MASTER.IMPORT_STATE
	 * 
	 * @param importState
	 *            the value for PIP_MMS_IMPORT_MASTER.IMPORT_STATE
	 * 
	 * @mbggenerated Sat Sep 06 10:21:13 CST 2014
	 */
	public void setImportState(Short importState) {
		this.importState = importState;
	}

	public String getLccName() {
		return lccName;
	}

	public void setLccName(String lccName) {
		this.lccName = lccName;
	}

}