package com.bdcor.pip.web.material.supp.domain;

import java.util.Date;

public class MaterUser{
	
	
	private String lccCode;
	private String lccName;
	private String stockCode;
	
	
    public String getLccCode() {
		return lccCode;
	}

	public void setLccCode(String lccCode) {
		this.lccCode = lccCode;
	}

	public String getLccName() {
		return lccName;
	}

	public void setLccName(String lccName) {
		this.lccName = lccName;
	}
	
	

	public String getStockCode() {
		return stockCode;
	}

	public void setStockCode(String stockCode) {
		this.stockCode = stockCode;
	}



	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIP_MMS_MATERL_USER.PROJECT_ID
     *
     * @mbggenerated Sat Oct 11 15:30:37 CST 2014
     */
    private String projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIP_MMS_MATERL_USER.USER_CODE
     *
     * @mbggenerated Sat Oct 11 15:30:37 CST 2014
     */
    private String userCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIP_MMS_MATERL_USER.PROJECT_ID
     *
     * @return the value of PIP_MMS_MATERL_USER.PROJECT_ID
     *
     * @mbggenerated Sat Oct 11 15:30:37 CST 2014
     */
    public String getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIP_MMS_MATERL_USER.PROJECT_ID
     *
     * @param projectId the value for PIP_MMS_MATERL_USER.PROJECT_ID
     *
     * @mbggenerated Sat Oct 11 15:30:37 CST 2014
     */
    public void setProjectId(String projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIP_MMS_MATERL_USER.USER_CODE
     *
     * @return the value of PIP_MMS_MATERL_USER.USER_CODE
     *
     * @mbggenerated Sat Oct 11 15:30:37 CST 2014
     */
    public String getUserCode() {
        return userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIP_MMS_MATERL_USER.USER_CODE
     *
     * @param userCode the value for PIP_MMS_MATERL_USER.USER_CODE
     *
     * @mbggenerated Sat Oct 11 15:30:37 CST 2014
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIP_MMS_MATERL_USER.USER_NAME
     *
     * @mbggenerated Sat Oct 11 15:30:37 CST 2014
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIP_MMS_MATERL_USER.HELP_CODE
     *
     * @mbggenerated Sat Oct 11 15:30:37 CST 2014
     */
    private String helpCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIP_MMS_MATERL_USER.CREATE_DATE
     *
     * @mbggenerated Sat Oct 11 15:30:37 CST 2014
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIP_MMS_MATERL_USER.CREATE_BY
     *
     * @mbggenerated Sat Oct 11 15:30:37 CST 2014
     */
    private String createBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIP_MMS_MATERL_USER.USER_NAME
     *
     * @return the value of PIP_MMS_MATERL_USER.USER_NAME
     *
     * @mbggenerated Sat Oct 11 15:30:37 CST 2014
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIP_MMS_MATERL_USER.USER_NAME
     *
     * @param userName the value for PIP_MMS_MATERL_USER.USER_NAME
     *
     * @mbggenerated Sat Oct 11 15:30:37 CST 2014
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIP_MMS_MATERL_USER.HELP_CODE
     *
     * @return the value of PIP_MMS_MATERL_USER.HELP_CODE
     *
     * @mbggenerated Sat Oct 11 15:30:37 CST 2014
     */
    public String getHelpCode() {
        return helpCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIP_MMS_MATERL_USER.HELP_CODE
     *
     * @param helpCode the value for PIP_MMS_MATERL_USER.HELP_CODE
     *
     * @mbggenerated Sat Oct 11 15:30:37 CST 2014
     */
    public void setHelpCode(String helpCode) {
        this.helpCode = helpCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIP_MMS_MATERL_USER.CREATE_DATE
     *
     * @return the value of PIP_MMS_MATERL_USER.CREATE_DATE
     *
     * @mbggenerated Sat Oct 11 15:30:37 CST 2014
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIP_MMS_MATERL_USER.CREATE_DATE
     *
     * @param createDate the value for PIP_MMS_MATERL_USER.CREATE_DATE
     *
     * @mbggenerated Sat Oct 11 15:30:37 CST 2014
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIP_MMS_MATERL_USER.CREATE_BY
     *
     * @return the value of PIP_MMS_MATERL_USER.CREATE_BY
     *
     * @mbggenerated Sat Oct 11 15:30:37 CST 2014
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIP_MMS_MATERL_USER.CREATE_BY
     *
     * @param createBy the value for PIP_MMS_MATERL_USER.CREATE_BY
     *
     * @mbggenerated Sat Oct 11 15:30:37 CST 2014
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }
}