package com.bdcor.pip.web.material.supp.domain;

import java.math.BigDecimal;
import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.format.annotation.NumberFormat;
import org.springframework.format.annotation.NumberFormat.Style;

import com.bdcor.pip.client.tools.DateUtils;
import com.bdcor.pip.core.utils.DateUtil;

import oracle.net.aso.r;

public class MaterExportDetail {
	private String supplierName;
	private String className;// 物质类别
	private String materlName;// 物质名称
	private String type;// 1新增 2修改
	private String stockCode;// 库房编码
	private String exportLccCode; // 目标单位
	private String exportStockCode; // 目标库房
	private String periodValidityStr;
	@DateTimeFormat(pattern="yyyy-MM-dd")
	private Date exportDate;
	private String exportLccName;
	@DateTimeFormat(pattern="yyyy-MM-dd")
	private Date orderDate;
	
	public Date getExportDate()
	{
		return exportDate;
	}
	public void setExportDate(Date exportDate)
	{
		this.exportDate = exportDate;
	}
	public String getExportLccName()
	{
		return exportLccName;
	}
	public void setExportLccName(String exportLccName)
	{
		this.exportLccName = exportLccName;
	}
	public Date getOrderDate()
	{
		return orderDate;
	}
	public void setOrderDate(Date orderDate)
	{
		this.orderDate = orderDate;
	}

	private String storeUnit; //库存单位
	
	public void setStoreUnit(String storeUnit) {
		this.storeUnit = storeUnit;
	}
	public String getStoreUnit() {
		return storeUnit;
	}

	/**
	 * exportLccCode.
	 * 
	 * @param exportLccCode
	 *            the exportLccCode to set
	 */
	public void setExportLccCode(String exportLccCode) {
		this.exportLccCode = exportLccCode;
	}

	/**
	 * exportLccCode.
	 * 
	 * @return the exportLccCode
	 */
	public String getExportLccCode() {
		return exportLccCode;
	}

	/**
	 * exportStockCode.
	 * 
	 * @param exportStockCode
	 *            the exportStockCode to set
	 */
	public void setExportStockCode(String exportStockCode) {
		this.exportStockCode = exportStockCode;
	}

	/**
	 * exportStockCode.
	 * 
	 * @return the exportStockCode
	 */
	public String getExportStockCode() {
		return exportStockCode;
	}

	public String getSupplierName() {
		return supplierName;
	}

	public void setSupplierName(String supplierName) {
		this.supplierName = supplierName;
	}

	public String getClassName() {
		return className;
	}

	public void setClassName(String className) {
		this.className = className;
	}

	public String getMaterlName() {
		return materlName;
	}

	public void setMaterlName(String materlName) {
		this.materlName = materlName;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getStockCode() {
		return stockCode;
	}

	public void setStockCode(String stockCode) {
		this.stockCode = stockCode;
	}

	public String getPeriodValidityStr() {
		return DateUtil.formatDate(this.getPeriodValidity());
	}

	public void setPeriodValidityStr(String periodValidityStr) {
		this.periodValidityStr = periodValidityStr;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PIP_MMS_EXPORT_DETAIL.ID
	 * 
	 * @mbggenerated Thu Sep 11 19:29:49 CST 2014
	 */
	private Long id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PIP_MMS_EXPORT_DETAIL.PROJECT_ID
	 * 
	 * @mbggenerated Thu Sep 11 19:29:49 CST 2014
	 */
	private String projectId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PIP_MMS_EXPORT_DETAIL.EXORDER_NO
	 * 
	 * @mbggenerated Thu Sep 11 19:29:49 CST 2014
	 */
	private String exorderNo;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PIP_MMS_EXPORT_DETAIL.MATERLINFO_CODE
	 * 
	 * @mbggenerated Thu Sep 11 19:29:49 CST 2014
	 */
	private String materlinfoCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PIP_MMS_EXPORT_DETAIL.MATERL_BATCH
	 * 
	 * @mbggenerated Thu Sep 11 19:29:49 CST 2014
	 */
	private String materlBatch;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PIP_MMS_EXPORT_DETAIL.MATERL_PRICE
	 * 
	 * @mbggenerated Thu Sep 11 19:29:49 CST 2014
	 */
	@NumberFormat(style = Style.CURRENCY)
	private BigDecimal materlPrice;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PIP_MMS_EXPORT_DETAIL.WHOLESALE_PRICE
	 * 
	 * @mbggenerated Thu Sep 11 19:29:49 CST 2014
	 */
	@NumberFormat(style = Style.CURRENCY)
	private BigDecimal wholesalePrice;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PIP_MMS_EXPORT_DETAIL.EXPORT_UNIT
	 * 
	 * @mbggenerated Thu Sep 11 19:29:49 CST 2014
	 */
	private String exportUnit;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PIP_MMS_EXPORT_DETAIL.EXPORT_AMOUNT
	 * 
	 * @mbggenerated Thu Sep 11 19:29:49 CST 2014
	 */
	private Long exportAmount;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PIP_MMS_EXPORT_DETAIL.PERIOD_VALIDITY
	 * 
	 * @mbggenerated Thu Sep 11 19:29:49 CST 2014
	 */
	@DateTimeFormat(pattern = "yyyy-MM-dd")
	private Date periodValidity;
	

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PIP_MMS_EXPORT_DETAIL.SUPPLIER_CODE
	 * 
	 * @mbggenerated Thu Sep 11 19:29:49 CST 2014
	 */
	private String supplierCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PIP_MMS_EXPORT_DETAIL.CREATE_DATE
	 * 
	 * @mbggenerated Thu Sep 11 19:29:49 CST 2014
	 */
	@DateTimeFormat(pattern = "yyyy-MM-dd")
	private Date createDate;
	
	private String createDateStr ; 
	public String getCreateDateStr() {
		return DateUtils.fromatDateTime("yyyy-MM-dd", getCreateDate());
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PIP_MMS_EXPORT_DETAIL.CREATE_BY
	 * 
	 * @mbggenerated Thu Sep 11 19:29:49 CST 2014
	 */
	private String createBy;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PIP_MMS_EXPORT_DETAIL.ARCHIVES_NO
	 * 
	 * @mbggenerated Thu Sep 11 19:29:49 CST 2014
	 */
	private String archivesNo;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PIP_MMS_EXPORT_DETAIL.CLASS_CODE
	 * 
	 * @mbggenerated Thu Sep 11 19:29:49 CST 2014
	 */
	private String classCode;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PIP_MMS_EXPORT_DETAIL.ID
	 * 
	 * @return the value of PIP_MMS_EXPORT_DETAIL.ID
	 * 
	 * @mbggenerated Thu Sep 11 19:29:49 CST 2014
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PIP_MMS_EXPORT_DETAIL.ID
	 * 
	 * @param id
	 *            the value for PIP_MMS_EXPORT_DETAIL.ID
	 * 
	 * @mbggenerated Thu Sep 11 19:29:49 CST 2014
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PIP_MMS_EXPORT_DETAIL.PROJECT_ID
	 * 
	 * @return the value of PIP_MMS_EXPORT_DETAIL.PROJECT_ID
	 * 
	 * @mbggenerated Thu Sep 11 19:29:49 CST 2014
	 */
	public String getProjectId() {
		return projectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PIP_MMS_EXPORT_DETAIL.PROJECT_ID
	 * 
	 * @param projectId
	 *            the value for PIP_MMS_EXPORT_DETAIL.PROJECT_ID
	 * 
	 * @mbggenerated Thu Sep 11 19:29:49 CST 2014
	 */
	public void setProjectId(String projectId) {
		this.projectId = projectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PIP_MMS_EXPORT_DETAIL.EXORDER_NO
	 * 
	 * @return the value of PIP_MMS_EXPORT_DETAIL.EXORDER_NO
	 * 
	 * @mbggenerated Thu Sep 11 19:29:49 CST 2014
	 */
	public String getExorderNo() {
		return exorderNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PIP_MMS_EXPORT_DETAIL.EXORDER_NO
	 * 
	 * @param exorderNo
	 *            the value for PIP_MMS_EXPORT_DETAIL.EXORDER_NO
	 * 
	 * @mbggenerated Thu Sep 11 19:29:49 CST 2014
	 */
	public void setExorderNo(String exorderNo) {
		this.exorderNo = exorderNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PIP_MMS_EXPORT_DETAIL.MATERLINFO_CODE
	 * 
	 * @return the value of PIP_MMS_EXPORT_DETAIL.MATERLINFO_CODE
	 * 
	 * @mbggenerated Thu Sep 11 19:29:49 CST 2014
	 */
	public String getMaterlinfoCode() {
		return materlinfoCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PIP_MMS_EXPORT_DETAIL.MATERLINFO_CODE
	 * 
	 * @param materlinfoCode
	 *            the value for PIP_MMS_EXPORT_DETAIL.MATERLINFO_CODE
	 * 
	 * @mbggenerated Thu Sep 11 19:29:49 CST 2014
	 */
	public void setMaterlinfoCode(String materlinfoCode) {
		this.materlinfoCode = materlinfoCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PIP_MMS_EXPORT_DETAIL.MATERL_BATCH
	 * 
	 * @return the value of PIP_MMS_EXPORT_DETAIL.MATERL_BATCH
	 * 
	 * @mbggenerated Thu Sep 11 19:29:49 CST 2014
	 */
	public String getMaterlBatch() {
		return materlBatch;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PIP_MMS_EXPORT_DETAIL.MATERL_BATCH
	 * 
	 * @param materlBatch
	 *            the value for PIP_MMS_EXPORT_DETAIL.MATERL_BATCH
	 * 
	 * @mbggenerated Thu Sep 11 19:29:49 CST 2014
	 */
	public void setMaterlBatch(String materlBatch) {
		this.materlBatch = materlBatch;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PIP_MMS_EXPORT_DETAIL.MATERL_PRICE
	 * 
	 * @return the value of PIP_MMS_EXPORT_DETAIL.MATERL_PRICE
	 * 
	 * @mbggenerated Thu Sep 11 19:29:49 CST 2014
	 */
	public BigDecimal getMaterlPrice() {
		return materlPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PIP_MMS_EXPORT_DETAIL.MATERL_PRICE
	 * 
	 * @param materlPrice
	 *            the value for PIP_MMS_EXPORT_DETAIL.MATERL_PRICE
	 * 
	 * @mbggenerated Thu Sep 11 19:29:49 CST 2014
	 */
	public void setMaterlPrice(BigDecimal materlPrice) {
		this.materlPrice = materlPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PIP_MMS_EXPORT_DETAIL.WHOLESALE_PRICE
	 * 
	 * @return the value of PIP_MMS_EXPORT_DETAIL.WHOLESALE_PRICE
	 * 
	 * @mbggenerated Thu Sep 11 19:29:49 CST 2014
	 */
	public BigDecimal getWholesalePrice() {
		return wholesalePrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PIP_MMS_EXPORT_DETAIL.WHOLESALE_PRICE
	 * 
	 * @param wholesalePrice
	 *            the value for PIP_MMS_EXPORT_DETAIL.WHOLESALE_PRICE
	 * 
	 * @mbggenerated Thu Sep 11 19:29:49 CST 2014
	 */
	public void setWholesalePrice(BigDecimal wholesalePrice) {
		this.wholesalePrice = wholesalePrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PIP_MMS_EXPORT_DETAIL.EXPORT_UNIT
	 * 
	 * @return the value of PIP_MMS_EXPORT_DETAIL.EXPORT_UNIT
	 * 
	 * @mbggenerated Thu Sep 11 19:29:49 CST 2014
	 */
	public String getExportUnit() {
		return exportUnit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PIP_MMS_EXPORT_DETAIL.EXPORT_UNIT
	 * 
	 * @param exportUnit
	 *            the value for PIP_MMS_EXPORT_DETAIL.EXPORT_UNIT
	 * 
	 * @mbggenerated Thu Sep 11 19:29:49 CST 2014
	 */
	public void setExportUnit(String exportUnit) {
		this.exportUnit = exportUnit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PIP_MMS_EXPORT_DETAIL.EXPORT_AMOUNT
	 * 
	 * @return the value of PIP_MMS_EXPORT_DETAIL.EXPORT_AMOUNT
	 * 
	 * @mbggenerated Thu Sep 11 19:29:49 CST 2014
	 */
	public Long getExportAmount() {
		return exportAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PIP_MMS_EXPORT_DETAIL.EXPORT_AMOUNT
	 * 
	 * @param exportAmount
	 *            the value for PIP_MMS_EXPORT_DETAIL.EXPORT_AMOUNT
	 * 
	 * @mbggenerated Thu Sep 11 19:29:49 CST 2014
	 */
	public void setExportAmount(Long exportAmount) {
		this.exportAmount = exportAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PIP_MMS_EXPORT_DETAIL.PERIOD_VALIDITY
	 * 
	 * @return the value of PIP_MMS_EXPORT_DETAIL.PERIOD_VALIDITY
	 * 
	 * @mbggenerated Thu Sep 11 19:29:49 CST 2014
	 */
	public Date getPeriodValidity() {
		return periodValidity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PIP_MMS_EXPORT_DETAIL.PERIOD_VALIDITY
	 * 
	 * @param periodValidity
	 *            the value for PIP_MMS_EXPORT_DETAIL.PERIOD_VALIDITY
	 * 
	 * @mbggenerated Thu Sep 11 19:29:49 CST 2014
	 */
	public void setPeriodValidity(Date periodValidity) {
		this.periodValidity = periodValidity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PIP_MMS_EXPORT_DETAIL.SUPPLIER_CODE
	 * 
	 * @return the value of PIP_MMS_EXPORT_DETAIL.SUPPLIER_CODE
	 * 
	 * @mbggenerated Thu Sep 11 19:29:49 CST 2014
	 */
	public String getSupplierCode() {
		return supplierCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PIP_MMS_EXPORT_DETAIL.SUPPLIER_CODE
	 * 
	 * @param supplierCode
	 *            the value for PIP_MMS_EXPORT_DETAIL.SUPPLIER_CODE
	 * 
	 * @mbggenerated Thu Sep 11 19:29:49 CST 2014
	 */
	public void setSupplierCode(String supplierCode) {
		this.supplierCode = supplierCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PIP_MMS_EXPORT_DETAIL.CREATE_DATE
	 * 
	 * @return the value of PIP_MMS_EXPORT_DETAIL.CREATE_DATE
	 * 
	 * @mbggenerated Thu Sep 11 19:29:49 CST 2014
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PIP_MMS_EXPORT_DETAIL.CREATE_DATE
	 * 
	 * @param createDate
	 *            the value for PIP_MMS_EXPORT_DETAIL.CREATE_DATE
	 * 
	 * @mbggenerated Thu Sep 11 19:29:49 CST 2014
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PIP_MMS_EXPORT_DETAIL.CREATE_BY
	 * 
	 * @return the value of PIP_MMS_EXPORT_DETAIL.CREATE_BY
	 * 
	 * @mbggenerated Thu Sep 11 19:29:49 CST 2014
	 */
	public String getCreateBy() {
		return createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PIP_MMS_EXPORT_DETAIL.CREATE_BY
	 * 
	 * @param createBy
	 *            the value for PIP_MMS_EXPORT_DETAIL.CREATE_BY
	 * 
	 * @mbggenerated Thu Sep 11 19:29:49 CST 2014
	 */
	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PIP_MMS_EXPORT_DETAIL.ARCHIVES_NO
	 * 
	 * @return the value of PIP_MMS_EXPORT_DETAIL.ARCHIVES_NO
	 * 
	 * @mbggenerated Thu Sep 11 19:29:49 CST 2014
	 */
	public String getArchivesNo() {
		return archivesNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PIP_MMS_EXPORT_DETAIL.ARCHIVES_NO
	 * 
	 * @param archivesNo
	 *            the value for PIP_MMS_EXPORT_DETAIL.ARCHIVES_NO
	 * 
	 * @mbggenerated Thu Sep 11 19:29:49 CST 2014
	 */
	public void setArchivesNo(String archivesNo) {
		this.archivesNo = archivesNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PIP_MMS_EXPORT_DETAIL.CLASS_CODE
	 * 
	 * @return the value of PIP_MMS_EXPORT_DETAIL.CLASS_CODE
	 * 
	 * @mbggenerated Thu Sep 11 19:29:49 CST 2014
	 */
	public String getClassCode() {
		return classCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PIP_MMS_EXPORT_DETAIL.CLASS_CODE
	 * 
	 * @param classCode
	 *            the value for PIP_MMS_EXPORT_DETAIL.CLASS_CODE
	 * 
	 * @mbggenerated Thu Sep 11 19:29:49 CST 2014
	 */
	public void setClassCode(String classCode) {
		this.classCode = classCode;
	}
}