package com.bdcor.pip.web.data.domain;

public class UqsAnswerDropKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIP_UQS_ANSWER_DROP.OPTION_ID
     *
     * @mbggenerated
     */
    private String optionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIP_UQS_ANSWER_DROP.PATIENT_ID
     *
     * @mbggenerated
     */
    private String patientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIP_UQS_ANSWER_DROP.PROJECT_ID
     *
     * @mbggenerated
     */
    private String projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIP_UQS_ANSWER_DROP.QUESTIONNAIRE_ID
     *
     * @mbggenerated
     */
    private String questionnaireId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIP_UQS_ANSWER_DROP.QUESTIONSET_ID
     *
     * @mbggenerated
     */
    private String questionsetId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIP_UQS_ANSWER_DROP.QUESTION_ID
     *
     * @mbggenerated
     */
    private String questionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIP_UQS_ANSWER_DROP.OPTION_ID
     *
     * @return the value of PIP_UQS_ANSWER_DROP.OPTION_ID
     *
     * @mbggenerated
     */
    public String getOptionId() {
        return optionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIP_UQS_ANSWER_DROP.OPTION_ID
     *
     * @param optionId the value for PIP_UQS_ANSWER_DROP.OPTION_ID
     *
     * @mbggenerated
     */
    public void setOptionId(String optionId) {
        this.optionId = optionId == null ? null : optionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIP_UQS_ANSWER_DROP.PATIENT_ID
     *
     * @return the value of PIP_UQS_ANSWER_DROP.PATIENT_ID
     *
     * @mbggenerated
     */
    public String getPatientId() {
        return patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIP_UQS_ANSWER_DROP.PATIENT_ID
     *
     * @param patientId the value for PIP_UQS_ANSWER_DROP.PATIENT_ID
     *
     * @mbggenerated
     */
    public void setPatientId(String patientId) {
        this.patientId = patientId == null ? null : patientId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIP_UQS_ANSWER_DROP.PROJECT_ID
     *
     * @return the value of PIP_UQS_ANSWER_DROP.PROJECT_ID
     *
     * @mbggenerated
     */
    public String getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIP_UQS_ANSWER_DROP.PROJECT_ID
     *
     * @param projectId the value for PIP_UQS_ANSWER_DROP.PROJECT_ID
     *
     * @mbggenerated
     */
    public void setProjectId(String projectId) {
        this.projectId = projectId == null ? null : projectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIP_UQS_ANSWER_DROP.QUESTIONNAIRE_ID
     *
     * @return the value of PIP_UQS_ANSWER_DROP.QUESTIONNAIRE_ID
     *
     * @mbggenerated
     */
    public String getQuestionnaireId() {
        return questionnaireId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIP_UQS_ANSWER_DROP.QUESTIONNAIRE_ID
     *
     * @param questionnaireId the value for PIP_UQS_ANSWER_DROP.QUESTIONNAIRE_ID
     *
     * @mbggenerated
     */
    public void setQuestionnaireId(String questionnaireId) {
        this.questionnaireId = questionnaireId == null ? null : questionnaireId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIP_UQS_ANSWER_DROP.QUESTIONSET_ID
     *
     * @return the value of PIP_UQS_ANSWER_DROP.QUESTIONSET_ID
     *
     * @mbggenerated
     */
    public String getQuestionsetId() {
        return questionsetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIP_UQS_ANSWER_DROP.QUESTIONSET_ID
     *
     * @param questionsetId the value for PIP_UQS_ANSWER_DROP.QUESTIONSET_ID
     *
     * @mbggenerated
     */
    public void setQuestionsetId(String questionsetId) {
        this.questionsetId = questionsetId == null ? null : questionsetId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIP_UQS_ANSWER_DROP.QUESTION_ID
     *
     * @return the value of PIP_UQS_ANSWER_DROP.QUESTION_ID
     *
     * @mbggenerated
     */
    public String getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIP_UQS_ANSWER_DROP.QUESTION_ID
     *
     * @param questionId the value for PIP_UQS_ANSWER_DROP.QUESTION_ID
     *
     * @mbggenerated
     */
    public void setQuestionId(String questionId) {
        this.questionId = questionId == null ? null : questionId.trim();
    }
}