package com.bdcor.pip.web.material.supp.domain;

import java.util.Date;

public class MaterStorehouse {
	
	private String lccName;
	
    public String getLccName() {
		return lccName;
	}

	public void setLccName(String lccName) {
		this.lccName = lccName;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIP_MMS_STOREHOUSE.LCC_CODE
     *
     * @mbggenerated Sat Oct 11 11:18:21 CST 2014
     */
    private String lccCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIP_MMS_STOREHOUSE.PROJECT_ID
     *
     * @mbggenerated Sat Oct 11 11:18:21 CST 2014
     */
    private String projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIP_MMS_STOREHOUSE.STOCK_CODE
     *
     * @mbggenerated Sat Oct 11 11:18:21 CST 2014
     */
    private String stockCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIP_MMS_STOREHOUSE.LCC_CODE
     *
     * @return the value of PIP_MMS_STOREHOUSE.LCC_CODE
     *
     * @mbggenerated Sat Oct 11 11:18:21 CST 2014
     */
    public String getLccCode() {
        return lccCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIP_MMS_STOREHOUSE.LCC_CODE
     *
     * @param lccCode the value for PIP_MMS_STOREHOUSE.LCC_CODE
     *
     * @mbggenerated Sat Oct 11 11:18:21 CST 2014
     */
    public void setLccCode(String lccCode) {
        this.lccCode = lccCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIP_MMS_STOREHOUSE.PROJECT_ID
     *
     * @return the value of PIP_MMS_STOREHOUSE.PROJECT_ID
     *
     * @mbggenerated Sat Oct 11 11:18:21 CST 2014
     */
    public String getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIP_MMS_STOREHOUSE.PROJECT_ID
     *
     * @param projectId the value for PIP_MMS_STOREHOUSE.PROJECT_ID
     *
     * @mbggenerated Sat Oct 11 11:18:21 CST 2014
     */
    public void setProjectId(String projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIP_MMS_STOREHOUSE.STOCK_CODE
     *
     * @return the value of PIP_MMS_STOREHOUSE.STOCK_CODE
     *
     * @mbggenerated Sat Oct 11 11:18:21 CST 2014
     */
    public String getStockCode() {
        return stockCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIP_MMS_STOREHOUSE.STOCK_CODE
     *
     * @param stockCode the value for PIP_MMS_STOREHOUSE.STOCK_CODE
     *
     * @mbggenerated Sat Oct 11 11:18:21 CST 2014
     */
    public void setStockCode(String stockCode) {
        this.stockCode = stockCode;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIP_MMS_STOREHOUSE.STOCK_NAME
     *
     * @mbggenerated Sat Oct 11 11:18:21 CST 2014
     */
    private String stockName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIP_MMS_STOREHOUSE.HELP_CODE
     *
     * @mbggenerated Sat Oct 11 11:18:21 CST 2014
     */
    private String helpCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIP_MMS_STOREHOUSE.CREATE_DATE
     *
     * @mbggenerated Sat Oct 11 11:18:21 CST 2014
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIP_MMS_STOREHOUSE.CREATE_BY
     *
     * @mbggenerated Sat Oct 11 11:18:21 CST 2014
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIP_MMS_STOREHOUSE.IS_REMOVED
     *
     * @mbggenerated Sat Oct 11 11:18:21 CST 2014
     */
    private String isRemoved;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIP_MMS_STOREHOUSE.REMARK
     *
     * @mbggenerated Sat Oct 11 11:18:21 CST 2014
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIP_MMS_STOREHOUSE.STOCK_NAME
     *
     * @return the value of PIP_MMS_STOREHOUSE.STOCK_NAME
     *
     * @mbggenerated Sat Oct 11 11:18:21 CST 2014
     */
    public String getStockName() {
        return stockName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIP_MMS_STOREHOUSE.STOCK_NAME
     *
     * @param stockName the value for PIP_MMS_STOREHOUSE.STOCK_NAME
     *
     * @mbggenerated Sat Oct 11 11:18:21 CST 2014
     */
    public void setStockName(String stockName) {
        this.stockName = stockName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIP_MMS_STOREHOUSE.HELP_CODE
     *
     * @return the value of PIP_MMS_STOREHOUSE.HELP_CODE
     *
     * @mbggenerated Sat Oct 11 11:18:21 CST 2014
     */
    public String getHelpCode() {
        return helpCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIP_MMS_STOREHOUSE.HELP_CODE
     *
     * @param helpCode the value for PIP_MMS_STOREHOUSE.HELP_CODE
     *
     * @mbggenerated Sat Oct 11 11:18:21 CST 2014
     */
    public void setHelpCode(String helpCode) {
        this.helpCode = helpCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIP_MMS_STOREHOUSE.CREATE_DATE
     *
     * @return the value of PIP_MMS_STOREHOUSE.CREATE_DATE
     *
     * @mbggenerated Sat Oct 11 11:18:21 CST 2014
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIP_MMS_STOREHOUSE.CREATE_DATE
     *
     * @param createDate the value for PIP_MMS_STOREHOUSE.CREATE_DATE
     *
     * @mbggenerated Sat Oct 11 11:18:21 CST 2014
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIP_MMS_STOREHOUSE.CREATE_BY
     *
     * @return the value of PIP_MMS_STOREHOUSE.CREATE_BY
     *
     * @mbggenerated Sat Oct 11 11:18:21 CST 2014
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIP_MMS_STOREHOUSE.CREATE_BY
     *
     * @param createBy the value for PIP_MMS_STOREHOUSE.CREATE_BY
     *
     * @mbggenerated Sat Oct 11 11:18:21 CST 2014
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIP_MMS_STOREHOUSE.IS_REMOVED
     *
     * @return the value of PIP_MMS_STOREHOUSE.IS_REMOVED
     *
     * @mbggenerated Sat Oct 11 11:18:21 CST 2014
     */
    public String getIsRemoved() {
        return isRemoved;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIP_MMS_STOREHOUSE.IS_REMOVED
     *
     * @param isRemoved the value for PIP_MMS_STOREHOUSE.IS_REMOVED
     *
     * @mbggenerated Sat Oct 11 11:18:21 CST 2014
     */
    public void setIsRemoved(String isRemoved) {
        this.isRemoved = isRemoved;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIP_MMS_STOREHOUSE.REMARK
     *
     * @return the value of PIP_MMS_STOREHOUSE.REMARK
     *
     * @mbggenerated Sat Oct 11 11:18:21 CST 2014
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIP_MMS_STOREHOUSE.REMARK
     *
     * @param remark the value for PIP_MMS_STOREHOUSE.REMARK
     *
     * @mbggenerated Sat Oct 11 11:18:21 CST 2014
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }


}
