package com.bdcor.pip.web.data.dao;

import com.bdcor.pip.core.persistence.MyBatisRepository;
import com.bdcor.pip.web.data.domain.PipCommPatientQc;
import com.bdcor.pip.web.data.domain.PipCommPatientQcExample;
import com.bdcor.pip.web.data.domain.PipCommPatientQcKey;

import java.util.List;

import org.apache.ibatis.annotations.Param;

@MyBatisRepository
public interface PipCommPatientQcMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PIP_COMM_PATIENT_QC
	 * @mbggenerated
	 */
	int countByExample(PipCommPatientQcExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PIP_COMM_PATIENT_QC
	 * @mbggenerated
	 */
	int deleteByExample(PipCommPatientQcExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PIP_COMM_PATIENT_QC
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(PipCommPatientQcKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PIP_COMM_PATIENT_QC
	 * @mbggenerated
	 */
	int insert(PipCommPatientQc record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PIP_COMM_PATIENT_QC
	 * @mbggenerated
	 */
	int insertSelective(PipCommPatientQc record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PIP_COMM_PATIENT_QC
	 * @mbggenerated
	 */
	List<PipCommPatientQc> selectByExample(PipCommPatientQcExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PIP_COMM_PATIENT_QC
	 * @mbggenerated
	 */
	PipCommPatientQc selectByPrimaryKey(PipCommPatientQcKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PIP_COMM_PATIENT_QC
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") PipCommPatientQc record,
			@Param("example") PipCommPatientQcExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PIP_COMM_PATIENT_QC
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") PipCommPatientQc record,
			@Param("example") PipCommPatientQcExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PIP_COMM_PATIENT_QC
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(PipCommPatientQc record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PIP_COMM_PATIENT_QC
	 * @mbggenerated
	 */
	int updateByPrimaryKey(PipCommPatientQc record);
}