package com.bdcor.pip.web.data.domain;

import java.util.Date;

public class UqsAttribute extends UqsAttributeKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIP_UQS_ATTRIBUTE.CREATE_BY
     *
     * @mbggenerated
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIP_UQS_ATTRIBUTE.CREATE_DATE
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIP_UQS_ATTRIBUTE.UPDATE_BY
     *
     * @mbggenerated
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIP_UQS_ATTRIBUTE.UPDATE_DATE
     *
     * @mbggenerated
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIP_UQS_ATTRIBUTE.IS_REMOVED
     *
     * @mbggenerated
     */
    private Short isRemoved;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIP_UQS_ATTRIBUTE.REMARK
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIP_UQS_ATTRIBUTE.VALIDATEOBJECTTYPE
     *
     * @mbggenerated
     */
    private String validateobjecttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIP_UQS_ATTRIBUTE.VALIDATETYPE
     *
     * @mbggenerated
     */
    private String validatetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIP_UQS_ATTRIBUTE.TYPE
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIP_UQS_ATTRIBUTE.VALUE
     *
     * @mbggenerated
     */
    private String value;
    
    private String version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIP_UQS_ATTRIBUTE.CREATE_BY
     *
     * @return the value of PIP_UQS_ATTRIBUTE.CREATE_BY
     *
     * @mbggenerated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIP_UQS_ATTRIBUTE.CREATE_BY
     *
     * @param createBy the value for PIP_UQS_ATTRIBUTE.CREATE_BY
     *
     * @mbggenerated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIP_UQS_ATTRIBUTE.CREATE_DATE
     *
     * @return the value of PIP_UQS_ATTRIBUTE.CREATE_DATE
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIP_UQS_ATTRIBUTE.CREATE_DATE
     *
     * @param createDate the value for PIP_UQS_ATTRIBUTE.CREATE_DATE
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIP_UQS_ATTRIBUTE.UPDATE_BY
     *
     * @return the value of PIP_UQS_ATTRIBUTE.UPDATE_BY
     *
     * @mbggenerated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIP_UQS_ATTRIBUTE.UPDATE_BY
     *
     * @param updateBy the value for PIP_UQS_ATTRIBUTE.UPDATE_BY
     *
     * @mbggenerated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIP_UQS_ATTRIBUTE.UPDATE_DATE
     *
     * @return the value of PIP_UQS_ATTRIBUTE.UPDATE_DATE
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIP_UQS_ATTRIBUTE.UPDATE_DATE
     *
     * @param updateDate the value for PIP_UQS_ATTRIBUTE.UPDATE_DATE
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIP_UQS_ATTRIBUTE.IS_REMOVED
     *
     * @return the value of PIP_UQS_ATTRIBUTE.IS_REMOVED
     *
     * @mbggenerated
     */
    public Short getIsRemoved() {
        return isRemoved;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIP_UQS_ATTRIBUTE.IS_REMOVED
     *
     * @param isRemoved the value for PIP_UQS_ATTRIBUTE.IS_REMOVED
     *
     * @mbggenerated
     */
    public void setIsRemoved(Short isRemoved) {
        this.isRemoved = isRemoved;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIP_UQS_ATTRIBUTE.REMARK
     *
     * @return the value of PIP_UQS_ATTRIBUTE.REMARK
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIP_UQS_ATTRIBUTE.REMARK
     *
     * @param remark the value for PIP_UQS_ATTRIBUTE.REMARK
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIP_UQS_ATTRIBUTE.VALIDATEOBJECTTYPE
     *
     * @return the value of PIP_UQS_ATTRIBUTE.VALIDATEOBJECTTYPE
     *
     * @mbggenerated
     */
    public String getValidateobjecttype() {
        return validateobjecttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIP_UQS_ATTRIBUTE.VALIDATEOBJECTTYPE
     *
     * @param validateobjecttype the value for PIP_UQS_ATTRIBUTE.VALIDATEOBJECTTYPE
     *
     * @mbggenerated
     */
    public void setValidateobjecttype(String validateobjecttype) {
        this.validateobjecttype = validateobjecttype == null ? null : validateobjecttype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIP_UQS_ATTRIBUTE.VALIDATETYPE
     *
     * @return the value of PIP_UQS_ATTRIBUTE.VALIDATETYPE
     *
     * @mbggenerated
     */
    public String getValidatetype() {
        return validatetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIP_UQS_ATTRIBUTE.VALIDATETYPE
     *
     * @param validatetype the value for PIP_UQS_ATTRIBUTE.VALIDATETYPE
     *
     * @mbggenerated
     */
    public void setValidatetype(String validatetype) {
        this.validatetype = validatetype == null ? null : validatetype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIP_UQS_ATTRIBUTE.TYPE
     *
     * @return the value of PIP_UQS_ATTRIBUTE.TYPE
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIP_UQS_ATTRIBUTE.TYPE
     *
     * @param type the value for PIP_UQS_ATTRIBUTE.TYPE
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIP_UQS_ATTRIBUTE.VALUE
     *
     * @return the value of PIP_UQS_ATTRIBUTE.VALUE
     *
     * @mbggenerated
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIP_UQS_ATTRIBUTE.VALUE
     *
     * @param value the value for PIP_UQS_ATTRIBUTE.VALUE
     *
     * @mbggenerated
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }
    
    public String toString(){
    	return this.getQuestionsetId()+"_"+this.getQuestionId()+"_"+this.getOptionId();
    }

	public String getVersion() {
		return version;
	}

	public void setVersion(String version) {
		this.version = version;
	}
    
}