package com.bdcor.pip.web.data.dao;

import org.apache.ibatis.annotations.Param;
import com.bdcor.pip.core.persistence.MyBatisRepository;
import com.bdcor.pip.web.data.domain.UqsQuestionnaire;
import com.bdcor.pip.web.data.domain.UqsQuestionnaireExample;
import com.bdcor.pip.web.data.domain.UqsQuestionnaireKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

@MyBatisRepository
public interface UqsQuestionnaireMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PIP_UQS_QUESTIONNAIRE
	 * @mbggenerated
	 */
	int countByExample(UqsQuestionnaireExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PIP_UQS_QUESTIONNAIRE
	 * @mbggenerated
	 */
	int deleteByExample(UqsQuestionnaireExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PIP_UQS_QUESTIONNAIRE
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(UqsQuestionnaireKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PIP_UQS_QUESTIONNAIRE
	 * @mbggenerated
	 */
	int insert(UqsQuestionnaire record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PIP_UQS_QUESTIONNAIRE
	 * @mbggenerated
	 */
	int insertSelective(UqsQuestionnaire record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PIP_UQS_QUESTIONNAIRE
	 * @mbggenerated
	 */
	List<UqsQuestionnaire> selectByExample(UqsQuestionnaireExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PIP_UQS_QUESTIONNAIRE
	 * @mbggenerated
	 */
	UqsQuestionnaire selectByPrimaryKey(UqsQuestionnaireKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PIP_UQS_QUESTIONNAIRE
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") UqsQuestionnaire record,
			@Param("example") UqsQuestionnaireExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PIP_UQS_QUESTIONNAIRE
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") UqsQuestionnaire record,
			@Param("example") UqsQuestionnaireExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PIP_UQS_QUESTIONNAIRE
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(UqsQuestionnaire record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PIP_UQS_QUESTIONNAIRE
	 * @mbggenerated
	 */
	int updateByPrimaryKey(UqsQuestionnaire record);
}