package com.bdcor.pip.web.material.supp.domain;

import java.math.BigDecimal;
import java.util.Date;

import com.bdcor.pip.core.utils.DateUtil;

public class MaterStore {
	private String materlName;// 物质名称
	private String helpCode;
	private String periodValidityStr;
	private String stockName;
	private String lccName;
	private String supplierName;
	private String produceDateStr;
	private Integer ratio; // 人数/ratio=出库数量
	private String combId;// pip_mms_matexport_combi_id表的id
							// 出库组合通过此id来获取具体的物资明细信息
	private String nextMeasureDateStr; // --下次计量时间

	public String getNextMeasureDateStr() {
		if (this.getNextMeasureDate() != null) {
			return DateUtil.formatDate(this.getNextMeasureDate());
		}
		return null;
	}

	public String getMaterlName() {
		return materlName;
	}

	public void setMaterlName(String materlName) {
		this.materlName = materlName;
	}

	public String getHelpCode() {
		return helpCode;
	}

	public void setHelpCode(String helpCode) {
		this.helpCode = helpCode;
	}

	public String getPeriodValidityStr() {
		if (this.getPeriodValidity() != null) {
			return DateUtil.formatDate(this.getPeriodValidity());
		}
		return null;
	}

	public void setPeriodValidityStr(String periodValidityStr) {
		this.periodValidityStr = periodValidityStr;
	}

	public String getStockName() {
		return stockName;
	}

	public void setStockName(String stockName) {
		this.stockName = stockName;
	}

	public String getLccName() {
		return lccName;
	}

	public void setLccName(String lccName) {
		this.lccName = lccName;
	}

	public String getSupplierName() {
		return supplierName;
	}

	public void setSupplierName(String supplierName) {
		this.supplierName = supplierName;
	}

	public Integer getRatio() {
		return ratio;
	}

	public void setRatio(Integer ratio) {
		this.ratio = ratio;
	}

	public String getProduceDateStr() {
		if (this.getPeriodValidity() != null) {
			return DateUtil.formatDate(this.getProduceDate());
		}
		return null;
	}

	public void setProduceDateStr(String produceDateStr) {
		this.produceDateStr = produceDateStr;
	}

	public String getCombId() {
		return combId;
	}

	public void setCombId(String combId) {
		this.combId = combId;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PIP_MMS_STORE.ID
	 * 
	 * @mbggenerated Wed Sep 10 09:47:34 CST 2014
	 */
	private Long id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PIP_MMS_STORE.PROJECT_ID
	 * 
	 * @mbggenerated Wed Sep 10 09:47:34 CST 2014
	 */
	private String projectId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PIP_MMS_STORE.LCC_CODE
	 * 
	 * @mbggenerated Wed Sep 10 09:47:34 CST 2014
	 */
	private String lccCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PIP_MMS_STORE.STOCK_CODE
	 * 
	 * @mbggenerated Wed Sep 10 09:47:34 CST 2014
	 */
	private String stockCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PIP_MMS_STORE.MATERLINFO_CODE
	 * 
	 * @mbggenerated Wed Sep 10 09:47:34 CST 2014
	 */
	private String materlinfoCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PIP_MMS_STORE.MATERL_BATCH
	 * 
	 * @mbggenerated Wed Sep 10 09:47:34 CST 2014
	 */
	private String materlBatch;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PIP_MMS_STORE.MATERL_PRICE
	 * 
	 * @mbggenerated Wed Sep 10 09:47:34 CST 2014
	 */
	private BigDecimal materlPrice;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PIP_MMS_STORE.WHOLESALE_PRICE
	 * 
	 * @mbggenerated Wed Sep 10 09:47:34 CST 2014
	 */
	private BigDecimal wholesalePrice;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PIP_MMS_STORE.STORE_AMOUNT
	 * 
	 * @mbggenerated Wed Sep 10 09:47:34 CST 2014
	 */
	private Long storeAmount;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PIP_MMS_STORE.STORE_UNIT
	 * 
	 * @mbggenerated Wed Sep 10 09:47:34 CST 2014
	 */
	private String storeUnit;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PIP_MMS_STORE.PERIOD_VALIDITY
	 * 
	 * @mbggenerated Wed Sep 10 09:47:34 CST 2014
	 */
	private Date periodValidity;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PIP_MMS_STORE.SUPPLIER_CODE
	 * 
	 * @mbggenerated Wed Sep 10 09:47:34 CST 2014
	 */
	private String supplierCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PIP_MMS_STORE.CREATE_DATE
	 * 
	 * @mbggenerated Wed Sep 10 09:47:34 CST 2014
	 */
	private Date createDate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PIP_MMS_STORE.CREATE_BY
	 * 
	 * @mbggenerated Wed Sep 10 09:47:34 CST 2014
	 */
	private String createBy;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PIP_MMS_STORE.PRODUCE_DATE
	 * 
	 * @mbggenerated Wed Sep 10 09:47:34 CST 2014
	 */
	private Date produceDate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PIP_MMS_STORE.MATERL_SPEC
	 * 
	 * @mbggenerated Wed Sep 10 09:47:34 CST 2014
	 */
	private String materlSpec;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PIP_MMS_STORE.ASSETS_STATUS
	 * 
	 * @mbggenerated Wed Sep 10 09:47:34 CST 2014
	 */
	private Short assetsStatus;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PIP_MMS_STORE.IS_MEASURE
	 * 
	 * @mbggenerated Wed Sep 10 09:47:34 CST 2014
	 */
	private Short isMeasure;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PIP_MMS_STORE.NEXT_MEASURE_DATE
	 * 
	 * @mbggenerated Wed Sep 10 09:47:34 CST 2014
	 */
	private Date nextMeasureDate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PIP_MMS_STORE.MEASURE_PERIOD
	 * 
	 * @mbggenerated Wed Sep 10 09:47:34 CST 2014
	 */
	private Long measurePeriod;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PIP_MMS_STORE.ARCHIVES_NO
	 * 
	 * @mbggenerated Wed Sep 10 09:47:34 CST 2014
	 */
	private String archivesNo;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PIP_MMS_STORE.CLASS_CODE
	 * 
	 * @mbggenerated Wed Sep 10 09:47:34 CST 2014
	 */
	private String classCode;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PIP_MMS_STORE.ID
	 * 
	 * @return the value of PIP_MMS_STORE.ID
	 * 
	 * @mbggenerated Wed Sep 10 09:47:34 CST 2014
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PIP_MMS_STORE.ID
	 * 
	 * @param id
	 *            the value for PIP_MMS_STORE.ID
	 * 
	 * @mbggenerated Wed Sep 10 09:47:34 CST 2014
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PIP_MMS_STORE.PROJECT_ID
	 * 
	 * @return the value of PIP_MMS_STORE.PROJECT_ID
	 * 
	 * @mbggenerated Wed Sep 10 09:47:34 CST 2014
	 */
	public String getProjectId() {
		return projectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PIP_MMS_STORE.PROJECT_ID
	 * 
	 * @param projectId
	 *            the value for PIP_MMS_STORE.PROJECT_ID
	 * 
	 * @mbggenerated Wed Sep 10 09:47:34 CST 2014
	 */
	public void setProjectId(String projectId) {
		this.projectId = projectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PIP_MMS_STORE.LCC_CODE
	 * 
	 * @return the value of PIP_MMS_STORE.LCC_CODE
	 * 
	 * @mbggenerated Wed Sep 10 09:47:34 CST 2014
	 */
	public String getLccCode() {
		return lccCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PIP_MMS_STORE.LCC_CODE
	 * 
	 * @param lccCode
	 *            the value for PIP_MMS_STORE.LCC_CODE
	 * 
	 * @mbggenerated Wed Sep 10 09:47:34 CST 2014
	 */
	public void setLccCode(String lccCode) {
		this.lccCode = lccCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PIP_MMS_STORE.STOCK_CODE
	 * 
	 * @return the value of PIP_MMS_STORE.STOCK_CODE
	 * 
	 * @mbggenerated Wed Sep 10 09:47:34 CST 2014
	 */
	public String getStockCode() {
		return stockCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PIP_MMS_STORE.STOCK_CODE
	 * 
	 * @param stockCode
	 *            the value for PIP_MMS_STORE.STOCK_CODE
	 * 
	 * @mbggenerated Wed Sep 10 09:47:34 CST 2014
	 */
	public void setStockCode(String stockCode) {
		this.stockCode = stockCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PIP_MMS_STORE.MATERLINFO_CODE
	 * 
	 * @return the value of PIP_MMS_STORE.MATERLINFO_CODE
	 * 
	 * @mbggenerated Wed Sep 10 09:47:34 CST 2014
	 */
	public String getMaterlinfoCode() {
		return materlinfoCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PIP_MMS_STORE.MATERLINFO_CODE
	 * 
	 * @param materlinfoCode
	 *            the value for PIP_MMS_STORE.MATERLINFO_CODE
	 * 
	 * @mbggenerated Wed Sep 10 09:47:34 CST 2014
	 */
	public void setMaterlinfoCode(String materlinfoCode) {
		this.materlinfoCode = materlinfoCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PIP_MMS_STORE.MATERL_BATCH
	 * 
	 * @return the value of PIP_MMS_STORE.MATERL_BATCH
	 * 
	 * @mbggenerated Wed Sep 10 09:47:34 CST 2014
	 */
	public String getMaterlBatch() {
		return materlBatch;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PIP_MMS_STORE.MATERL_BATCH
	 * 
	 * @param materlBatch
	 *            the value for PIP_MMS_STORE.MATERL_BATCH
	 * 
	 * @mbggenerated Wed Sep 10 09:47:34 CST 2014
	 */
	public void setMaterlBatch(String materlBatch) {
		this.materlBatch = materlBatch;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PIP_MMS_STORE.MATERL_PRICE
	 * 
	 * @return the value of PIP_MMS_STORE.MATERL_PRICE
	 * 
	 * @mbggenerated Wed Sep 10 09:47:34 CST 2014
	 */
	public BigDecimal getMaterlPrice() {
		return materlPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PIP_MMS_STORE.MATERL_PRICE
	 * 
	 * @param materlPrice
	 *            the value for PIP_MMS_STORE.MATERL_PRICE
	 * 
	 * @mbggenerated Wed Sep 10 09:47:34 CST 2014
	 */
	public void setMaterlPrice(BigDecimal materlPrice) {
		this.materlPrice = materlPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PIP_MMS_STORE.WHOLESALE_PRICE
	 * 
	 * @return the value of PIP_MMS_STORE.WHOLESALE_PRICE
	 * 
	 * @mbggenerated Wed Sep 10 09:47:34 CST 2014
	 */
	public BigDecimal getWholesalePrice() {
		return wholesalePrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PIP_MMS_STORE.WHOLESALE_PRICE
	 * 
	 * @param wholesalePrice
	 *            the value for PIP_MMS_STORE.WHOLESALE_PRICE
	 * 
	 * @mbggenerated Wed Sep 10 09:47:34 CST 2014
	 */
	public void setWholesalePrice(BigDecimal wholesalePrice) {
		this.wholesalePrice = wholesalePrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PIP_MMS_STORE.STORE_AMOUNT
	 * 
	 * @return the value of PIP_MMS_STORE.STORE_AMOUNT
	 * 
	 * @mbggenerated Wed Sep 10 09:47:34 CST 2014
	 */
	public Long getStoreAmount() {
		return storeAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PIP_MMS_STORE.STORE_AMOUNT
	 * 
	 * @param storeAmount
	 *            the value for PIP_MMS_STORE.STORE_AMOUNT
	 * 
	 * @mbggenerated Wed Sep 10 09:47:34 CST 2014
	 */
	public void setStoreAmount(Long storeAmount) {
		this.storeAmount = storeAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PIP_MMS_STORE.STORE_UNIT
	 * 
	 * @return the value of PIP_MMS_STORE.STORE_UNIT
	 * 
	 * @mbggenerated Wed Sep 10 09:47:34 CST 2014
	 */
	public String getStoreUnit() {
		return storeUnit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PIP_MMS_STORE.STORE_UNIT
	 * 
	 * @param storeUnit
	 *            the value for PIP_MMS_STORE.STORE_UNIT
	 * 
	 * @mbggenerated Wed Sep 10 09:47:34 CST 2014
	 */
	public void setStoreUnit(String storeUnit) {
		this.storeUnit = storeUnit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PIP_MMS_STORE.PERIOD_VALIDITY
	 * 
	 * @return the value of PIP_MMS_STORE.PERIOD_VALIDITY
	 * 
	 * @mbggenerated Wed Sep 10 09:47:34 CST 2014
	 */
	public Date getPeriodValidity() {
		return periodValidity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PIP_MMS_STORE.PERIOD_VALIDITY
	 * 
	 * @param periodValidity
	 *            the value for PIP_MMS_STORE.PERIOD_VALIDITY
	 * 
	 * @mbggenerated Wed Sep 10 09:47:34 CST 2014
	 */
	public void setPeriodValidity(Date periodValidity) {
		this.periodValidity = periodValidity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PIP_MMS_STORE.SUPPLIER_CODE
	 * 
	 * @return the value of PIP_MMS_STORE.SUPPLIER_CODE
	 * 
	 * @mbggenerated Wed Sep 10 09:47:34 CST 2014
	 */
	public String getSupplierCode() {
		return supplierCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PIP_MMS_STORE.SUPPLIER_CODE
	 * 
	 * @param supplierCode
	 *            the value for PIP_MMS_STORE.SUPPLIER_CODE
	 * 
	 * @mbggenerated Wed Sep 10 09:47:34 CST 2014
	 */
	public void setSupplierCode(String supplierCode) {
		this.supplierCode = supplierCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PIP_MMS_STORE.CREATE_DATE
	 * 
	 * @return the value of PIP_MMS_STORE.CREATE_DATE
	 * 
	 * @mbggenerated Wed Sep 10 09:47:34 CST 2014
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PIP_MMS_STORE.CREATE_DATE
	 * 
	 * @param createDate
	 *            the value for PIP_MMS_STORE.CREATE_DATE
	 * 
	 * @mbggenerated Wed Sep 10 09:47:34 CST 2014
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PIP_MMS_STORE.CREATE_BY
	 * 
	 * @return the value of PIP_MMS_STORE.CREATE_BY
	 * 
	 * @mbggenerated Wed Sep 10 09:47:34 CST 2014
	 */
	public String getCreateBy() {
		return createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PIP_MMS_STORE.CREATE_BY
	 * 
	 * @param createBy
	 *            the value for PIP_MMS_STORE.CREATE_BY
	 * 
	 * @mbggenerated Wed Sep 10 09:47:34 CST 2014
	 */
	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PIP_MMS_STORE.PRODUCE_DATE
	 * 
	 * @return the value of PIP_MMS_STORE.PRODUCE_DATE
	 * 
	 * @mbggenerated Wed Sep 10 09:47:34 CST 2014
	 */
	public Date getProduceDate() {
		return produceDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PIP_MMS_STORE.PRODUCE_DATE
	 * 
	 * @param produceDate
	 *            the value for PIP_MMS_STORE.PRODUCE_DATE
	 * 
	 * @mbggenerated Wed Sep 10 09:47:34 CST 2014
	 */
	public void setProduceDate(Date produceDate) {
		this.produceDate = produceDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PIP_MMS_STORE.MATERL_SPEC
	 * 
	 * @return the value of PIP_MMS_STORE.MATERL_SPEC
	 * 
	 * @mbggenerated Wed Sep 10 09:47:34 CST 2014
	 */
	public String getMaterlSpec() {
		return materlSpec;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PIP_MMS_STORE.MATERL_SPEC
	 * 
	 * @param materlSpec
	 *            the value for PIP_MMS_STORE.MATERL_SPEC
	 * 
	 * @mbggenerated Wed Sep 10 09:47:34 CST 2014
	 */
	public void setMaterlSpec(String materlSpec) {
		this.materlSpec = materlSpec;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PIP_MMS_STORE.ASSETS_STATUS
	 * 
	 * @return the value of PIP_MMS_STORE.ASSETS_STATUS
	 * 
	 * @mbggenerated Wed Sep 10 09:47:34 CST 2014
	 */
	public Short getAssetsStatus() {
		return assetsStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PIP_MMS_STORE.ASSETS_STATUS
	 * 
	 * @param assetsStatus
	 *            the value for PIP_MMS_STORE.ASSETS_STATUS
	 * 
	 * @mbggenerated Wed Sep 10 09:47:34 CST 2014
	 */
	public void setAssetsStatus(Short assetsStatus) {
		this.assetsStatus = assetsStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PIP_MMS_STORE.IS_MEASURE
	 * 
	 * @return the value of PIP_MMS_STORE.IS_MEASURE
	 * 
	 * @mbggenerated Wed Sep 10 09:47:34 CST 2014
	 */
	public Short getIsMeasure() {
		return isMeasure;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PIP_MMS_STORE.IS_MEASURE
	 * 
	 * @param isMeasure
	 *            the value for PIP_MMS_STORE.IS_MEASURE
	 * 
	 * @mbggenerated Wed Sep 10 09:47:34 CST 2014
	 */
	public void setIsMeasure(Short isMeasure) {
		this.isMeasure = isMeasure;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PIP_MMS_STORE.NEXT_MEASURE_DATE
	 * 
	 * @return the value of PIP_MMS_STORE.NEXT_MEASURE_DATE
	 * 
	 * @mbggenerated Wed Sep 10 09:47:34 CST 2014
	 */
	public Date getNextMeasureDate() {
		return nextMeasureDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PIP_MMS_STORE.NEXT_MEASURE_DATE
	 * 
	 * @param nextMeasureDate
	 *            the value for PIP_MMS_STORE.NEXT_MEASURE_DATE
	 * 
	 * @mbggenerated Wed Sep 10 09:47:34 CST 2014
	 */
	public void setNextMeasureDate(Date nextMeasureDate) {
		this.nextMeasureDate = nextMeasureDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PIP_MMS_STORE.MEASURE_PERIOD
	 * 
	 * @return the value of PIP_MMS_STORE.MEASURE_PERIOD
	 * 
	 * @mbggenerated Wed Sep 10 09:47:34 CST 2014
	 */
	public Long getMeasurePeriod() {
		return measurePeriod;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PIP_MMS_STORE.MEASURE_PERIOD
	 * 
	 * @param measurePeriod
	 *            the value for PIP_MMS_STORE.MEASURE_PERIOD
	 * 
	 * @mbggenerated Wed Sep 10 09:47:34 CST 2014
	 */
	public void setMeasurePeriod(Long measurePeriod) {
		this.measurePeriod = measurePeriod;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PIP_MMS_STORE.ARCHIVES_NO
	 * 
	 * @return the value of PIP_MMS_STORE.ARCHIVES_NO
	 * 
	 * @mbggenerated Wed Sep 10 09:47:34 CST 2014
	 */
	public String getArchivesNo() {
		return archivesNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PIP_MMS_STORE.ARCHIVES_NO
	 * 
	 * @param archivesNo
	 *            the value for PIP_MMS_STORE.ARCHIVES_NO
	 * 
	 * @mbggenerated Wed Sep 10 09:47:34 CST 2014
	 */
	public void setArchivesNo(String archivesNo) {
		this.archivesNo = archivesNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PIP_MMS_STORE.CLASS_CODE
	 * 
	 * @return the value of PIP_MMS_STORE.CLASS_CODE
	 * 
	 * @mbggenerated Wed Sep 10 09:47:34 CST 2014
	 */
	public String getClassCode() {
		return classCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PIP_MMS_STORE.CLASS_CODE
	 * 
	 * @param classCode
	 *            the value for PIP_MMS_STORE.CLASS_CODE
	 * 
	 * @mbggenerated Wed Sep 10 09:47:34 CST 2014
	 */
	public void setClassCode(String classCode) {
		this.classCode = classCode;
	}
}