package com.bdcor.pip.web.data.domain;

public class PipCommPatientKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIP_COMM_PATIENT.PATIENT_ID
     *
     * @mbggenerated
     */
    private String patientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIP_COMM_PATIENT.PROJECT_ID
     *
     * @mbggenerated
     */
    private String projectId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIP_COMM_PATIENT.PATIENT_ID
     *
     * @return the value of PIP_COMM_PATIENT.PATIENT_ID
     *
     * @mbggenerated
     */
    public String getPatientId() {
        return patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIP_COMM_PATIENT.PATIENT_ID
     *
     * @param patientId the value for PIP_COMM_PATIENT.PATIENT_ID
     *
     * @mbggenerated
     */
    public void setPatientId(String patientId) {
        this.patientId = patientId == null ? null : patientId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIP_COMM_PATIENT.PROJECT_ID
     *
     * @return the value of PIP_COMM_PATIENT.PROJECT_ID
     *
     * @mbggenerated
     */
    public String getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIP_COMM_PATIENT.PROJECT_ID
     *
     * @param projectId the value for PIP_COMM_PATIENT.PROJECT_ID
     *
     * @mbggenerated
     */
    public void setProjectId(String projectId) {
        this.projectId = projectId == null ? null : projectId.trim();
    }
}