package com.bdcor.pip.web.data.domain;

import java.util.Date;

public class PipCommPatientQcLog extends PipCommPatientQcLogKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PIP_COMM_PATIENT_QC_LOG.SOURCE_ID
	 * @mbggenerated
	 */
	private String sourceId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PIP_COMM_PATIENT_QC_LOG.START_DATE
	 * @mbggenerated
	 */
	private Date startDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PIP_COMM_PATIENT_QC_LOG.END_DATE
	 * @mbggenerated
	 */
	private Date endDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PIP_COMM_PATIENT_QC_LOG.CREATE_BY
	 * @mbggenerated
	 */
	private String createBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PIP_COMM_PATIENT_QC_LOG.CREATE_DATE
	 * @mbggenerated
	 */
	private Date createDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PIP_COMM_PATIENT_QC_LOG.SOURCE_ID
	 * @return  the value of PIP_COMM_PATIENT_QC_LOG.SOURCE_ID
	 * @mbggenerated
	 */
	public String getSourceId() {
		return sourceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PIP_COMM_PATIENT_QC_LOG.SOURCE_ID
	 * @param sourceId  the value for PIP_COMM_PATIENT_QC_LOG.SOURCE_ID
	 * @mbggenerated
	 */
	public void setSourceId(String sourceId) {
		this.sourceId = sourceId == null ? null : sourceId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PIP_COMM_PATIENT_QC_LOG.START_DATE
	 * @return  the value of PIP_COMM_PATIENT_QC_LOG.START_DATE
	 * @mbggenerated
	 */
	public Date getStartDate() {
		return startDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PIP_COMM_PATIENT_QC_LOG.START_DATE
	 * @param startDate  the value for PIP_COMM_PATIENT_QC_LOG.START_DATE
	 * @mbggenerated
	 */
	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PIP_COMM_PATIENT_QC_LOG.END_DATE
	 * @return  the value of PIP_COMM_PATIENT_QC_LOG.END_DATE
	 * @mbggenerated
	 */
	public Date getEndDate() {
		return endDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PIP_COMM_PATIENT_QC_LOG.END_DATE
	 * @param endDate  the value for PIP_COMM_PATIENT_QC_LOG.END_DATE
	 * @mbggenerated
	 */
	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PIP_COMM_PATIENT_QC_LOG.CREATE_BY
	 * @return  the value of PIP_COMM_PATIENT_QC_LOG.CREATE_BY
	 * @mbggenerated
	 */
	public String getCreateBy() {
		return createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PIP_COMM_PATIENT_QC_LOG.CREATE_BY
	 * @param createBy  the value for PIP_COMM_PATIENT_QC_LOG.CREATE_BY
	 * @mbggenerated
	 */
	public void setCreateBy(String createBy) {
		this.createBy = createBy == null ? null : createBy.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PIP_COMM_PATIENT_QC_LOG.CREATE_DATE
	 * @return  the value of PIP_COMM_PATIENT_QC_LOG.CREATE_DATE
	 * @mbggenerated
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PIP_COMM_PATIENT_QC_LOG.CREATE_DATE
	 * @param createDate  the value for PIP_COMM_PATIENT_QC_LOG.CREATE_DATE
	 * @mbggenerated
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}
}