package com.bdcor.pip.web.data.dao;

import com.bdcor.pip.core.persistence.MyBatisRepository;
import com.bdcor.pip.web.data.domain.PipCommLccMsg;
import com.bdcor.pip.web.data.domain.PipCommLccMsgExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.bdcor.pip.web.data.domain.PipCommLccMsgKey;

@MyBatisRepository
public interface PipCommLccMsgMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PIP_COMM_LCC_MSG
	 * @mbggenerated
	 */
	int countByExample(PipCommLccMsgExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PIP_COMM_LCC_MSG
	 * @mbggenerated
	 */
	int deleteByExample(PipCommLccMsgExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PIP_COMM_LCC_MSG
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(PipCommLccMsgKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PIP_COMM_LCC_MSG
	 * @mbggenerated
	 */
	int insert(PipCommLccMsg record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PIP_COMM_LCC_MSG
	 * @mbggenerated
	 */
	int insertSelective(PipCommLccMsg record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PIP_COMM_LCC_MSG
	 * @mbggenerated
	 */
	List<PipCommLccMsg> selectByExample(PipCommLccMsgExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PIP_COMM_LCC_MSG
	 * @mbggenerated
	 */
	PipCommLccMsg selectByPrimaryKey(PipCommLccMsgKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PIP_COMM_LCC_MSG
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") PipCommLccMsg record,
			@Param("example") PipCommLccMsgExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PIP_COMM_LCC_MSG
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") PipCommLccMsg record,
			@Param("example") PipCommLccMsgExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PIP_COMM_LCC_MSG
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(PipCommLccMsg record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PIP_COMM_LCC_MSG
	 * @mbggenerated
	 */
	int updateByPrimaryKey(PipCommLccMsg record);
	
	public List getLccMsgNum(@Param("toLccCode")String toLccCode , @Param("projectId")String projectId);
	
}