package com.bdcor.pip.web.data.domain;

import java.util.Date;

public class UqsQuestionSet extends UqsQuestionSetKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIP_UQS_QUESTIONSET.DISPLAY_NAME
     *
     * @mbggenerated
     */
    private String displayName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIP_UQS_QUESTIONSET.DESCRIPTION
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIP_UQS_QUESTIONSET.ORDER_IN_QUESTIONNAIRE
     *
     * @mbggenerated
     */
    private Long orderInQuestionnaire;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIP_UQS_QUESTIONSET.CREATE_BY
     *
     * @mbggenerated
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIP_UQS_QUESTIONSET.CREATE_DATE
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIP_UQS_QUESTIONSET.UPDATE_BY
     *
     * @mbggenerated
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIP_UQS_QUESTIONSET.UPDATE_DATE
     *
     * @mbggenerated
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIP_UQS_QUESTIONSET.IS_REMOVED
     *
     * @mbggenerated
     */
    private Short isRemoved;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIP_UQS_QUESTIONSET.REMARK
     *
     * @mbggenerated
     */
    private String remark;
    
    private String version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIP_UQS_QUESTIONSET.DISPLAY_NAME
     *
     * @return the value of PIP_UQS_QUESTIONSET.DISPLAY_NAME
     *
     * @mbggenerated
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIP_UQS_QUESTIONSET.DISPLAY_NAME
     *
     * @param displayName the value for PIP_UQS_QUESTIONSET.DISPLAY_NAME
     *
     * @mbggenerated
     */
    public void setDisplayName(String displayName) {
        this.displayName = displayName == null ? null : displayName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIP_UQS_QUESTIONSET.DESCRIPTION
     *
     * @return the value of PIP_UQS_QUESTIONSET.DESCRIPTION
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIP_UQS_QUESTIONSET.DESCRIPTION
     *
     * @param description the value for PIP_UQS_QUESTIONSET.DESCRIPTION
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIP_UQS_QUESTIONSET.ORDER_IN_QUESTIONNAIRE
     *
     * @return the value of PIP_UQS_QUESTIONSET.ORDER_IN_QUESTIONNAIRE
     *
     * @mbggenerated
     */
    public Long getOrderInQuestionnaire() {
        return orderInQuestionnaire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIP_UQS_QUESTIONSET.ORDER_IN_QUESTIONNAIRE
     *
     * @param orderInQuestionnaire the value for PIP_UQS_QUESTIONSET.ORDER_IN_QUESTIONNAIRE
     *
     * @mbggenerated
     */
    public void setOrderInQuestionnaire(Long orderInQuestionnaire) {
        this.orderInQuestionnaire = orderInQuestionnaire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIP_UQS_QUESTIONSET.CREATE_BY
     *
     * @return the value of PIP_UQS_QUESTIONSET.CREATE_BY
     *
     * @mbggenerated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIP_UQS_QUESTIONSET.CREATE_BY
     *
     * @param createBy the value for PIP_UQS_QUESTIONSET.CREATE_BY
     *
     * @mbggenerated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIP_UQS_QUESTIONSET.CREATE_DATE
     *
     * @return the value of PIP_UQS_QUESTIONSET.CREATE_DATE
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIP_UQS_QUESTIONSET.CREATE_DATE
     *
     * @param createDate the value for PIP_UQS_QUESTIONSET.CREATE_DATE
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIP_UQS_QUESTIONSET.UPDATE_BY
     *
     * @return the value of PIP_UQS_QUESTIONSET.UPDATE_BY
     *
     * @mbggenerated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIP_UQS_QUESTIONSET.UPDATE_BY
     *
     * @param updateBy the value for PIP_UQS_QUESTIONSET.UPDATE_BY
     *
     * @mbggenerated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIP_UQS_QUESTIONSET.UPDATE_DATE
     *
     * @return the value of PIP_UQS_QUESTIONSET.UPDATE_DATE
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIP_UQS_QUESTIONSET.UPDATE_DATE
     *
     * @param updateDate the value for PIP_UQS_QUESTIONSET.UPDATE_DATE
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIP_UQS_QUESTIONSET.IS_REMOVED
     *
     * @return the value of PIP_UQS_QUESTIONSET.IS_REMOVED
     *
     * @mbggenerated
     */
    public Short getIsRemoved() {
        return isRemoved;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIP_UQS_QUESTIONSET.IS_REMOVED
     *
     * @param isRemoved the value for PIP_UQS_QUESTIONSET.IS_REMOVED
     *
     * @mbggenerated
     */
    public void setIsRemoved(Short isRemoved) {
        this.isRemoved = isRemoved;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIP_UQS_QUESTIONSET.REMARK
     *
     * @return the value of PIP_UQS_QUESTIONSET.REMARK
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIP_UQS_QUESTIONSET.REMARK
     *
     * @param remark the value for PIP_UQS_QUESTIONSET.REMARK
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

	public String getVersion() {
		return version;
	}

	public void setVersion(String version) {
		this.version = version;
	}
    
}