package com.bdcor.pip.web.data.domain;

import java.util.Date;

public class PipFeeInfo extends PipFeeInfoKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIP_FEE_INFO.UPLOAD_DATE
     *
     * @mbggenerated
     */
    private Date uploadDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIP_FEE_INFO.REGISTRATION_DATE
     *
     * @mbggenerated
     */
    private Date registrationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIP_FEE_INFO.LCC_CODE
     *
     * @mbggenerated
     */
    private String lccCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIP_FEE_INFO.UPLOAD_DATE
     *
     * @return the value of PIP_FEE_INFO.UPLOAD_DATE
     *
     * @mbggenerated
     */
    public Date getUploadDate() {
        return uploadDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIP_FEE_INFO.UPLOAD_DATE
     *
     * @param uploadDate the value for PIP_FEE_INFO.UPLOAD_DATE
     *
     * @mbggenerated
     */
    public void setUploadDate(Date uploadDate) {
        this.uploadDate = uploadDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIP_FEE_INFO.REGISTRATION_DATE
     *
     * @return the value of PIP_FEE_INFO.REGISTRATION_DATE
     *
     * @mbggenerated
     */
    public Date getRegistrationDate() {
        return registrationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIP_FEE_INFO.REGISTRATION_DATE
     *
     * @param registrationDate the value for PIP_FEE_INFO.REGISTRATION_DATE
     *
     * @mbggenerated
     */
    public void setRegistrationDate(Date registrationDate) {
        this.registrationDate = registrationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIP_FEE_INFO.LCC_CODE
     *
     * @return the value of PIP_FEE_INFO.LCC_CODE
     *
     * @mbggenerated
     */
    public String getLccCode() {
        return lccCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIP_FEE_INFO.LCC_CODE
     *
     * @param lccCode the value for PIP_FEE_INFO.LCC_CODE
     *
     * @mbggenerated
     */
    public void setLccCode(String lccCode) {
        this.lccCode = lccCode == null ? null : lccCode.trim();
    }
}