package com.bdcor.pip.web.data.dao;

import com.bdcor.pip.core.persistence.MyBatisRepository;
import com.bdcor.pip.web.data.domain.ReportFactoryView;
import com.bdcor.pip.web.data.domain.ReportFactoryViewExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

@MyBatisRepository
public interface ReportFactoryViewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REPORT_FACTORY_VIEW
     *
     * @mbggenerated
     */
    int countByExample(ReportFactoryViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REPORT_FACTORY_VIEW
     *
     * @mbggenerated
     */
    int deleteByExample(ReportFactoryViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REPORT_FACTORY_VIEW
     *
     * @mbggenerated
     */
    int insert(ReportFactoryView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REPORT_FACTORY_VIEW
     *
     * @mbggenerated
     */
    int insertSelective(ReportFactoryView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REPORT_FACTORY_VIEW
     *
     * @mbggenerated
     */
    List<ReportFactoryView> selectByExample(ReportFactoryViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REPORT_FACTORY_VIEW
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ReportFactoryView record, @Param("example") ReportFactoryViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REPORT_FACTORY_VIEW
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ReportFactoryView record, @Param("example") ReportFactoryViewExample example);
}